#![doc = "Peripheral access API for NRF52833 microcontrollers (generated using svd2rust v0.37.0 ( ))\n\nYou can find an overview of the generated API [here].\n\nAPI features to be included in the [next] svd2rust release can be generated by cloning the svd2rust [repository], checking out the above commit, and running `cargo doc --open`.\n\n[here]: https://docs.rs/svd2rust/0.37.0/svd2rust/#peripheral-api\n[next]: https://github.com/rust-embedded/svd2rust/blob/master/CHANGELOG.md#unreleased\n[repository]: https://github.com/rust-embedded/svd2rust"]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![no_std]
#![cfg_attr(docsrs, feature(doc_auto_cfg))]
#[doc = r"Number available in the NVIC for configuring priority"]
pub const NVIC_PRIO_BITS: u8 = 3;
#[allow(unused_imports)]
use generic::*;
#[doc = r"Common register and bit access and modify traits"]
pub mod generic;
#[cfg(feature = "rt")]
extern "C" {
    fn POWER_CLOCK();
    fn RADIO();
    fn UARTE0_UART0();
    fn SPIM0_SPIS0_TWIM0_TWIS0_SPI0_TWI0();
    fn SPIM1_SPIS1_TWIM1_TWIS1_SPI1_TWI1();
    fn NFCT();
    fn GPIOTE();
    fn SAADC();
    fn TIMER0();
    fn TIMER1();
    fn TIMER2();
    fn RTC0();
    fn TEMP();
    fn RNG();
    fn ECB();
    fn CCM_AAR();
    fn WDT();
    fn RTC1();
    fn QDEC();
    fn COMP_LPCOMP();
    fn SWI0_EGU0();
    fn SWI1_EGU1();
    fn SWI2_EGU2();
    fn SWI3_EGU3();
    fn SWI4_EGU4();
    fn SWI5_EGU5();
    fn TIMER3();
    fn TIMER4();
    fn PWM0();
    fn PDM();
    fn MWU();
    fn PWM1();
    fn PWM2();
    fn SPIM2_SPIS2_SPI2();
    fn RTC2();
    fn I2S();
    fn FPU();
    fn USBD();
    fn UARTE1();
    fn PWM3();
    fn SPIM3();
}
#[doc(hidden)]
#[repr(C)]
pub union Vector {
    _handler: unsafe extern "C" fn(),
    _reserved: u32,
}
#[cfg(feature = "rt")]
#[doc(hidden)]
#[link_section = ".vector_table.interrupts"]
#[no_mangle]
pub static __INTERRUPTS: [Vector; 48] = [
    Vector {
        _handler: POWER_CLOCK,
    },
    Vector { _handler: RADIO },
    Vector {
        _handler: UARTE0_UART0,
    },
    Vector {
        _handler: SPIM0_SPIS0_TWIM0_TWIS0_SPI0_TWI0,
    },
    Vector {
        _handler: SPIM1_SPIS1_TWIM1_TWIS1_SPI1_TWI1,
    },
    Vector { _handler: NFCT },
    Vector { _handler: GPIOTE },
    Vector { _handler: SAADC },
    Vector { _handler: TIMER0 },
    Vector { _handler: TIMER1 },
    Vector { _handler: TIMER2 },
    Vector { _handler: RTC0 },
    Vector { _handler: TEMP },
    Vector { _handler: RNG },
    Vector { _handler: ECB },
    Vector { _handler: CCM_AAR },
    Vector { _handler: WDT },
    Vector { _handler: RTC1 },
    Vector { _handler: QDEC },
    Vector {
        _handler: COMP_LPCOMP,
    },
    Vector {
        _handler: SWI0_EGU0,
    },
    Vector {
        _handler: SWI1_EGU1,
    },
    Vector {
        _handler: SWI2_EGU2,
    },
    Vector {
        _handler: SWI3_EGU3,
    },
    Vector {
        _handler: SWI4_EGU4,
    },
    Vector {
        _handler: SWI5_EGU5,
    },
    Vector { _handler: TIMER3 },
    Vector { _handler: TIMER4 },
    Vector { _handler: PWM0 },
    Vector { _handler: PDM },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: MWU },
    Vector { _handler: PWM1 },
    Vector { _handler: PWM2 },
    Vector {
        _handler: SPIM2_SPIS2_SPI2,
    },
    Vector { _handler: RTC2 },
    Vector { _handler: I2S },
    Vector { _handler: FPU },
    Vector { _handler: USBD },
    Vector { _handler: UARTE1 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: PWM3 },
    Vector { _reserved: 0 },
    Vector { _handler: SPIM3 },
];
#[doc = r"Enumeration of all the interrupts."]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
#[repr(u16)]
pub enum Interrupt {
    #[doc = "0 - POWER_CLOCK"]
    POWER_CLOCK = 0,
    #[doc = "1 - RADIO"]
    RADIO = 1,
    #[doc = "2 - UARTE0_UART0"]
    UARTE0_UART0 = 2,
    #[doc = "3 - SPIM0_SPIS0_TWIM0_TWIS0_SPI0_TWI0"]
    SPIM0_SPIS0_TWIM0_TWIS0_SPI0_TWI0 = 3,
    #[doc = "4 - SPIM1_SPIS1_TWIM1_TWIS1_SPI1_TWI1"]
    SPIM1_SPIS1_TWIM1_TWIS1_SPI1_TWI1 = 4,
    #[doc = "5 - NFCT"]
    NFCT = 5,
    #[doc = "6 - GPIOTE"]
    GPIOTE = 6,
    #[doc = "7 - SAADC"]
    SAADC = 7,
    #[doc = "8 - TIMER0"]
    TIMER0 = 8,
    #[doc = "9 - TIMER1"]
    TIMER1 = 9,
    #[doc = "10 - TIMER2"]
    TIMER2 = 10,
    #[doc = "11 - RTC0"]
    RTC0 = 11,
    #[doc = "12 - TEMP"]
    TEMP = 12,
    #[doc = "13 - RNG"]
    RNG = 13,
    #[doc = "14 - ECB"]
    ECB = 14,
    #[doc = "15 - CCM_AAR"]
    CCM_AAR = 15,
    #[doc = "16 - WDT"]
    WDT = 16,
    #[doc = "17 - RTC1"]
    RTC1 = 17,
    #[doc = "18 - QDEC"]
    QDEC = 18,
    #[doc = "19 - COMP_LPCOMP"]
    COMP_LPCOMP = 19,
    #[doc = "20 - SWI0_EGU0"]
    SWI0_EGU0 = 20,
    #[doc = "21 - SWI1_EGU1"]
    SWI1_EGU1 = 21,
    #[doc = "22 - SWI2_EGU2"]
    SWI2_EGU2 = 22,
    #[doc = "23 - SWI3_EGU3"]
    SWI3_EGU3 = 23,
    #[doc = "24 - SWI4_EGU4"]
    SWI4_EGU4 = 24,
    #[doc = "25 - SWI5_EGU5"]
    SWI5_EGU5 = 25,
    #[doc = "26 - TIMER3"]
    TIMER3 = 26,
    #[doc = "27 - TIMER4"]
    TIMER4 = 27,
    #[doc = "28 - PWM0"]
    PWM0 = 28,
    #[doc = "29 - PDM"]
    PDM = 29,
    #[doc = "32 - MWU"]
    MWU = 32,
    #[doc = "33 - PWM1"]
    PWM1 = 33,
    #[doc = "34 - PWM2"]
    PWM2 = 34,
    #[doc = "35 - SPIM2_SPIS2_SPI2"]
    SPIM2_SPIS2_SPI2 = 35,
    #[doc = "36 - RTC2"]
    RTC2 = 36,
    #[doc = "37 - I2S"]
    I2S = 37,
    #[doc = "38 - FPU"]
    FPU = 38,
    #[doc = "39 - USBD"]
    USBD = 39,
    #[doc = "40 - UARTE1"]
    UARTE1 = 40,
    #[doc = "45 - PWM3"]
    PWM3 = 45,
    #[doc = "47 - SPIM3"]
    SPIM3 = 47,
}
unsafe impl cortex_m::interrupt::InterruptNumber for Interrupt {
    #[inline(always)]
    fn number(self) -> u16 {
        self as u16
    }
}
#[doc = "Factory information configuration registers"]
pub type Ficr = crate::Periph<ficr::RegisterBlock, 0x1000_0000>;
impl core::fmt::Debug for Ficr {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Ficr").finish()
    }
}
#[doc = "Factory information configuration registers"]
pub mod ficr;
#[doc = "User information configuration registers"]
pub type Uicr = crate::Periph<uicr::RegisterBlock, 0x1000_1000>;
impl core::fmt::Debug for Uicr {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uicr").finish()
    }
}
#[doc = "User information configuration registers"]
pub mod uicr;
#[doc = "Access Port Protection"]
pub type Approtect = crate::Periph<approtect::RegisterBlock, 0x4000_0000>;
impl core::fmt::Debug for Approtect {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Approtect").finish()
    }
}
#[doc = "Access Port Protection"]
pub mod approtect;
#[doc = "Clock control"]
pub type Clock = crate::Periph<clock::RegisterBlock, 0x4000_0000>;
impl core::fmt::Debug for Clock {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Clock").finish()
    }
}
#[doc = "Clock control"]
pub mod clock;
#[doc = "Power control"]
pub type Power = crate::Periph<power::RegisterBlock, 0x4000_0000>;
impl core::fmt::Debug for Power {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Power").finish()
    }
}
#[doc = "Power control"]
pub mod power;
#[doc = "GPIO Port 1"]
pub type P0 = crate::Periph<p0::RegisterBlock, 0x5000_0000>;
impl core::fmt::Debug for P0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("P0").finish()
    }
}
#[doc = "GPIO Port 1"]
pub mod p0;
#[doc = "GPIO Port 2"]
pub type P1 = crate::Periph<p0::RegisterBlock, 0x5000_0300>;
impl core::fmt::Debug for P1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("P1").finish()
    }
}
#[doc = "GPIO Port 2"]
pub use self::p0 as p1;
#[doc = "2.4 GHz radio"]
pub type Radio = crate::Periph<radio::RegisterBlock, 0x4000_1000>;
impl core::fmt::Debug for Radio {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Radio").finish()
    }
}
#[doc = "2.4 GHz radio"]
pub mod radio;
#[doc = "Universal Asynchronous Receiver/Transmitter"]
pub type Uart0 = crate::Periph<uart0::RegisterBlock, 0x4000_2000>;
impl core::fmt::Debug for Uart0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uart0").finish()
    }
}
#[doc = "Universal Asynchronous Receiver/Transmitter"]
pub mod uart0;
#[doc = "UART with EasyDMA 0"]
pub type Uarte0 = crate::Periph<uarte0::RegisterBlock, 0x4000_2000>;
impl core::fmt::Debug for Uarte0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uarte0").finish()
    }
}
#[doc = "UART with EasyDMA 0"]
pub mod uarte0;
#[doc = "Serial Peripheral Interface 0"]
pub type Spi0 = crate::Periph<spi0::RegisterBlock, 0x4000_3000>;
impl core::fmt::Debug for Spi0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spi0").finish()
    }
}
#[doc = "Serial Peripheral Interface 0"]
pub mod spi0;
#[doc = "Serial Peripheral Interface Master with EasyDMA 0"]
pub type Spim0 = crate::Periph<spim0::RegisterBlock, 0x4000_3000>;
impl core::fmt::Debug for Spim0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spim0").finish()
    }
}
#[doc = "Serial Peripheral Interface Master with EasyDMA 0"]
pub mod spim0;
#[doc = "SPI Slave 0"]
pub type Spis0 = crate::Periph<spis0::RegisterBlock, 0x4000_3000>;
impl core::fmt::Debug for Spis0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spis0").finish()
    }
}
#[doc = "SPI Slave 0"]
pub mod spis0;
#[doc = "I2C compatible Two-Wire Interface 0"]
pub type Twi0 = crate::Periph<twi0::RegisterBlock, 0x4000_3000>;
impl core::fmt::Debug for Twi0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Twi0").finish()
    }
}
#[doc = "I2C compatible Two-Wire Interface 0"]
pub mod twi0;
#[doc = "I2C compatible Two-Wire Master Interface with EasyDMA 0"]
pub type Twim0 = crate::Periph<twim0::RegisterBlock, 0x4000_3000>;
impl core::fmt::Debug for Twim0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Twim0").finish()
    }
}
#[doc = "I2C compatible Two-Wire Master Interface with EasyDMA 0"]
pub mod twim0;
#[doc = "I2C compatible Two-Wire Slave Interface with EasyDMA 0"]
pub type Twis0 = crate::Periph<twis0::RegisterBlock, 0x4000_3000>;
impl core::fmt::Debug for Twis0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Twis0").finish()
    }
}
#[doc = "I2C compatible Two-Wire Slave Interface with EasyDMA 0"]
pub mod twis0;
#[doc = "Serial Peripheral Interface 1"]
pub type Spi1 = crate::Periph<spi0::RegisterBlock, 0x4000_4000>;
impl core::fmt::Debug for Spi1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spi1").finish()
    }
}
#[doc = "Serial Peripheral Interface 1"]
pub use self::spi0 as spi1;
#[doc = "Serial Peripheral Interface Master with EasyDMA 1"]
pub type Spim1 = crate::Periph<spim0::RegisterBlock, 0x4000_4000>;
impl core::fmt::Debug for Spim1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spim1").finish()
    }
}
#[doc = "Serial Peripheral Interface Master with EasyDMA 1"]
pub use self::spim0 as spim1;
#[doc = "SPI Slave 1"]
pub type Spis1 = crate::Periph<spis0::RegisterBlock, 0x4000_4000>;
impl core::fmt::Debug for Spis1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spis1").finish()
    }
}
#[doc = "SPI Slave 1"]
pub use self::spis0 as spis1;
#[doc = "I2C compatible Two-Wire Interface 1"]
pub type Twi1 = crate::Periph<twi0::RegisterBlock, 0x4000_4000>;
impl core::fmt::Debug for Twi1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Twi1").finish()
    }
}
#[doc = "I2C compatible Two-Wire Interface 1"]
pub use self::twi0 as twi1;
#[doc = "I2C compatible Two-Wire Master Interface with EasyDMA 1"]
pub type Twim1 = crate::Periph<twim0::RegisterBlock, 0x4000_4000>;
impl core::fmt::Debug for Twim1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Twim1").finish()
    }
}
#[doc = "I2C compatible Two-Wire Master Interface with EasyDMA 1"]
pub use self::twim0 as twim1;
#[doc = "I2C compatible Two-Wire Slave Interface with EasyDMA 1"]
pub type Twis1 = crate::Periph<twis0::RegisterBlock, 0x4000_4000>;
impl core::fmt::Debug for Twis1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Twis1").finish()
    }
}
#[doc = "I2C compatible Two-Wire Slave Interface with EasyDMA 1"]
pub use self::twis0 as twis1;
#[doc = "NFC-A compatible radio"]
pub type Nfct = crate::Periph<nfct::RegisterBlock, 0x4000_5000>;
impl core::fmt::Debug for Nfct {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Nfct").finish()
    }
}
#[doc = "NFC-A compatible radio"]
pub mod nfct;
#[doc = "GPIO Tasks and Events"]
pub type Gpiote = crate::Periph<gpiote::RegisterBlock, 0x4000_6000>;
impl core::fmt::Debug for Gpiote {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpiote").finish()
    }
}
#[doc = "GPIO Tasks and Events"]
pub mod gpiote;
#[doc = "Successive approximation register (SAR) analog-to-digital converter"]
pub type Saadc = crate::Periph<saadc::RegisterBlock, 0x4000_7000>;
impl core::fmt::Debug for Saadc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Saadc").finish()
    }
}
#[doc = "Successive approximation register (SAR) analog-to-digital converter"]
pub mod saadc;
#[doc = "Timer/Counter 0"]
pub type Timer0 = crate::Periph<timer0::RegisterBlock, 0x4000_8000>;
impl core::fmt::Debug for Timer0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timer0").finish()
    }
}
#[doc = "Timer/Counter 0"]
pub mod timer0;
#[doc = "Timer/Counter 1"]
pub type Timer1 = crate::Periph<timer0::RegisterBlock, 0x4000_9000>;
impl core::fmt::Debug for Timer1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timer1").finish()
    }
}
#[doc = "Timer/Counter 1"]
pub use self::timer0 as timer1;
#[doc = "Timer/Counter 2"]
pub type Timer2 = crate::Periph<timer0::RegisterBlock, 0x4000_a000>;
impl core::fmt::Debug for Timer2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timer2").finish()
    }
}
#[doc = "Timer/Counter 2"]
pub use self::timer0 as timer2;
#[doc = "Real time counter 0"]
pub type Rtc0 = crate::Periph<rtc0::RegisterBlock, 0x4000_b000>;
impl core::fmt::Debug for Rtc0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Rtc0").finish()
    }
}
#[doc = "Real time counter 0"]
pub mod rtc0;
#[doc = "Temperature Sensor"]
pub type Temp = crate::Periph<temp::RegisterBlock, 0x4000_c000>;
impl core::fmt::Debug for Temp {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Temp").finish()
    }
}
#[doc = "Temperature Sensor"]
pub mod temp;
#[doc = "Random Number Generator"]
pub type Rng = crate::Periph<rng::RegisterBlock, 0x4000_d000>;
impl core::fmt::Debug for Rng {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Rng").finish()
    }
}
#[doc = "Random Number Generator"]
pub mod rng;
#[doc = "AES ECB Mode Encryption"]
pub type Ecb = crate::Periph<ecb::RegisterBlock, 0x4000_e000>;
impl core::fmt::Debug for Ecb {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Ecb").finish()
    }
}
#[doc = "AES ECB Mode Encryption"]
pub mod ecb;
#[doc = "Accelerated Address Resolver"]
pub type Aar = crate::Periph<aar::RegisterBlock, 0x4000_f000>;
impl core::fmt::Debug for Aar {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Aar").finish()
    }
}
#[doc = "Accelerated Address Resolver"]
pub mod aar;
#[doc = "AES CCM mode encryption"]
pub type Ccm = crate::Periph<ccm::RegisterBlock, 0x4000_f000>;
impl core::fmt::Debug for Ccm {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Ccm").finish()
    }
}
#[doc = "AES CCM mode encryption"]
pub mod ccm;
#[doc = "Watchdog Timer"]
pub type Wdt = crate::Periph<wdt::RegisterBlock, 0x4001_0000>;
impl core::fmt::Debug for Wdt {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Wdt").finish()
    }
}
#[doc = "Watchdog Timer"]
pub mod wdt;
#[doc = "Real time counter 1"]
pub type Rtc1 = crate::Periph<rtc0::RegisterBlock, 0x4001_1000>;
impl core::fmt::Debug for Rtc1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Rtc1").finish()
    }
}
#[doc = "Real time counter 1"]
pub use self::rtc0 as rtc1;
#[doc = "Quadrature Decoder"]
pub type Qdec = crate::Periph<qdec::RegisterBlock, 0x4001_2000>;
impl core::fmt::Debug for Qdec {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Qdec").finish()
    }
}
#[doc = "Quadrature Decoder"]
pub mod qdec;
#[doc = "Comparator"]
pub type Comp = crate::Periph<comp::RegisterBlock, 0x4001_3000>;
impl core::fmt::Debug for Comp {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Comp").finish()
    }
}
#[doc = "Comparator"]
pub mod comp;
#[doc = "Low-power comparator"]
pub type Lpcomp = crate::Periph<lpcomp::RegisterBlock, 0x4001_3000>;
impl core::fmt::Debug for Lpcomp {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Lpcomp").finish()
    }
}
#[doc = "Low-power comparator"]
pub mod lpcomp;
#[doc = "Event generator unit 0"]
pub type Egu0 = crate::Periph<egu0::RegisterBlock, 0x4001_4000>;
impl core::fmt::Debug for Egu0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Egu0").finish()
    }
}
#[doc = "Event generator unit 0"]
pub mod egu0;
#[doc = "Software interrupt 0"]
pub type Swi0 = crate::Periph<swi0::RegisterBlock, 0x4001_4000>;
impl core::fmt::Debug for Swi0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Swi0").finish()
    }
}
#[doc = "Software interrupt 0"]
pub mod swi0;
#[doc = "Event generator unit 1"]
pub type Egu1 = crate::Periph<egu0::RegisterBlock, 0x4001_5000>;
impl core::fmt::Debug for Egu1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Egu1").finish()
    }
}
#[doc = "Event generator unit 1"]
pub use self::egu0 as egu1;
#[doc = "Software interrupt 1"]
pub type Swi1 = crate::Periph<swi0::RegisterBlock, 0x4001_5000>;
impl core::fmt::Debug for Swi1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Swi1").finish()
    }
}
#[doc = "Software interrupt 1"]
pub use self::swi0 as swi1;
#[doc = "Event generator unit 2"]
pub type Egu2 = crate::Periph<egu0::RegisterBlock, 0x4001_6000>;
impl core::fmt::Debug for Egu2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Egu2").finish()
    }
}
#[doc = "Event generator unit 2"]
pub use self::egu0 as egu2;
#[doc = "Software interrupt 2"]
pub type Swi2 = crate::Periph<swi0::RegisterBlock, 0x4001_6000>;
impl core::fmt::Debug for Swi2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Swi2").finish()
    }
}
#[doc = "Software interrupt 2"]
pub use self::swi0 as swi2;
#[doc = "Event generator unit 3"]
pub type Egu3 = crate::Periph<egu0::RegisterBlock, 0x4001_7000>;
impl core::fmt::Debug for Egu3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Egu3").finish()
    }
}
#[doc = "Event generator unit 3"]
pub use self::egu0 as egu3;
#[doc = "Software interrupt 3"]
pub type Swi3 = crate::Periph<swi0::RegisterBlock, 0x4001_7000>;
impl core::fmt::Debug for Swi3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Swi3").finish()
    }
}
#[doc = "Software interrupt 3"]
pub use self::swi0 as swi3;
#[doc = "Event generator unit 4"]
pub type Egu4 = crate::Periph<egu0::RegisterBlock, 0x4001_8000>;
impl core::fmt::Debug for Egu4 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Egu4").finish()
    }
}
#[doc = "Event generator unit 4"]
pub use self::egu0 as egu4;
#[doc = "Software interrupt 4"]
pub type Swi4 = crate::Periph<swi0::RegisterBlock, 0x4001_8000>;
impl core::fmt::Debug for Swi4 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Swi4").finish()
    }
}
#[doc = "Software interrupt 4"]
pub use self::swi0 as swi4;
#[doc = "Event generator unit 5"]
pub type Egu5 = crate::Periph<egu0::RegisterBlock, 0x4001_9000>;
impl core::fmt::Debug for Egu5 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Egu5").finish()
    }
}
#[doc = "Event generator unit 5"]
pub use self::egu0 as egu5;
#[doc = "Software interrupt 5"]
pub type Swi5 = crate::Periph<swi0::RegisterBlock, 0x4001_9000>;
impl core::fmt::Debug for Swi5 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Swi5").finish()
    }
}
#[doc = "Software interrupt 5"]
pub use self::swi0 as swi5;
#[doc = "Timer/Counter 3"]
pub type Timer3 = crate::Periph<timer0::RegisterBlock, 0x4001_a000>;
impl core::fmt::Debug for Timer3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timer3").finish()
    }
}
#[doc = "Timer/Counter 3"]
pub use self::timer0 as timer3;
#[doc = "Timer/Counter 4"]
pub type Timer4 = crate::Periph<timer0::RegisterBlock, 0x4001_b000>;
impl core::fmt::Debug for Timer4 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timer4").finish()
    }
}
#[doc = "Timer/Counter 4"]
pub use self::timer0 as timer4;
#[doc = "Pulse width modulation unit 0"]
pub type Pwm0 = crate::Periph<pwm0::RegisterBlock, 0x4001_c000>;
impl core::fmt::Debug for Pwm0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pwm0").finish()
    }
}
#[doc = "Pulse width modulation unit 0"]
pub mod pwm0;
#[doc = "Pulse Density Modulation (Digital Microphone) Interface"]
pub type Pdm = crate::Periph<pdm::RegisterBlock, 0x4001_d000>;
impl core::fmt::Debug for Pdm {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pdm").finish()
    }
}
#[doc = "Pulse Density Modulation (Digital Microphone) Interface"]
pub mod pdm;
#[doc = "Access control lists"]
pub type Acl = crate::Periph<acl::RegisterBlock, 0x4001_e000>;
impl core::fmt::Debug for Acl {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Acl").finish()
    }
}
#[doc = "Access control lists"]
pub mod acl;
#[doc = "Non Volatile Memory Controller"]
pub type Nvmc = crate::Periph<nvmc::RegisterBlock, 0x4001_e000>;
impl core::fmt::Debug for Nvmc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Nvmc").finish()
    }
}
#[doc = "Non Volatile Memory Controller"]
pub mod nvmc;
#[doc = "Programmable Peripheral Interconnect"]
pub type Ppi = crate::Periph<ppi::RegisterBlock, 0x4001_f000>;
impl core::fmt::Debug for Ppi {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Ppi").finish()
    }
}
#[doc = "Programmable Peripheral Interconnect"]
pub mod ppi;
#[doc = "Memory Watch Unit"]
pub type Mwu = crate::Periph<mwu::RegisterBlock, 0x4002_0000>;
impl core::fmt::Debug for Mwu {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Mwu").finish()
    }
}
#[doc = "Memory Watch Unit"]
pub mod mwu;
#[doc = "Pulse width modulation unit 1"]
pub type Pwm1 = crate::Periph<pwm0::RegisterBlock, 0x4002_1000>;
impl core::fmt::Debug for Pwm1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pwm1").finish()
    }
}
#[doc = "Pulse width modulation unit 1"]
pub use self::pwm0 as pwm1;
#[doc = "Pulse width modulation unit 2"]
pub type Pwm2 = crate::Periph<pwm0::RegisterBlock, 0x4002_2000>;
impl core::fmt::Debug for Pwm2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pwm2").finish()
    }
}
#[doc = "Pulse width modulation unit 2"]
pub use self::pwm0 as pwm2;
#[doc = "Serial Peripheral Interface 2"]
pub type Spi2 = crate::Periph<spi0::RegisterBlock, 0x4002_3000>;
impl core::fmt::Debug for Spi2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spi2").finish()
    }
}
#[doc = "Serial Peripheral Interface 2"]
pub use self::spi0 as spi2;
#[doc = "Serial Peripheral Interface Master with EasyDMA 2"]
pub type Spim2 = crate::Periph<spim0::RegisterBlock, 0x4002_3000>;
impl core::fmt::Debug for Spim2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spim2").finish()
    }
}
#[doc = "Serial Peripheral Interface Master with EasyDMA 2"]
pub use self::spim0 as spim2;
#[doc = "SPI Slave 2"]
pub type Spis2 = crate::Periph<spis0::RegisterBlock, 0x4002_3000>;
impl core::fmt::Debug for Spis2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spis2").finish()
    }
}
#[doc = "SPI Slave 2"]
pub use self::spis0 as spis2;
#[doc = "Real time counter 2"]
pub type Rtc2 = crate::Periph<rtc0::RegisterBlock, 0x4002_4000>;
impl core::fmt::Debug for Rtc2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Rtc2").finish()
    }
}
#[doc = "Real time counter 2"]
pub use self::rtc0 as rtc2;
#[doc = "Inter-IC Sound"]
pub type I2s = crate::Periph<i2s::RegisterBlock, 0x4002_5000>;
impl core::fmt::Debug for I2s {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2s").finish()
    }
}
#[doc = "Inter-IC Sound"]
pub mod i2s;
#[doc = "Universal serial bus device"]
pub type Usbd = crate::Periph<usbd::RegisterBlock, 0x4002_7000>;
impl core::fmt::Debug for Usbd {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Usbd").finish()
    }
}
#[doc = "Universal serial bus device"]
pub mod usbd;
#[doc = "UART with EasyDMA 1"]
pub type Uarte1 = crate::Periph<uarte0::RegisterBlock, 0x4002_8000>;
impl core::fmt::Debug for Uarte1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uarte1").finish()
    }
}
#[doc = "UART with EasyDMA 1"]
pub use self::uarte0 as uarte1;
#[doc = "Pulse width modulation unit 3"]
pub type Pwm3 = crate::Periph<pwm0::RegisterBlock, 0x4002_d000>;
impl core::fmt::Debug for Pwm3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pwm3").finish()
    }
}
#[doc = "Pulse width modulation unit 3"]
pub use self::pwm0 as pwm3;
#[doc = "Serial Peripheral Interface Master with EasyDMA 3"]
pub type Spim3 = crate::Periph<spim0::RegisterBlock, 0x4002_f000>;
impl core::fmt::Debug for Spim3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spim3").finish()
    }
}
#[doc = "Serial Peripheral Interface Master with EasyDMA 3"]
pub use self::spim0 as spim3;
#[no_mangle]
static mut DEVICE_PERIPHERALS: bool = false;
#[doc = r" All the peripherals."]
#[allow(non_snake_case)]
pub struct Peripherals {
    #[doc = "FICR"]
    pub ficr: Ficr,
    #[doc = "UICR"]
    pub uicr: Uicr,
    #[doc = "APPROTECT"]
    pub approtect: Approtect,
    #[doc = "CLOCK"]
    pub clock: Clock,
    #[doc = "POWER"]
    pub power: Power,
    #[doc = "P0"]
    pub p0: P0,
    #[doc = "P1"]
    pub p1: P1,
    #[doc = "RADIO"]
    pub radio: Radio,
    #[doc = "UART0"]
    pub uart0: Uart0,
    #[doc = "UARTE0"]
    pub uarte0: Uarte0,
    #[doc = "SPI0"]
    pub spi0: Spi0,
    #[doc = "SPIM0"]
    pub spim0: Spim0,
    #[doc = "SPIS0"]
    pub spis0: Spis0,
    #[doc = "TWI0"]
    pub twi0: Twi0,
    #[doc = "TWIM0"]
    pub twim0: Twim0,
    #[doc = "TWIS0"]
    pub twis0: Twis0,
    #[doc = "SPI1"]
    pub spi1: Spi1,
    #[doc = "SPIM1"]
    pub spim1: Spim1,
    #[doc = "SPIS1"]
    pub spis1: Spis1,
    #[doc = "TWI1"]
    pub twi1: Twi1,
    #[doc = "TWIM1"]
    pub twim1: Twim1,
    #[doc = "TWIS1"]
    pub twis1: Twis1,
    #[doc = "NFCT"]
    pub nfct: Nfct,
    #[doc = "GPIOTE"]
    pub gpiote: Gpiote,
    #[doc = "SAADC"]
    pub saadc: Saadc,
    #[doc = "TIMER0"]
    pub timer0: Timer0,
    #[doc = "TIMER1"]
    pub timer1: Timer1,
    #[doc = "TIMER2"]
    pub timer2: Timer2,
    #[doc = "RTC0"]
    pub rtc0: Rtc0,
    #[doc = "TEMP"]
    pub temp: Temp,
    #[doc = "RNG"]
    pub rng: Rng,
    #[doc = "ECB"]
    pub ecb: Ecb,
    #[doc = "AAR"]
    pub aar: Aar,
    #[doc = "CCM"]
    pub ccm: Ccm,
    #[doc = "WDT"]
    pub wdt: Wdt,
    #[doc = "RTC1"]
    pub rtc1: Rtc1,
    #[doc = "QDEC"]
    pub qdec: Qdec,
    #[doc = "COMP"]
    pub comp: Comp,
    #[doc = "LPCOMP"]
    pub lpcomp: Lpcomp,
    #[doc = "EGU0"]
    pub egu0: Egu0,
    #[doc = "SWI0"]
    pub swi0: Swi0,
    #[doc = "EGU1"]
    pub egu1: Egu1,
    #[doc = "SWI1"]
    pub swi1: Swi1,
    #[doc = "EGU2"]
    pub egu2: Egu2,
    #[doc = "SWI2"]
    pub swi2: Swi2,
    #[doc = "EGU3"]
    pub egu3: Egu3,
    #[doc = "SWI3"]
    pub swi3: Swi3,
    #[doc = "EGU4"]
    pub egu4: Egu4,
    #[doc = "SWI4"]
    pub swi4: Swi4,
    #[doc = "EGU5"]
    pub egu5: Egu5,
    #[doc = "SWI5"]
    pub swi5: Swi5,
    #[doc = "TIMER3"]
    pub timer3: Timer3,
    #[doc = "TIMER4"]
    pub timer4: Timer4,
    #[doc = "PWM0"]
    pub pwm0: Pwm0,
    #[doc = "PDM"]
    pub pdm: Pdm,
    #[doc = "ACL"]
    pub acl: Acl,
    #[doc = "NVMC"]
    pub nvmc: Nvmc,
    #[doc = "PPI"]
    pub ppi: Ppi,
    #[doc = "MWU"]
    pub mwu: Mwu,
    #[doc = "PWM1"]
    pub pwm1: Pwm1,
    #[doc = "PWM2"]
    pub pwm2: Pwm2,
    #[doc = "SPI2"]
    pub spi2: Spi2,
    #[doc = "SPIM2"]
    pub spim2: Spim2,
    #[doc = "SPIS2"]
    pub spis2: Spis2,
    #[doc = "RTC2"]
    pub rtc2: Rtc2,
    #[doc = "I2S"]
    pub i2s: I2s,
    #[doc = "USBD"]
    pub usbd: Usbd,
    #[doc = "UARTE1"]
    pub uarte1: Uarte1,
    #[doc = "PWM3"]
    pub pwm3: Pwm3,
    #[doc = "SPIM3"]
    pub spim3: Spim3,
}
impl Peripherals {
    #[doc = r" Returns all the peripherals *once*."]
    #[cfg(feature = "critical-section")]
    #[inline]
    pub fn take() -> Option<Self> {
        critical_section::with(|_| {
            if unsafe { DEVICE_PERIPHERALS } {
                return None;
            }
            Some(unsafe { Peripherals::steal() })
        })
    }
    #[doc = r" Unchecked version of `Peripherals::take`."]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Each of the returned peripherals must be used at most once."]
    #[inline]
    pub unsafe fn steal() -> Self {
        DEVICE_PERIPHERALS = true;
        Peripherals {
            ficr: Ficr::steal(),
            uicr: Uicr::steal(),
            approtect: Approtect::steal(),
            clock: Clock::steal(),
            power: Power::steal(),
            p0: P0::steal(),
            p1: P1::steal(),
            radio: Radio::steal(),
            uart0: Uart0::steal(),
            uarte0: Uarte0::steal(),
            spi0: Spi0::steal(),
            spim0: Spim0::steal(),
            spis0: Spis0::steal(),
            twi0: Twi0::steal(),
            twim0: Twim0::steal(),
            twis0: Twis0::steal(),
            spi1: Spi1::steal(),
            spim1: Spim1::steal(),
            spis1: Spis1::steal(),
            twi1: Twi1::steal(),
            twim1: Twim1::steal(),
            twis1: Twis1::steal(),
            nfct: Nfct::steal(),
            gpiote: Gpiote::steal(),
            saadc: Saadc::steal(),
            timer0: Timer0::steal(),
            timer1: Timer1::steal(),
            timer2: Timer2::steal(),
            rtc0: Rtc0::steal(),
            temp: Temp::steal(),
            rng: Rng::steal(),
            ecb: Ecb::steal(),
            aar: Aar::steal(),
            ccm: Ccm::steal(),
            wdt: Wdt::steal(),
            rtc1: Rtc1::steal(),
            qdec: Qdec::steal(),
            comp: Comp::steal(),
            lpcomp: Lpcomp::steal(),
            egu0: Egu0::steal(),
            swi0: Swi0::steal(),
            egu1: Egu1::steal(),
            swi1: Swi1::steal(),
            egu2: Egu2::steal(),
            swi2: Swi2::steal(),
            egu3: Egu3::steal(),
            swi3: Swi3::steal(),
            egu4: Egu4::steal(),
            swi4: Swi4::steal(),
            egu5: Egu5::steal(),
            swi5: Swi5::steal(),
            timer3: Timer3::steal(),
            timer4: Timer4::steal(),
            pwm0: Pwm0::steal(),
            pdm: Pdm::steal(),
            acl: Acl::steal(),
            nvmc: Nvmc::steal(),
            ppi: Ppi::steal(),
            mwu: Mwu::steal(),
            pwm1: Pwm1::steal(),
            pwm2: Pwm2::steal(),
            spi2: Spi2::steal(),
            spim2: Spim2::steal(),
            spis2: Spis2::steal(),
            rtc2: Rtc2::steal(),
            i2s: I2s::steal(),
            usbd: Usbd::steal(),
            uarte1: Uarte1::steal(),
            pwm3: Pwm3::steal(),
            spim3: Spim3::steal(),
        }
    }
}
