#![doc = "Peripheral access API for NRF5340_NETWORK microcontrollers (generated using svd2rust v0.37.0 ( ))\n\nYou can find an overview of the generated API [here].\n\nAPI features to be included in the [next] svd2rust release can be generated by cloning the svd2rust [repository], checking out the above commit, and running `cargo doc --open`.\n\n[here]: https://docs.rs/svd2rust/0.37.0/svd2rust/#peripheral-api\n[next]: https://github.com/rust-embedded/svd2rust/blob/master/CHANGELOG.md#unreleased\n[repository]: https://github.com/rust-embedded/svd2rust"]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![no_std]
#![cfg_attr(docsrs, feature(doc_auto_cfg))]
#[doc = r"Number available in the NVIC for configuring priority"]
pub const NVIC_PRIO_BITS: u8 = 3;
#[allow(unused_imports)]
use generic::*;
#[doc = r"Common register and bit access and modify traits"]
pub mod generic;
#[cfg(feature = "rt")]
extern "C" {
    fn CLOCK_POWER();
    fn RADIO();
    fn RNG();
    fn GPIOTE();
    fn WDT();
    fn TIMER0();
    fn ECB();
    fn AAR_CCM();
    fn TEMP();
    fn RTC0();
    fn IPC();
    fn SERIAL0();
    fn EGU0();
    fn RTC1();
    fn TIMER1();
    fn TIMER2();
    fn SWI0();
    fn SWI1();
    fn SWI2();
    fn SWI3();
}
#[doc(hidden)]
#[repr(C)]
pub union Vector {
    _handler: unsafe extern "C" fn(),
    _reserved: u32,
}
#[cfg(feature = "rt")]
#[doc(hidden)]
#[link_section = ".vector_table.interrupts"]
#[no_mangle]
pub static __INTERRUPTS: [Vector; 30] = [
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector {
        _handler: CLOCK_POWER,
    },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: RADIO },
    Vector { _handler: RNG },
    Vector { _handler: GPIOTE },
    Vector { _handler: WDT },
    Vector { _handler: TIMER0 },
    Vector { _handler: ECB },
    Vector { _handler: AAR_CCM },
    Vector { _reserved: 0 },
    Vector { _handler: TEMP },
    Vector { _handler: RTC0 },
    Vector { _handler: IPC },
    Vector { _handler: SERIAL0 },
    Vector { _handler: EGU0 },
    Vector { _reserved: 0 },
    Vector { _handler: RTC1 },
    Vector { _reserved: 0 },
    Vector { _handler: TIMER1 },
    Vector { _handler: TIMER2 },
    Vector { _handler: SWI0 },
    Vector { _handler: SWI1 },
    Vector { _handler: SWI2 },
    Vector { _handler: SWI3 },
];
#[doc = r"Enumeration of all the interrupts."]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
#[repr(u16)]
pub enum Interrupt {
    #[doc = "5 - CLOCK_POWER"]
    CLOCK_POWER = 5,
    #[doc = "8 - RADIO"]
    RADIO = 8,
    #[doc = "9 - RNG"]
    RNG = 9,
    #[doc = "10 - GPIOTE"]
    GPIOTE = 10,
    #[doc = "11 - WDT"]
    WDT = 11,
    #[doc = "12 - TIMER0"]
    TIMER0 = 12,
    #[doc = "13 - ECB"]
    ECB = 13,
    #[doc = "14 - AAR_CCM"]
    AAR_CCM = 14,
    #[doc = "16 - TEMP"]
    TEMP = 16,
    #[doc = "17 - RTC0"]
    RTC0 = 17,
    #[doc = "18 - IPC"]
    IPC = 18,
    #[doc = "19 - SERIAL0"]
    SERIAL0 = 19,
    #[doc = "20 - EGU0"]
    EGU0 = 20,
    #[doc = "22 - RTC1"]
    RTC1 = 22,
    #[doc = "24 - TIMER1"]
    TIMER1 = 24,
    #[doc = "25 - TIMER2"]
    TIMER2 = 25,
    #[doc = "26 - SWI0"]
    SWI0 = 26,
    #[doc = "27 - SWI1"]
    SWI1 = 27,
    #[doc = "28 - SWI2"]
    SWI2 = 28,
    #[doc = "29 - SWI3"]
    SWI3 = 29,
}
unsafe impl cortex_m::interrupt::InterruptNumber for Interrupt {
    #[inline(always)]
    fn number(self) -> u16 {
        self as u16
    }
}
#[doc = "Factory Information Configuration Registers"]
pub type FicrNs = crate::Periph<ficr_ns::RegisterBlock, 0x01ff_0000>;
impl core::fmt::Debug for FicrNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("FicrNs").finish()
    }
}
#[doc = "Factory Information Configuration Registers"]
pub mod ficr_ns;
#[doc = "User Information Configuration Registers"]
pub type UicrNs = crate::Periph<uicr_ns::RegisterBlock, 0x01ff_8000>;
impl core::fmt::Debug for UicrNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("UicrNs").finish()
    }
}
#[doc = "User Information Configuration Registers"]
pub mod uicr_ns;
#[doc = "Cross-Trigger Interface control. NOTE: this is not a separate peripheral, but describes CM33 functionality."]
pub type CtiNs = crate::Periph<cti_ns::RegisterBlock, 0xe004_2000>;
impl core::fmt::Debug for CtiNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("CtiNs").finish()
    }
}
#[doc = "Cross-Trigger Interface control. NOTE: this is not a separate peripheral, but describes CM33 functionality."]
pub mod cti_ns;
#[doc = "Domain configuration management"]
pub type DcnfNs = crate::Periph<dcnf_ns::RegisterBlock, 0x4100_0000>;
impl core::fmt::Debug for DcnfNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("DcnfNs").finish()
    }
}
#[doc = "Domain configuration management"]
pub mod dcnf_ns;
#[doc = "Voltage request control"]
pub type VreqctrlNs = crate::Periph<vreqctrl_ns::RegisterBlock, 0x4100_4000>;
impl core::fmt::Debug for VreqctrlNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("VreqctrlNs").finish()
    }
}
#[doc = "Voltage request control"]
pub mod vreqctrl_ns;
#[doc = "Clock management"]
pub type ClockNs = crate::Periph<clock_ns::RegisterBlock, 0x4100_5000>;
impl core::fmt::Debug for ClockNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("ClockNs").finish()
    }
}
#[doc = "Clock management"]
pub mod clock_ns;
#[doc = "Power control"]
pub type PowerNs = crate::Periph<power_ns::RegisterBlock, 0x4100_5000>;
impl core::fmt::Debug for PowerNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("PowerNs").finish()
    }
}
#[doc = "Power control"]
pub mod power_ns;
#[doc = "Reset control"]
pub type ResetNs = crate::Periph<reset_ns::RegisterBlock, 0x4100_5000>;
impl core::fmt::Debug for ResetNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("ResetNs").finish()
    }
}
#[doc = "Reset control"]
pub mod reset_ns;
#[doc = "Control access port"]
pub type CtrlapNs = crate::Periph<ctrlap_ns::RegisterBlock, 0x4100_6000>;
impl core::fmt::Debug for CtrlapNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("CtrlapNs").finish()
    }
}
#[doc = "Control access port"]
pub mod ctrlap_ns;
#[doc = "2.4 GHz radio"]
pub type RadioNs = crate::Periph<radio_ns::RegisterBlock, 0x4100_8000>;
impl core::fmt::Debug for RadioNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("RadioNs").finish()
    }
}
#[doc = "2.4 GHz radio"]
pub mod radio_ns;
#[doc = "Random Number Generator"]
pub type RngNs = crate::Periph<rng_ns::RegisterBlock, 0x4100_9000>;
impl core::fmt::Debug for RngNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("RngNs").finish()
    }
}
#[doc = "Random Number Generator"]
pub mod rng_ns;
#[doc = "GPIO Tasks and Events"]
pub type GpioteNs = crate::Periph<gpiote_ns::RegisterBlock, 0x4100_a000>;
impl core::fmt::Debug for GpioteNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("GpioteNs").finish()
    }
}
#[doc = "GPIO Tasks and Events"]
pub mod gpiote_ns;
#[doc = "Watchdog Timer"]
pub type WdtNs = crate::Periph<wdt_ns::RegisterBlock, 0x4100_b000>;
impl core::fmt::Debug for WdtNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("WdtNs").finish()
    }
}
#[doc = "Watchdog Timer"]
pub mod wdt_ns;
#[doc = "Timer/Counter 0"]
pub type Timer0Ns = crate::Periph<timer0_ns::RegisterBlock, 0x4100_c000>;
impl core::fmt::Debug for Timer0Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timer0Ns").finish()
    }
}
#[doc = "Timer/Counter 0"]
pub mod timer0_ns;
#[doc = "AES ECB Mode Encryption"]
pub type EcbNs = crate::Periph<ecb_ns::RegisterBlock, 0x4100_d000>;
impl core::fmt::Debug for EcbNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("EcbNs").finish()
    }
}
#[doc = "AES ECB Mode Encryption"]
pub mod ecb_ns;
#[doc = "Accelerated Address Resolver"]
pub type AarNs = crate::Periph<aar_ns::RegisterBlock, 0x4100_e000>;
impl core::fmt::Debug for AarNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("AarNs").finish()
    }
}
#[doc = "Accelerated Address Resolver"]
pub mod aar_ns;
#[doc = "AES CCM mode encryption"]
pub type CcmNs = crate::Periph<ccm_ns::RegisterBlock, 0x4100_e000>;
impl core::fmt::Debug for CcmNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("CcmNs").finish()
    }
}
#[doc = "AES CCM mode encryption"]
pub mod ccm_ns;
#[doc = "Distributed programmable peripheral interconnect controller"]
pub type DppicNs = crate::Periph<dppic_ns::RegisterBlock, 0x4100_f000>;
impl core::fmt::Debug for DppicNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("DppicNs").finish()
    }
}
#[doc = "Distributed programmable peripheral interconnect controller"]
pub mod dppic_ns;
#[doc = "Temperature Sensor"]
pub type TempNs = crate::Periph<temp_ns::RegisterBlock, 0x4101_0000>;
impl core::fmt::Debug for TempNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("TempNs").finish()
    }
}
#[doc = "Temperature Sensor"]
pub mod temp_ns;
#[doc = "Real-time counter 0"]
pub type Rtc0Ns = crate::Periph<rtc0_ns::RegisterBlock, 0x4101_1000>;
impl core::fmt::Debug for Rtc0Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Rtc0Ns").finish()
    }
}
#[doc = "Real-time counter 0"]
pub mod rtc0_ns;
#[doc = "Interprocessor communication"]
pub type IpcNs = crate::Periph<ipc_ns::RegisterBlock, 0x4101_2000>;
impl core::fmt::Debug for IpcNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("IpcNs").finish()
    }
}
#[doc = "Interprocessor communication"]
pub mod ipc_ns;
#[doc = "Serial Peripheral Interface Master with EasyDMA"]
pub type Spim0Ns = crate::Periph<spim0_ns::RegisterBlock, 0x4101_3000>;
impl core::fmt::Debug for Spim0Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spim0Ns").finish()
    }
}
#[doc = "Serial Peripheral Interface Master with EasyDMA"]
pub mod spim0_ns;
#[doc = "SPI Slave"]
pub type Spis0Ns = crate::Periph<spis0_ns::RegisterBlock, 0x4101_3000>;
impl core::fmt::Debug for Spis0Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spis0Ns").finish()
    }
}
#[doc = "SPI Slave"]
pub mod spis0_ns;
#[doc = "I2C compatible Two-Wire Master Interface with EasyDMA"]
pub type Twim0Ns = crate::Periph<twim0_ns::RegisterBlock, 0x4101_3000>;
impl core::fmt::Debug for Twim0Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Twim0Ns").finish()
    }
}
#[doc = "I2C compatible Two-Wire Master Interface with EasyDMA"]
pub mod twim0_ns;
#[doc = "I2C compatible Two-Wire Slave Interface with EasyDMA"]
pub type Twis0Ns = crate::Periph<twis0_ns::RegisterBlock, 0x4101_3000>;
impl core::fmt::Debug for Twis0Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Twis0Ns").finish()
    }
}
#[doc = "I2C compatible Two-Wire Slave Interface with EasyDMA"]
pub mod twis0_ns;
#[doc = "UART with EasyDMA"]
pub type Uarte0Ns = crate::Periph<uarte0_ns::RegisterBlock, 0x4101_3000>;
impl core::fmt::Debug for Uarte0Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uarte0Ns").finish()
    }
}
#[doc = "UART with EasyDMA"]
pub mod uarte0_ns;
#[doc = "Event generator unit"]
pub type Egu0Ns = crate::Periph<egu0_ns::RegisterBlock, 0x4101_4000>;
impl core::fmt::Debug for Egu0Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Egu0Ns").finish()
    }
}
#[doc = "Event generator unit"]
pub mod egu0_ns;
#[doc = "Real-time counter 1"]
pub type Rtc1Ns = crate::Periph<rtc0_ns::RegisterBlock, 0x4101_6000>;
impl core::fmt::Debug for Rtc1Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Rtc1Ns").finish()
    }
}
#[doc = "Real-time counter 1"]
pub use self::rtc0_ns as rtc1_ns;
#[doc = "Timer/Counter 1"]
pub type Timer1Ns = crate::Periph<timer0_ns::RegisterBlock, 0x4101_8000>;
impl core::fmt::Debug for Timer1Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timer1Ns").finish()
    }
}
#[doc = "Timer/Counter 1"]
pub use self::timer0_ns as timer1_ns;
#[doc = "Timer/Counter 2"]
pub type Timer2Ns = crate::Periph<timer0_ns::RegisterBlock, 0x4101_9000>;
impl core::fmt::Debug for Timer2Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timer2Ns").finish()
    }
}
#[doc = "Timer/Counter 2"]
pub use self::timer0_ns as timer2_ns;
#[doc = "Software interrupt 0"]
pub type Swi0Ns = crate::Periph<swi0_ns::RegisterBlock, 0x4101_a000>;
impl core::fmt::Debug for Swi0Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Swi0Ns").finish()
    }
}
#[doc = "Software interrupt 0"]
pub mod swi0_ns;
#[doc = "Software interrupt 1"]
pub type Swi1Ns = crate::Periph<swi0_ns::RegisterBlock, 0x4101_b000>;
impl core::fmt::Debug for Swi1Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Swi1Ns").finish()
    }
}
#[doc = "Software interrupt 1"]
pub use self::swi0_ns as swi1_ns;
#[doc = "Software interrupt 2"]
pub type Swi2Ns = crate::Periph<swi0_ns::RegisterBlock, 0x4101_c000>;
impl core::fmt::Debug for Swi2Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Swi2Ns").finish()
    }
}
#[doc = "Software interrupt 2"]
pub use self::swi0_ns as swi2_ns;
#[doc = "Software interrupt 3"]
pub type Swi3Ns = crate::Periph<swi0_ns::RegisterBlock, 0x4101_d000>;
impl core::fmt::Debug for Swi3Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Swi3Ns").finish()
    }
}
#[doc = "Software interrupt 3"]
pub use self::swi0_ns as swi3_ns;
#[doc = "MUTEX 0"]
pub type AppmutexNs = crate::Periph<appmutex_ns::RegisterBlock, 0x4003_0000>;
impl core::fmt::Debug for AppmutexNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("AppmutexNs").finish()
    }
}
#[doc = "MUTEX 0"]
pub mod appmutex_ns;
#[doc = "MUTEX 1"]
pub type AppmutexS = crate::Periph<appmutex_ns::RegisterBlock, 0x5003_0000>;
impl core::fmt::Debug for AppmutexS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("AppmutexS").finish()
    }
}
#[doc = "MUTEX 1"]
pub use self::appmutex_ns as appmutex_s;
#[doc = "Access control lists"]
pub type AclNs = crate::Periph<acl_ns::RegisterBlock, 0x4108_0000>;
impl core::fmt::Debug for AclNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("AclNs").finish()
    }
}
#[doc = "Access control lists"]
pub mod acl_ns;
#[doc = "Non-volatile memory controller"]
pub type NvmcNs = crate::Periph<nvmc_ns::RegisterBlock, 0x4108_0000>;
impl core::fmt::Debug for NvmcNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("NvmcNs").finish()
    }
}
#[doc = "Non-volatile memory controller"]
pub mod nvmc_ns;
#[doc = "Volatile Memory controller"]
pub type VmcNs = crate::Periph<vmc_ns::RegisterBlock, 0x4108_1000>;
impl core::fmt::Debug for VmcNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("VmcNs").finish()
    }
}
#[doc = "Volatile Memory controller"]
pub mod vmc_ns;
#[doc = "GPIO Port 0"]
pub type P0Ns = crate::Periph<p0_ns::RegisterBlock, 0x418c_0500>;
impl core::fmt::Debug for P0Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("P0Ns").finish()
    }
}
#[doc = "GPIO Port 0"]
pub mod p0_ns;
#[doc = "GPIO Port 1"]
pub type P1Ns = crate::Periph<p0_ns::RegisterBlock, 0x418c_0800>;
impl core::fmt::Debug for P1Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("P1Ns").finish()
    }
}
#[doc = "GPIO Port 1"]
pub use self::p0_ns as p1_ns;
#[no_mangle]
static mut DEVICE_PERIPHERALS: bool = false;
#[doc = r" All the peripherals."]
#[allow(non_snake_case)]
pub struct Peripherals {
    #[doc = "FICR_NS"]
    pub ficr_ns: FicrNs,
    #[doc = "UICR_NS"]
    pub uicr_ns: UicrNs,
    #[doc = "CTI_NS"]
    pub cti_ns: CtiNs,
    #[doc = "DCNF_NS"]
    pub dcnf_ns: DcnfNs,
    #[doc = "VREQCTRL_NS"]
    pub vreqctrl_ns: VreqctrlNs,
    #[doc = "CLOCK_NS"]
    pub clock_ns: ClockNs,
    #[doc = "POWER_NS"]
    pub power_ns: PowerNs,
    #[doc = "RESET_NS"]
    pub reset_ns: ResetNs,
    #[doc = "CTRLAP_NS"]
    pub ctrlap_ns: CtrlapNs,
    #[doc = "RADIO_NS"]
    pub radio_ns: RadioNs,
    #[doc = "RNG_NS"]
    pub rng_ns: RngNs,
    #[doc = "GPIOTE_NS"]
    pub gpiote_ns: GpioteNs,
    #[doc = "WDT_NS"]
    pub wdt_ns: WdtNs,
    #[doc = "TIMER0_NS"]
    pub timer0_ns: Timer0Ns,
    #[doc = "ECB_NS"]
    pub ecb_ns: EcbNs,
    #[doc = "AAR_NS"]
    pub aar_ns: AarNs,
    #[doc = "CCM_NS"]
    pub ccm_ns: CcmNs,
    #[doc = "DPPIC_NS"]
    pub dppic_ns: DppicNs,
    #[doc = "TEMP_NS"]
    pub temp_ns: TempNs,
    #[doc = "RTC0_NS"]
    pub rtc0_ns: Rtc0Ns,
    #[doc = "IPC_NS"]
    pub ipc_ns: IpcNs,
    #[doc = "SPIM0_NS"]
    pub spim0_ns: Spim0Ns,
    #[doc = "SPIS0_NS"]
    pub spis0_ns: Spis0Ns,
    #[doc = "TWIM0_NS"]
    pub twim0_ns: Twim0Ns,
    #[doc = "TWIS0_NS"]
    pub twis0_ns: Twis0Ns,
    #[doc = "UARTE0_NS"]
    pub uarte0_ns: Uarte0Ns,
    #[doc = "EGU0_NS"]
    pub egu0_ns: Egu0Ns,
    #[doc = "RTC1_NS"]
    pub rtc1_ns: Rtc1Ns,
    #[doc = "TIMER1_NS"]
    pub timer1_ns: Timer1Ns,
    #[doc = "TIMER2_NS"]
    pub timer2_ns: Timer2Ns,
    #[doc = "SWI0_NS"]
    pub swi0_ns: Swi0Ns,
    #[doc = "SWI1_NS"]
    pub swi1_ns: Swi1Ns,
    #[doc = "SWI2_NS"]
    pub swi2_ns: Swi2Ns,
    #[doc = "SWI3_NS"]
    pub swi3_ns: Swi3Ns,
    #[doc = "APPMUTEX_NS"]
    pub appmutex_ns: AppmutexNs,
    #[doc = "APPMUTEX_S"]
    pub appmutex_s: AppmutexS,
    #[doc = "ACL_NS"]
    pub acl_ns: AclNs,
    #[doc = "NVMC_NS"]
    pub nvmc_ns: NvmcNs,
    #[doc = "VMC_NS"]
    pub vmc_ns: VmcNs,
    #[doc = "P0_NS"]
    pub p0_ns: P0Ns,
    #[doc = "P1_NS"]
    pub p1_ns: P1Ns,
}
impl Peripherals {
    #[doc = r" Returns all the peripherals *once*."]
    #[cfg(feature = "critical-section")]
    #[inline]
    pub fn take() -> Option<Self> {
        critical_section::with(|_| {
            if unsafe { DEVICE_PERIPHERALS } {
                return None;
            }
            Some(unsafe { Peripherals::steal() })
        })
    }
    #[doc = r" Unchecked version of `Peripherals::take`."]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Each of the returned peripherals must be used at most once."]
    #[inline]
    pub unsafe fn steal() -> Self {
        DEVICE_PERIPHERALS = true;
        Peripherals {
            ficr_ns: FicrNs::steal(),
            uicr_ns: UicrNs::steal(),
            cti_ns: CtiNs::steal(),
            dcnf_ns: DcnfNs::steal(),
            vreqctrl_ns: VreqctrlNs::steal(),
            clock_ns: ClockNs::steal(),
            power_ns: PowerNs::steal(),
            reset_ns: ResetNs::steal(),
            ctrlap_ns: CtrlapNs::steal(),
            radio_ns: RadioNs::steal(),
            rng_ns: RngNs::steal(),
            gpiote_ns: GpioteNs::steal(),
            wdt_ns: WdtNs::steal(),
            timer0_ns: Timer0Ns::steal(),
            ecb_ns: EcbNs::steal(),
            aar_ns: AarNs::steal(),
            ccm_ns: CcmNs::steal(),
            dppic_ns: DppicNs::steal(),
            temp_ns: TempNs::steal(),
            rtc0_ns: Rtc0Ns::steal(),
            ipc_ns: IpcNs::steal(),
            spim0_ns: Spim0Ns::steal(),
            spis0_ns: Spis0Ns::steal(),
            twim0_ns: Twim0Ns::steal(),
            twis0_ns: Twis0Ns::steal(),
            uarte0_ns: Uarte0Ns::steal(),
            egu0_ns: Egu0Ns::steal(),
            rtc1_ns: Rtc1Ns::steal(),
            timer1_ns: Timer1Ns::steal(),
            timer2_ns: Timer2Ns::steal(),
            swi0_ns: Swi0Ns::steal(),
            swi1_ns: Swi1Ns::steal(),
            swi2_ns: Swi2Ns::steal(),
            swi3_ns: Swi3Ns::steal(),
            appmutex_ns: AppmutexNs::steal(),
            appmutex_s: AppmutexS::steal(),
            acl_ns: AclNs::steal(),
            nvmc_ns: NvmcNs::steal(),
            vmc_ns: VmcNs::steal(),
            p0_ns: P0Ns::steal(),
            p1_ns: P1Ns::steal(),
        }
    }
}
