#![doc = "Peripheral access API for NRF5340_APPLICATION microcontrollers (generated using svd2rust v0.37.0 ( ))\n\nYou can find an overview of the generated API [here].\n\nAPI features to be included in the [next] svd2rust release can be generated by cloning the svd2rust [repository], checking out the above commit, and running `cargo doc --open`.\n\n[here]: https://docs.rs/svd2rust/0.37.0/svd2rust/#peripheral-api\n[next]: https://github.com/rust-embedded/svd2rust/blob/master/CHANGELOG.md#unreleased\n[repository]: https://github.com/rust-embedded/svd2rust"]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![no_std]
#![cfg_attr(docsrs, feature(doc_auto_cfg))]
#[doc = r"Number available in the NVIC for configuring priority"]
pub const NVIC_PRIO_BITS: u8 = 3;
#[allow(unused_imports)]
use generic::*;
#[doc = r"Common register and bit access and modify traits"]
pub mod generic;
#[cfg(feature = "rt")]
extern "C" {
    fn FPU();
    fn CACHE();
    fn SPU();
    fn CLOCK_POWER();
    fn SERIAL0();
    fn SERIAL1();
    fn SPIM4();
    fn SERIAL2();
    fn SERIAL3();
    fn GPIOTE0();
    fn SAADC();
    fn TIMER0();
    fn TIMER1();
    fn TIMER2();
    fn RTC0();
    fn RTC1();
    fn WDT0();
    fn WDT1();
    fn COMP_LPCOMP();
    fn EGU0();
    fn EGU1();
    fn EGU2();
    fn EGU3();
    fn EGU4();
    fn EGU5();
    fn PWM0();
    fn PWM1();
    fn PWM2();
    fn PWM3();
    fn PDM0();
    fn I2S0();
    fn IPC();
    fn QSPI();
    fn NFCT();
    fn GPIOTE1();
    fn QDEC0();
    fn QDEC1();
    fn USBD();
    fn USBREGULATOR();
    fn KMU();
    fn CRYPTOCELL();
}
#[doc(hidden)]
#[repr(C)]
pub union Vector {
    _handler: unsafe extern "C" fn(),
    _reserved: u32,
}
#[cfg(feature = "rt")]
#[doc(hidden)]
#[link_section = ".vector_table.interrupts"]
#[no_mangle]
pub static __INTERRUPTS: [Vector; 69] = [
    Vector { _handler: FPU },
    Vector { _handler: CACHE },
    Vector { _reserved: 0 },
    Vector { _handler: SPU },
    Vector { _reserved: 0 },
    Vector {
        _handler: CLOCK_POWER,
    },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: SERIAL0 },
    Vector { _handler: SERIAL1 },
    Vector { _handler: SPIM4 },
    Vector { _handler: SERIAL2 },
    Vector { _handler: SERIAL3 },
    Vector { _handler: GPIOTE0 },
    Vector { _handler: SAADC },
    Vector { _handler: TIMER0 },
    Vector { _handler: TIMER1 },
    Vector { _handler: TIMER2 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: RTC0 },
    Vector { _handler: RTC1 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: WDT0 },
    Vector { _handler: WDT1 },
    Vector {
        _handler: COMP_LPCOMP,
    },
    Vector { _handler: EGU0 },
    Vector { _handler: EGU1 },
    Vector { _handler: EGU2 },
    Vector { _handler: EGU3 },
    Vector { _handler: EGU4 },
    Vector { _handler: EGU5 },
    Vector { _handler: PWM0 },
    Vector { _handler: PWM1 },
    Vector { _handler: PWM2 },
    Vector { _handler: PWM3 },
    Vector { _reserved: 0 },
    Vector { _handler: PDM0 },
    Vector { _reserved: 0 },
    Vector { _handler: I2S0 },
    Vector { _reserved: 0 },
    Vector { _handler: IPC },
    Vector { _handler: QSPI },
    Vector { _reserved: 0 },
    Vector { _handler: NFCT },
    Vector { _reserved: 0 },
    Vector { _handler: GPIOTE1 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: QDEC0 },
    Vector { _handler: QDEC1 },
    Vector { _reserved: 0 },
    Vector { _handler: USBD },
    Vector {
        _handler: USBREGULATOR,
    },
    Vector { _reserved: 0 },
    Vector { _handler: KMU },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector {
        _handler: CRYPTOCELL,
    },
];
#[doc = r"Enumeration of all the interrupts."]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
#[repr(u16)]
pub enum Interrupt {
    #[doc = "0 - FPU"]
    FPU = 0,
    #[doc = "1 - CACHE"]
    CACHE = 1,
    #[doc = "3 - SPU"]
    SPU = 3,
    #[doc = "5 - CLOCK_POWER"]
    CLOCK_POWER = 5,
    #[doc = "8 - SERIAL0"]
    SERIAL0 = 8,
    #[doc = "9 - SERIAL1"]
    SERIAL1 = 9,
    #[doc = "10 - SPIM4"]
    SPIM4 = 10,
    #[doc = "11 - SERIAL2"]
    SERIAL2 = 11,
    #[doc = "12 - SERIAL3"]
    SERIAL3 = 12,
    #[doc = "13 - GPIOTE0"]
    GPIOTE0 = 13,
    #[doc = "14 - SAADC"]
    SAADC = 14,
    #[doc = "15 - TIMER0"]
    TIMER0 = 15,
    #[doc = "16 - TIMER1"]
    TIMER1 = 16,
    #[doc = "17 - TIMER2"]
    TIMER2 = 17,
    #[doc = "20 - RTC0"]
    RTC0 = 20,
    #[doc = "21 - RTC1"]
    RTC1 = 21,
    #[doc = "24 - WDT0"]
    WDT0 = 24,
    #[doc = "25 - WDT1"]
    WDT1 = 25,
    #[doc = "26 - COMP_LPCOMP"]
    COMP_LPCOMP = 26,
    #[doc = "27 - EGU0"]
    EGU0 = 27,
    #[doc = "28 - EGU1"]
    EGU1 = 28,
    #[doc = "29 - EGU2"]
    EGU2 = 29,
    #[doc = "30 - EGU3"]
    EGU3 = 30,
    #[doc = "31 - EGU4"]
    EGU4 = 31,
    #[doc = "32 - EGU5"]
    EGU5 = 32,
    #[doc = "33 - PWM0"]
    PWM0 = 33,
    #[doc = "34 - PWM1"]
    PWM1 = 34,
    #[doc = "35 - PWM2"]
    PWM2 = 35,
    #[doc = "36 - PWM3"]
    PWM3 = 36,
    #[doc = "38 - PDM0"]
    PDM0 = 38,
    #[doc = "40 - I2S0"]
    I2S0 = 40,
    #[doc = "42 - IPC"]
    IPC = 42,
    #[doc = "43 - QSPI"]
    QSPI = 43,
    #[doc = "45 - NFCT"]
    NFCT = 45,
    #[doc = "47 - GPIOTE1"]
    GPIOTE1 = 47,
    #[doc = "51 - QDEC0"]
    QDEC0 = 51,
    #[doc = "52 - QDEC1"]
    QDEC1 = 52,
    #[doc = "54 - USBD"]
    USBD = 54,
    #[doc = "55 - USBREGULATOR"]
    USBREGULATOR = 55,
    #[doc = "57 - KMU"]
    KMU = 57,
    #[doc = "68 - CRYPTOCELL"]
    CRYPTOCELL = 68,
}
unsafe impl cortex_m::interrupt::InterruptNumber for Interrupt {
    #[inline(always)]
    fn number(self) -> u16 {
        self as u16
    }
}
#[doc = "CACHEDATA"]
pub type CachedataS = crate::Periph<cachedata_s::RegisterBlock, 0x00f0_0000>;
impl core::fmt::Debug for CachedataS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("CachedataS").finish()
    }
}
#[doc = "CACHEDATA"]
pub mod cachedata_s;
#[doc = "CACHEINFO"]
pub type CacheinfoS = crate::Periph<cacheinfo_s::RegisterBlock, 0x00f0_8000>;
impl core::fmt::Debug for CacheinfoS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("CacheinfoS").finish()
    }
}
#[doc = "CACHEINFO"]
pub mod cacheinfo_s;
#[doc = "Factory Information Configuration Registers"]
pub type FicrS = crate::Periph<ficr_s::RegisterBlock, 0x00ff_0000>;
impl core::fmt::Debug for FicrS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("FicrS").finish()
    }
}
#[doc = "Factory Information Configuration Registers"]
pub mod ficr_s;
#[doc = "User Information Configuration Registers User information configuration registers"]
pub type UicrS = crate::Periph<uicr_s::RegisterBlock, 0x00ff_8000>;
impl core::fmt::Debug for UicrS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("UicrS").finish()
    }
}
#[doc = "User Information Configuration Registers User information configuration registers"]
pub mod uicr_s;
#[doc = "Cross-Trigger Interface control. NOTE: this is not a separate peripheral, but describes CM33 functionality."]
pub type CtiS = crate::Periph<cti_s::RegisterBlock, 0xe004_2000>;
impl core::fmt::Debug for CtiS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("CtiS").finish()
    }
}
#[doc = "Cross-Trigger Interface control. NOTE: this is not a separate peripheral, but describes CM33 functionality."]
pub mod cti_s;
#[doc = "Trace and debug control"]
pub type TadS = crate::Periph<tad_s::RegisterBlock, 0xe008_0000>;
impl core::fmt::Debug for TadS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("TadS").finish()
    }
}
#[doc = "Trace and debug control"]
pub mod tad_s;
#[doc = "Domain configuration management 0"]
pub type DcnfNs = crate::Periph<dcnf_ns::RegisterBlock, 0x4000_0000>;
impl core::fmt::Debug for DcnfNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("DcnfNs").finish()
    }
}
#[doc = "Domain configuration management 0"]
pub mod dcnf_ns;
#[doc = "FPU control peripheral 0"]
pub type FpuNs = crate::Periph<fpu_ns::RegisterBlock, 0x4000_0000>;
impl core::fmt::Debug for FpuNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("FpuNs").finish()
    }
}
#[doc = "FPU control peripheral 0"]
pub mod fpu_ns;
#[doc = "Domain configuration management 1"]
pub type DcnfS = crate::Periph<dcnf_ns::RegisterBlock, 0x5000_0000>;
impl core::fmt::Debug for DcnfS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("DcnfS").finish()
    }
}
#[doc = "Domain configuration management 1"]
pub use self::dcnf_ns as dcnf_s;
#[doc = "FPU control peripheral 1"]
pub type FpuS = crate::Periph<fpu_ns::RegisterBlock, 0x5000_0000>;
impl core::fmt::Debug for FpuS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("FpuS").finish()
    }
}
#[doc = "FPU control peripheral 1"]
pub use self::fpu_ns as fpu_s;
#[doc = "Cache"]
pub type CacheS = crate::Periph<cache_s::RegisterBlock, 0x5000_1000>;
impl core::fmt::Debug for CacheS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("CacheS").finish()
    }
}
#[doc = "Cache"]
pub mod cache_s;
#[doc = "System protection unit"]
pub type SpuS = crate::Periph<spu_s::RegisterBlock, 0x5000_3000>;
impl core::fmt::Debug for SpuS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SpuS").finish()
    }
}
#[doc = "System protection unit"]
pub mod spu_s;
#[doc = "Oscillator control 0"]
pub type OscillatorsNs = crate::Periph<oscillators_ns::RegisterBlock, 0x4000_4000>;
impl core::fmt::Debug for OscillatorsNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("OscillatorsNs").finish()
    }
}
#[doc = "Oscillator control 0"]
pub mod oscillators_ns;
#[doc = "Voltage regulators 0"]
pub type RegulatorsNs = crate::Periph<regulators_ns::RegisterBlock, 0x4000_4000>;
impl core::fmt::Debug for RegulatorsNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("RegulatorsNs").finish()
    }
}
#[doc = "Voltage regulators 0"]
pub mod regulators_ns;
#[doc = "Oscillator control 1"]
pub type OscillatorsS = crate::Periph<oscillators_ns::RegisterBlock, 0x5000_4000>;
impl core::fmt::Debug for OscillatorsS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("OscillatorsS").finish()
    }
}
#[doc = "Oscillator control 1"]
pub use self::oscillators_ns as oscillators_s;
#[doc = "Voltage regulators 1"]
pub type RegulatorsS = crate::Periph<regulators_ns::RegisterBlock, 0x5000_4000>;
impl core::fmt::Debug for RegulatorsS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("RegulatorsS").finish()
    }
}
#[doc = "Voltage regulators 1"]
pub use self::regulators_ns as regulators_s;
#[doc = "Clock management 0"]
pub type ClockNs = crate::Periph<clock_ns::RegisterBlock, 0x4000_5000>;
impl core::fmt::Debug for ClockNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("ClockNs").finish()
    }
}
#[doc = "Clock management 0"]
pub mod clock_ns;
#[doc = "Power control 0"]
pub type PowerNs = crate::Periph<power_ns::RegisterBlock, 0x4000_5000>;
impl core::fmt::Debug for PowerNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("PowerNs").finish()
    }
}
#[doc = "Power control 0"]
pub mod power_ns;
#[doc = "Reset control 0"]
pub type ResetNs = crate::Periph<reset_ns::RegisterBlock, 0x4000_5000>;
impl core::fmt::Debug for ResetNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("ResetNs").finish()
    }
}
#[doc = "Reset control 0"]
pub mod reset_ns;
#[doc = "Clock management 1"]
pub type ClockS = crate::Periph<clock_ns::RegisterBlock, 0x5000_5000>;
impl core::fmt::Debug for ClockS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("ClockS").finish()
    }
}
#[doc = "Clock management 1"]
pub use self::clock_ns as clock_s;
#[doc = "Power control 1"]
pub type PowerS = crate::Periph<power_ns::RegisterBlock, 0x5000_5000>;
impl core::fmt::Debug for PowerS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("PowerS").finish()
    }
}
#[doc = "Power control 1"]
pub use self::power_ns as power_s;
#[doc = "Reset control 1"]
pub type ResetS = crate::Periph<reset_ns::RegisterBlock, 0x5000_5000>;
impl core::fmt::Debug for ResetS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("ResetS").finish()
    }
}
#[doc = "Reset control 1"]
pub use self::reset_ns as reset_s;
#[doc = "Control access port 0"]
pub type CtrlapNs = crate::Periph<ctrlap_ns::RegisterBlock, 0x4000_6000>;
impl core::fmt::Debug for CtrlapNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("CtrlapNs").finish()
    }
}
#[doc = "Control access port 0"]
pub mod ctrlap_ns;
#[doc = "Control access port 1"]
pub type CtrlapS = crate::Periph<ctrlap_ns::RegisterBlock, 0x5000_6000>;
impl core::fmt::Debug for CtrlapS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("CtrlapS").finish()
    }
}
#[doc = "Control access port 1"]
pub use self::ctrlap_ns as ctrlap_s;
#[doc = "Serial Peripheral Interface Master with EasyDMA 0"]
pub type Spim0Ns = crate::Periph<spim0_ns::RegisterBlock, 0x4000_8000>;
impl core::fmt::Debug for Spim0Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spim0Ns").finish()
    }
}
#[doc = "Serial Peripheral Interface Master with EasyDMA 0"]
pub mod spim0_ns;
#[doc = "SPI Slave 0"]
pub type Spis0Ns = crate::Periph<spis0_ns::RegisterBlock, 0x4000_8000>;
impl core::fmt::Debug for Spis0Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spis0Ns").finish()
    }
}
#[doc = "SPI Slave 0"]
pub mod spis0_ns;
#[doc = "I2C compatible Two-Wire Master Interface with EasyDMA 0"]
pub type Twim0Ns = crate::Periph<twim0_ns::RegisterBlock, 0x4000_8000>;
impl core::fmt::Debug for Twim0Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Twim0Ns").finish()
    }
}
#[doc = "I2C compatible Two-Wire Master Interface with EasyDMA 0"]
pub mod twim0_ns;
#[doc = "I2C compatible Two-Wire Slave Interface with EasyDMA 0"]
pub type Twis0Ns = crate::Periph<twis0_ns::RegisterBlock, 0x4000_8000>;
impl core::fmt::Debug for Twis0Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Twis0Ns").finish()
    }
}
#[doc = "I2C compatible Two-Wire Slave Interface with EasyDMA 0"]
pub mod twis0_ns;
#[doc = "UART with EasyDMA 0"]
pub type Uarte0Ns = crate::Periph<uarte0_ns::RegisterBlock, 0x4000_8000>;
impl core::fmt::Debug for Uarte0Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uarte0Ns").finish()
    }
}
#[doc = "UART with EasyDMA 0"]
pub mod uarte0_ns;
#[doc = "Serial Peripheral Interface Master with EasyDMA 1"]
pub type Spim0S = crate::Periph<spim0_ns::RegisterBlock, 0x5000_8000>;
impl core::fmt::Debug for Spim0S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spim0S").finish()
    }
}
#[doc = "Serial Peripheral Interface Master with EasyDMA 1"]
pub use self::spim0_ns as spim0_s;
#[doc = "SPI Slave 1"]
pub type Spis0S = crate::Periph<spis0_ns::RegisterBlock, 0x5000_8000>;
impl core::fmt::Debug for Spis0S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spis0S").finish()
    }
}
#[doc = "SPI Slave 1"]
pub use self::spis0_ns as spis0_s;
#[doc = "I2C compatible Two-Wire Master Interface with EasyDMA 1"]
pub type Twim0S = crate::Periph<twim0_ns::RegisterBlock, 0x5000_8000>;
impl core::fmt::Debug for Twim0S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Twim0S").finish()
    }
}
#[doc = "I2C compatible Two-Wire Master Interface with EasyDMA 1"]
pub use self::twim0_ns as twim0_s;
#[doc = "I2C compatible Two-Wire Slave Interface with EasyDMA 1"]
pub type Twis0S = crate::Periph<twis0_ns::RegisterBlock, 0x5000_8000>;
impl core::fmt::Debug for Twis0S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Twis0S").finish()
    }
}
#[doc = "I2C compatible Two-Wire Slave Interface with EasyDMA 1"]
pub use self::twis0_ns as twis0_s;
#[doc = "UART with EasyDMA 1"]
pub type Uarte0S = crate::Periph<uarte0_ns::RegisterBlock, 0x5000_8000>;
impl core::fmt::Debug for Uarte0S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uarte0S").finish()
    }
}
#[doc = "UART with EasyDMA 1"]
pub use self::uarte0_ns as uarte0_s;
#[doc = "Serial Peripheral Interface Master with EasyDMA 2"]
pub type Spim1Ns = crate::Periph<spim0_ns::RegisterBlock, 0x4000_9000>;
impl core::fmt::Debug for Spim1Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spim1Ns").finish()
    }
}
#[doc = "Serial Peripheral Interface Master with EasyDMA 2"]
pub use self::spim0_ns as spim1_ns;
#[doc = "SPI Slave 2"]
pub type Spis1Ns = crate::Periph<spis0_ns::RegisterBlock, 0x4000_9000>;
impl core::fmt::Debug for Spis1Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spis1Ns").finish()
    }
}
#[doc = "SPI Slave 2"]
pub use self::spis0_ns as spis1_ns;
#[doc = "I2C compatible Two-Wire Master Interface with EasyDMA 2"]
pub type Twim1Ns = crate::Periph<twim0_ns::RegisterBlock, 0x4000_9000>;
impl core::fmt::Debug for Twim1Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Twim1Ns").finish()
    }
}
#[doc = "I2C compatible Two-Wire Master Interface with EasyDMA 2"]
pub use self::twim0_ns as twim1_ns;
#[doc = "I2C compatible Two-Wire Slave Interface with EasyDMA 2"]
pub type Twis1Ns = crate::Periph<twis0_ns::RegisterBlock, 0x4000_9000>;
impl core::fmt::Debug for Twis1Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Twis1Ns").finish()
    }
}
#[doc = "I2C compatible Two-Wire Slave Interface with EasyDMA 2"]
pub use self::twis0_ns as twis1_ns;
#[doc = "UART with EasyDMA 2"]
pub type Uarte1Ns = crate::Periph<uarte0_ns::RegisterBlock, 0x4000_9000>;
impl core::fmt::Debug for Uarte1Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uarte1Ns").finish()
    }
}
#[doc = "UART with EasyDMA 2"]
pub use self::uarte0_ns as uarte1_ns;
#[doc = "Serial Peripheral Interface Master with EasyDMA 3"]
pub type Spim1S = crate::Periph<spim0_ns::RegisterBlock, 0x5000_9000>;
impl core::fmt::Debug for Spim1S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spim1S").finish()
    }
}
#[doc = "Serial Peripheral Interface Master with EasyDMA 3"]
pub use self::spim0_ns as spim1_s;
#[doc = "SPI Slave 3"]
pub type Spis1S = crate::Periph<spis0_ns::RegisterBlock, 0x5000_9000>;
impl core::fmt::Debug for Spis1S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spis1S").finish()
    }
}
#[doc = "SPI Slave 3"]
pub use self::spis0_ns as spis1_s;
#[doc = "I2C compatible Two-Wire Master Interface with EasyDMA 3"]
pub type Twim1S = crate::Periph<twim0_ns::RegisterBlock, 0x5000_9000>;
impl core::fmt::Debug for Twim1S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Twim1S").finish()
    }
}
#[doc = "I2C compatible Two-Wire Master Interface with EasyDMA 3"]
pub use self::twim0_ns as twim1_s;
#[doc = "I2C compatible Two-Wire Slave Interface with EasyDMA 3"]
pub type Twis1S = crate::Periph<twis0_ns::RegisterBlock, 0x5000_9000>;
impl core::fmt::Debug for Twis1S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Twis1S").finish()
    }
}
#[doc = "I2C compatible Two-Wire Slave Interface with EasyDMA 3"]
pub use self::twis0_ns as twis1_s;
#[doc = "UART with EasyDMA 3"]
pub type Uarte1S = crate::Periph<uarte0_ns::RegisterBlock, 0x5000_9000>;
impl core::fmt::Debug for Uarte1S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uarte1S").finish()
    }
}
#[doc = "UART with EasyDMA 3"]
pub use self::uarte0_ns as uarte1_s;
#[doc = "Serial Peripheral Interface Master with EasyDMA 4"]
pub type Spim4Ns = crate::Periph<spim0_ns::RegisterBlock, 0x4000_a000>;
impl core::fmt::Debug for Spim4Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spim4Ns").finish()
    }
}
#[doc = "Serial Peripheral Interface Master with EasyDMA 4"]
pub use self::spim0_ns as spim4_ns;
#[doc = "Serial Peripheral Interface Master with EasyDMA 5"]
pub type Spim4S = crate::Periph<spim0_ns::RegisterBlock, 0x5000_a000>;
impl core::fmt::Debug for Spim4S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spim4S").finish()
    }
}
#[doc = "Serial Peripheral Interface Master with EasyDMA 5"]
pub use self::spim0_ns as spim4_s;
#[doc = "Serial Peripheral Interface Master with EasyDMA 6"]
pub type Spim2Ns = crate::Periph<spim0_ns::RegisterBlock, 0x4000_b000>;
impl core::fmt::Debug for Spim2Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spim2Ns").finish()
    }
}
#[doc = "Serial Peripheral Interface Master with EasyDMA 6"]
pub use self::spim0_ns as spim2_ns;
#[doc = "SPI Slave 4"]
pub type Spis2Ns = crate::Periph<spis0_ns::RegisterBlock, 0x4000_b000>;
impl core::fmt::Debug for Spis2Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spis2Ns").finish()
    }
}
#[doc = "SPI Slave 4"]
pub use self::spis0_ns as spis2_ns;
#[doc = "I2C compatible Two-Wire Master Interface with EasyDMA 4"]
pub type Twim2Ns = crate::Periph<twim0_ns::RegisterBlock, 0x4000_b000>;
impl core::fmt::Debug for Twim2Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Twim2Ns").finish()
    }
}
#[doc = "I2C compatible Two-Wire Master Interface with EasyDMA 4"]
pub use self::twim0_ns as twim2_ns;
#[doc = "I2C compatible Two-Wire Slave Interface with EasyDMA 4"]
pub type Twis2Ns = crate::Periph<twis0_ns::RegisterBlock, 0x4000_b000>;
impl core::fmt::Debug for Twis2Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Twis2Ns").finish()
    }
}
#[doc = "I2C compatible Two-Wire Slave Interface with EasyDMA 4"]
pub use self::twis0_ns as twis2_ns;
#[doc = "UART with EasyDMA 4"]
pub type Uarte2Ns = crate::Periph<uarte0_ns::RegisterBlock, 0x4000_b000>;
impl core::fmt::Debug for Uarte2Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uarte2Ns").finish()
    }
}
#[doc = "UART with EasyDMA 4"]
pub use self::uarte0_ns as uarte2_ns;
#[doc = "Serial Peripheral Interface Master with EasyDMA 7"]
pub type Spim2S = crate::Periph<spim0_ns::RegisterBlock, 0x5000_b000>;
impl core::fmt::Debug for Spim2S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spim2S").finish()
    }
}
#[doc = "Serial Peripheral Interface Master with EasyDMA 7"]
pub use self::spim0_ns as spim2_s;
#[doc = "SPI Slave 5"]
pub type Spis2S = crate::Periph<spis0_ns::RegisterBlock, 0x5000_b000>;
impl core::fmt::Debug for Spis2S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spis2S").finish()
    }
}
#[doc = "SPI Slave 5"]
pub use self::spis0_ns as spis2_s;
#[doc = "I2C compatible Two-Wire Master Interface with EasyDMA 5"]
pub type Twim2S = crate::Periph<twim0_ns::RegisterBlock, 0x5000_b000>;
impl core::fmt::Debug for Twim2S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Twim2S").finish()
    }
}
#[doc = "I2C compatible Two-Wire Master Interface with EasyDMA 5"]
pub use self::twim0_ns as twim2_s;
#[doc = "I2C compatible Two-Wire Slave Interface with EasyDMA 5"]
pub type Twis2S = crate::Periph<twis0_ns::RegisterBlock, 0x5000_b000>;
impl core::fmt::Debug for Twis2S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Twis2S").finish()
    }
}
#[doc = "I2C compatible Two-Wire Slave Interface with EasyDMA 5"]
pub use self::twis0_ns as twis2_s;
#[doc = "UART with EasyDMA 5"]
pub type Uarte2S = crate::Periph<uarte0_ns::RegisterBlock, 0x5000_b000>;
impl core::fmt::Debug for Uarte2S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uarte2S").finish()
    }
}
#[doc = "UART with EasyDMA 5"]
pub use self::uarte0_ns as uarte2_s;
#[doc = "Serial Peripheral Interface Master with EasyDMA 8"]
pub type Spim3Ns = crate::Periph<spim0_ns::RegisterBlock, 0x4000_c000>;
impl core::fmt::Debug for Spim3Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spim3Ns").finish()
    }
}
#[doc = "Serial Peripheral Interface Master with EasyDMA 8"]
pub use self::spim0_ns as spim3_ns;
#[doc = "SPI Slave 6"]
pub type Spis3Ns = crate::Periph<spis0_ns::RegisterBlock, 0x4000_c000>;
impl core::fmt::Debug for Spis3Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spis3Ns").finish()
    }
}
#[doc = "SPI Slave 6"]
pub use self::spis0_ns as spis3_ns;
#[doc = "I2C compatible Two-Wire Master Interface with EasyDMA 6"]
pub type Twim3Ns = crate::Periph<twim0_ns::RegisterBlock, 0x4000_c000>;
impl core::fmt::Debug for Twim3Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Twim3Ns").finish()
    }
}
#[doc = "I2C compatible Two-Wire Master Interface with EasyDMA 6"]
pub use self::twim0_ns as twim3_ns;
#[doc = "I2C compatible Two-Wire Slave Interface with EasyDMA 6"]
pub type Twis3Ns = crate::Periph<twis0_ns::RegisterBlock, 0x4000_c000>;
impl core::fmt::Debug for Twis3Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Twis3Ns").finish()
    }
}
#[doc = "I2C compatible Two-Wire Slave Interface with EasyDMA 6"]
pub use self::twis0_ns as twis3_ns;
#[doc = "UART with EasyDMA 6"]
pub type Uarte3Ns = crate::Periph<uarte0_ns::RegisterBlock, 0x4000_c000>;
impl core::fmt::Debug for Uarte3Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uarte3Ns").finish()
    }
}
#[doc = "UART with EasyDMA 6"]
pub use self::uarte0_ns as uarte3_ns;
#[doc = "Serial Peripheral Interface Master with EasyDMA 9"]
pub type Spim3S = crate::Periph<spim0_ns::RegisterBlock, 0x5000_c000>;
impl core::fmt::Debug for Spim3S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spim3S").finish()
    }
}
#[doc = "Serial Peripheral Interface Master with EasyDMA 9"]
pub use self::spim0_ns as spim3_s;
#[doc = "SPI Slave 7"]
pub type Spis3S = crate::Periph<spis0_ns::RegisterBlock, 0x5000_c000>;
impl core::fmt::Debug for Spis3S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spis3S").finish()
    }
}
#[doc = "SPI Slave 7"]
pub use self::spis0_ns as spis3_s;
#[doc = "I2C compatible Two-Wire Master Interface with EasyDMA 7"]
pub type Twim3S = crate::Periph<twim0_ns::RegisterBlock, 0x5000_c000>;
impl core::fmt::Debug for Twim3S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Twim3S").finish()
    }
}
#[doc = "I2C compatible Two-Wire Master Interface with EasyDMA 7"]
pub use self::twim0_ns as twim3_s;
#[doc = "I2C compatible Two-Wire Slave Interface with EasyDMA 7"]
pub type Twis3S = crate::Periph<twis0_ns::RegisterBlock, 0x5000_c000>;
impl core::fmt::Debug for Twis3S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Twis3S").finish()
    }
}
#[doc = "I2C compatible Two-Wire Slave Interface with EasyDMA 7"]
pub use self::twis0_ns as twis3_s;
#[doc = "UART with EasyDMA 7"]
pub type Uarte3S = crate::Periph<uarte0_ns::RegisterBlock, 0x5000_c000>;
impl core::fmt::Debug for Uarte3S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uarte3S").finish()
    }
}
#[doc = "UART with EasyDMA 7"]
pub use self::uarte0_ns as uarte3_s;
#[doc = "GPIO Tasks and Events 0"]
pub type Gpiote0S = crate::Periph<gpiote0_s::RegisterBlock, 0x5000_d000>;
impl core::fmt::Debug for Gpiote0S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpiote0S").finish()
    }
}
#[doc = "GPIO Tasks and Events 0"]
pub mod gpiote0_s;
#[doc = "Analog to Digital Converter 0"]
pub type SaadcNs = crate::Periph<saadc_ns::RegisterBlock, 0x4000_e000>;
impl core::fmt::Debug for SaadcNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SaadcNs").finish()
    }
}
#[doc = "Analog to Digital Converter 0"]
pub mod saadc_ns;
#[doc = "Analog to Digital Converter 1"]
pub type SaadcS = crate::Periph<saadc_ns::RegisterBlock, 0x5000_e000>;
impl core::fmt::Debug for SaadcS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SaadcS").finish()
    }
}
#[doc = "Analog to Digital Converter 1"]
pub use self::saadc_ns as saadc_s;
#[doc = "Timer/Counter 0"]
pub type Timer0Ns = crate::Periph<timer0_ns::RegisterBlock, 0x4000_f000>;
impl core::fmt::Debug for Timer0Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timer0Ns").finish()
    }
}
#[doc = "Timer/Counter 0"]
pub mod timer0_ns;
#[doc = "Timer/Counter 1"]
pub type Timer0S = crate::Periph<timer0_ns::RegisterBlock, 0x5000_f000>;
impl core::fmt::Debug for Timer0S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timer0S").finish()
    }
}
#[doc = "Timer/Counter 1"]
pub use self::timer0_ns as timer0_s;
#[doc = "Timer/Counter 2"]
pub type Timer1Ns = crate::Periph<timer0_ns::RegisterBlock, 0x4001_0000>;
impl core::fmt::Debug for Timer1Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timer1Ns").finish()
    }
}
#[doc = "Timer/Counter 2"]
pub use self::timer0_ns as timer1_ns;
#[doc = "Timer/Counter 3"]
pub type Timer1S = crate::Periph<timer0_ns::RegisterBlock, 0x5001_0000>;
impl core::fmt::Debug for Timer1S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timer1S").finish()
    }
}
#[doc = "Timer/Counter 3"]
pub use self::timer0_ns as timer1_s;
#[doc = "Timer/Counter 4"]
pub type Timer2Ns = crate::Periph<timer0_ns::RegisterBlock, 0x4001_1000>;
impl core::fmt::Debug for Timer2Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timer2Ns").finish()
    }
}
#[doc = "Timer/Counter 4"]
pub use self::timer0_ns as timer2_ns;
#[doc = "Timer/Counter 5"]
pub type Timer2S = crate::Periph<timer0_ns::RegisterBlock, 0x5001_1000>;
impl core::fmt::Debug for Timer2S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timer2S").finish()
    }
}
#[doc = "Timer/Counter 5"]
pub use self::timer0_ns as timer2_s;
#[doc = "Real-time counter 0"]
pub type Rtc0Ns = crate::Periph<rtc0_ns::RegisterBlock, 0x4001_4000>;
impl core::fmt::Debug for Rtc0Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Rtc0Ns").finish()
    }
}
#[doc = "Real-time counter 0"]
pub mod rtc0_ns;
#[doc = "Real-time counter 1"]
pub type Rtc0S = crate::Periph<rtc0_ns::RegisterBlock, 0x5001_4000>;
impl core::fmt::Debug for Rtc0S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Rtc0S").finish()
    }
}
#[doc = "Real-time counter 1"]
pub use self::rtc0_ns as rtc0_s;
#[doc = "Real-time counter 2"]
pub type Rtc1Ns = crate::Periph<rtc0_ns::RegisterBlock, 0x4001_5000>;
impl core::fmt::Debug for Rtc1Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Rtc1Ns").finish()
    }
}
#[doc = "Real-time counter 2"]
pub use self::rtc0_ns as rtc1_ns;
#[doc = "Real-time counter 3"]
pub type Rtc1S = crate::Periph<rtc0_ns::RegisterBlock, 0x5001_5000>;
impl core::fmt::Debug for Rtc1S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Rtc1S").finish()
    }
}
#[doc = "Real-time counter 3"]
pub use self::rtc0_ns as rtc1_s;
#[doc = "Distributed programmable peripheral interconnect controller 0"]
pub type DppicNs = crate::Periph<dppic_ns::RegisterBlock, 0x4001_7000>;
impl core::fmt::Debug for DppicNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("DppicNs").finish()
    }
}
#[doc = "Distributed programmable peripheral interconnect controller 0"]
pub mod dppic_ns;
#[doc = "Distributed programmable peripheral interconnect controller 1"]
pub type DppicS = crate::Periph<dppic_ns::RegisterBlock, 0x5001_7000>;
impl core::fmt::Debug for DppicS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("DppicS").finish()
    }
}
#[doc = "Distributed programmable peripheral interconnect controller 1"]
pub use self::dppic_ns as dppic_s;
#[doc = "Watchdog Timer 0"]
pub type Wdt0Ns = crate::Periph<wdt0_ns::RegisterBlock, 0x4001_8000>;
impl core::fmt::Debug for Wdt0Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Wdt0Ns").finish()
    }
}
#[doc = "Watchdog Timer 0"]
pub mod wdt0_ns;
#[doc = "Watchdog Timer 1"]
pub type Wdt0S = crate::Periph<wdt0_ns::RegisterBlock, 0x5001_8000>;
impl core::fmt::Debug for Wdt0S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Wdt0S").finish()
    }
}
#[doc = "Watchdog Timer 1"]
pub use self::wdt0_ns as wdt0_s;
#[doc = "Watchdog Timer 2"]
pub type Wdt1Ns = crate::Periph<wdt0_ns::RegisterBlock, 0x4001_9000>;
impl core::fmt::Debug for Wdt1Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Wdt1Ns").finish()
    }
}
#[doc = "Watchdog Timer 2"]
pub use self::wdt0_ns as wdt1_ns;
#[doc = "Watchdog Timer 3"]
pub type Wdt1S = crate::Periph<wdt0_ns::RegisterBlock, 0x5001_9000>;
impl core::fmt::Debug for Wdt1S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Wdt1S").finish()
    }
}
#[doc = "Watchdog Timer 3"]
pub use self::wdt0_ns as wdt1_s;
#[doc = "Comparator 0"]
pub type CompNs = crate::Periph<comp_ns::RegisterBlock, 0x4001_a000>;
impl core::fmt::Debug for CompNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("CompNs").finish()
    }
}
#[doc = "Comparator 0"]
pub mod comp_ns;
#[doc = "Low-power comparator 0"]
pub type LpcompNs = crate::Periph<lpcomp_ns::RegisterBlock, 0x4001_a000>;
impl core::fmt::Debug for LpcompNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("LpcompNs").finish()
    }
}
#[doc = "Low-power comparator 0"]
pub mod lpcomp_ns;
#[doc = "Comparator 1"]
pub type CompS = crate::Periph<comp_ns::RegisterBlock, 0x5001_a000>;
impl core::fmt::Debug for CompS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("CompS").finish()
    }
}
#[doc = "Comparator 1"]
pub use self::comp_ns as comp_s;
#[doc = "Low-power comparator 1"]
pub type LpcompS = crate::Periph<lpcomp_ns::RegisterBlock, 0x5001_a000>;
impl core::fmt::Debug for LpcompS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("LpcompS").finish()
    }
}
#[doc = "Low-power comparator 1"]
pub use self::lpcomp_ns as lpcomp_s;
#[doc = "Event generator unit 0"]
pub type Egu0Ns = crate::Periph<egu0_ns::RegisterBlock, 0x4001_b000>;
impl core::fmt::Debug for Egu0Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Egu0Ns").finish()
    }
}
#[doc = "Event generator unit 0"]
pub mod egu0_ns;
#[doc = "Event generator unit 1"]
pub type Egu0S = crate::Periph<egu0_ns::RegisterBlock, 0x5001_b000>;
impl core::fmt::Debug for Egu0S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Egu0S").finish()
    }
}
#[doc = "Event generator unit 1"]
pub use self::egu0_ns as egu0_s;
#[doc = "Event generator unit 2"]
pub type Egu1Ns = crate::Periph<egu0_ns::RegisterBlock, 0x4001_c000>;
impl core::fmt::Debug for Egu1Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Egu1Ns").finish()
    }
}
#[doc = "Event generator unit 2"]
pub use self::egu0_ns as egu1_ns;
#[doc = "Event generator unit 3"]
pub type Egu1S = crate::Periph<egu0_ns::RegisterBlock, 0x5001_c000>;
impl core::fmt::Debug for Egu1S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Egu1S").finish()
    }
}
#[doc = "Event generator unit 3"]
pub use self::egu0_ns as egu1_s;
#[doc = "Event generator unit 4"]
pub type Egu2Ns = crate::Periph<egu0_ns::RegisterBlock, 0x4001_d000>;
impl core::fmt::Debug for Egu2Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Egu2Ns").finish()
    }
}
#[doc = "Event generator unit 4"]
pub use self::egu0_ns as egu2_ns;
#[doc = "Event generator unit 5"]
pub type Egu2S = crate::Periph<egu0_ns::RegisterBlock, 0x5001_d000>;
impl core::fmt::Debug for Egu2S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Egu2S").finish()
    }
}
#[doc = "Event generator unit 5"]
pub use self::egu0_ns as egu2_s;
#[doc = "Event generator unit 6"]
pub type Egu3Ns = crate::Periph<egu0_ns::RegisterBlock, 0x4001_e000>;
impl core::fmt::Debug for Egu3Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Egu3Ns").finish()
    }
}
#[doc = "Event generator unit 6"]
pub use self::egu0_ns as egu3_ns;
#[doc = "Event generator unit 7"]
pub type Egu3S = crate::Periph<egu0_ns::RegisterBlock, 0x5001_e000>;
impl core::fmt::Debug for Egu3S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Egu3S").finish()
    }
}
#[doc = "Event generator unit 7"]
pub use self::egu0_ns as egu3_s;
#[doc = "Event generator unit 8"]
pub type Egu4Ns = crate::Periph<egu0_ns::RegisterBlock, 0x4001_f000>;
impl core::fmt::Debug for Egu4Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Egu4Ns").finish()
    }
}
#[doc = "Event generator unit 8"]
pub use self::egu0_ns as egu4_ns;
#[doc = "Event generator unit 9"]
pub type Egu4S = crate::Periph<egu0_ns::RegisterBlock, 0x5001_f000>;
impl core::fmt::Debug for Egu4S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Egu4S").finish()
    }
}
#[doc = "Event generator unit 9"]
pub use self::egu0_ns as egu4_s;
#[doc = "Event generator unit 10"]
pub type Egu5Ns = crate::Periph<egu0_ns::RegisterBlock, 0x4002_0000>;
impl core::fmt::Debug for Egu5Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Egu5Ns").finish()
    }
}
#[doc = "Event generator unit 10"]
pub use self::egu0_ns as egu5_ns;
#[doc = "Event generator unit 11"]
pub type Egu5S = crate::Periph<egu0_ns::RegisterBlock, 0x5002_0000>;
impl core::fmt::Debug for Egu5S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Egu5S").finish()
    }
}
#[doc = "Event generator unit 11"]
pub use self::egu0_ns as egu5_s;
#[doc = "Pulse width modulation unit 0"]
pub type Pwm0Ns = crate::Periph<pwm0_ns::RegisterBlock, 0x4002_1000>;
impl core::fmt::Debug for Pwm0Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pwm0Ns").finish()
    }
}
#[doc = "Pulse width modulation unit 0"]
pub mod pwm0_ns;
#[doc = "Pulse width modulation unit 1"]
pub type Pwm0S = crate::Periph<pwm0_ns::RegisterBlock, 0x5002_1000>;
impl core::fmt::Debug for Pwm0S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pwm0S").finish()
    }
}
#[doc = "Pulse width modulation unit 1"]
pub use self::pwm0_ns as pwm0_s;
#[doc = "Pulse width modulation unit 2"]
pub type Pwm1Ns = crate::Periph<pwm0_ns::RegisterBlock, 0x4002_2000>;
impl core::fmt::Debug for Pwm1Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pwm1Ns").finish()
    }
}
#[doc = "Pulse width modulation unit 2"]
pub use self::pwm0_ns as pwm1_ns;
#[doc = "Pulse width modulation unit 3"]
pub type Pwm1S = crate::Periph<pwm0_ns::RegisterBlock, 0x5002_2000>;
impl core::fmt::Debug for Pwm1S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pwm1S").finish()
    }
}
#[doc = "Pulse width modulation unit 3"]
pub use self::pwm0_ns as pwm1_s;
#[doc = "Pulse width modulation unit 4"]
pub type Pwm2Ns = crate::Periph<pwm0_ns::RegisterBlock, 0x4002_3000>;
impl core::fmt::Debug for Pwm2Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pwm2Ns").finish()
    }
}
#[doc = "Pulse width modulation unit 4"]
pub use self::pwm0_ns as pwm2_ns;
#[doc = "Pulse width modulation unit 5"]
pub type Pwm2S = crate::Periph<pwm0_ns::RegisterBlock, 0x5002_3000>;
impl core::fmt::Debug for Pwm2S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pwm2S").finish()
    }
}
#[doc = "Pulse width modulation unit 5"]
pub use self::pwm0_ns as pwm2_s;
#[doc = "Pulse width modulation unit 6"]
pub type Pwm3Ns = crate::Periph<pwm0_ns::RegisterBlock, 0x4002_4000>;
impl core::fmt::Debug for Pwm3Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pwm3Ns").finish()
    }
}
#[doc = "Pulse width modulation unit 6"]
pub use self::pwm0_ns as pwm3_ns;
#[doc = "Pulse width modulation unit 7"]
pub type Pwm3S = crate::Periph<pwm0_ns::RegisterBlock, 0x5002_4000>;
impl core::fmt::Debug for Pwm3S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pwm3S").finish()
    }
}
#[doc = "Pulse width modulation unit 7"]
pub use self::pwm0_ns as pwm3_s;
#[doc = "Pulse Density Modulation (Digital Microphone) Interface 0"]
pub type Pdm0Ns = crate::Periph<pdm0_ns::RegisterBlock, 0x4002_6000>;
impl core::fmt::Debug for Pdm0Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pdm0Ns").finish()
    }
}
#[doc = "Pulse Density Modulation (Digital Microphone) Interface 0"]
pub mod pdm0_ns;
#[doc = "Pulse Density Modulation (Digital Microphone) Interface 1"]
pub type Pdm0S = crate::Periph<pdm0_ns::RegisterBlock, 0x5002_6000>;
impl core::fmt::Debug for Pdm0S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pdm0S").finish()
    }
}
#[doc = "Pulse Density Modulation (Digital Microphone) Interface 1"]
pub use self::pdm0_ns as pdm0_s;
#[doc = "Inter-IC Sound 0"]
pub type I2s0Ns = crate::Periph<i2s0_ns::RegisterBlock, 0x4002_8000>;
impl core::fmt::Debug for I2s0Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2s0Ns").finish()
    }
}
#[doc = "Inter-IC Sound 0"]
pub mod i2s0_ns;
#[doc = "Inter-IC Sound 1"]
pub type I2s0S = crate::Periph<i2s0_ns::RegisterBlock, 0x5002_8000>;
impl core::fmt::Debug for I2s0S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2s0S").finish()
    }
}
#[doc = "Inter-IC Sound 1"]
pub use self::i2s0_ns as i2s0_s;
#[doc = "Interprocessor communication 0"]
pub type IpcNs = crate::Periph<ipc_ns::RegisterBlock, 0x4002_a000>;
impl core::fmt::Debug for IpcNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("IpcNs").finish()
    }
}
#[doc = "Interprocessor communication 0"]
pub mod ipc_ns;
#[doc = "Interprocessor communication 1"]
pub type IpcS = crate::Periph<ipc_ns::RegisterBlock, 0x5002_a000>;
impl core::fmt::Debug for IpcS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("IpcS").finish()
    }
}
#[doc = "Interprocessor communication 1"]
pub use self::ipc_ns as ipc_s;
#[doc = "External flash interface 0"]
pub type QspiNs = crate::Periph<qspi_ns::RegisterBlock, 0x4002_b000>;
impl core::fmt::Debug for QspiNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("QspiNs").finish()
    }
}
#[doc = "External flash interface 0"]
pub mod qspi_ns;
#[doc = "External flash interface 1"]
pub type QspiS = crate::Periph<qspi_ns::RegisterBlock, 0x5002_b000>;
impl core::fmt::Debug for QspiS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("QspiS").finish()
    }
}
#[doc = "External flash interface 1"]
pub use self::qspi_ns as qspi_s;
#[doc = "NFC-A compatible radio 0"]
pub type NfctNs = crate::Periph<nfct_ns::RegisterBlock, 0x4002_d000>;
impl core::fmt::Debug for NfctNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("NfctNs").finish()
    }
}
#[doc = "NFC-A compatible radio 0"]
pub mod nfct_ns;
#[doc = "NFC-A compatible radio 1"]
pub type NfctS = crate::Periph<nfct_ns::RegisterBlock, 0x5002_d000>;
impl core::fmt::Debug for NfctS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("NfctS").finish()
    }
}
#[doc = "NFC-A compatible radio 1"]
pub use self::nfct_ns as nfct_s;
#[doc = "GPIO Tasks and Events 1"]
pub type Gpiote1Ns = crate::Periph<gpiote0_s::RegisterBlock, 0x4002_f000>;
impl core::fmt::Debug for Gpiote1Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpiote1Ns").finish()
    }
}
#[doc = "GPIO Tasks and Events 1"]
pub use self::gpiote0_s as gpiote1_ns;
#[doc = "MUTEX 0"]
pub type MutexNs = crate::Periph<mutex_ns::RegisterBlock, 0x4003_0000>;
impl core::fmt::Debug for MutexNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("MutexNs").finish()
    }
}
#[doc = "MUTEX 0"]
pub mod mutex_ns;
#[doc = "MUTEX 1"]
pub type MutexS = crate::Periph<mutex_ns::RegisterBlock, 0x5003_0000>;
impl core::fmt::Debug for MutexS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("MutexS").finish()
    }
}
#[doc = "MUTEX 1"]
pub use self::mutex_ns as mutex_s;
#[doc = "Quadrature Decoder 0"]
pub type Qdec0Ns = crate::Periph<qdec0_ns::RegisterBlock, 0x4003_3000>;
impl core::fmt::Debug for Qdec0Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Qdec0Ns").finish()
    }
}
#[doc = "Quadrature Decoder 0"]
pub mod qdec0_ns;
#[doc = "Quadrature Decoder 1"]
pub type Qdec0S = crate::Periph<qdec0_ns::RegisterBlock, 0x5003_3000>;
impl core::fmt::Debug for Qdec0S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Qdec0S").finish()
    }
}
#[doc = "Quadrature Decoder 1"]
pub use self::qdec0_ns as qdec0_s;
#[doc = "Quadrature Decoder 2"]
pub type Qdec1Ns = crate::Periph<qdec0_ns::RegisterBlock, 0x4003_4000>;
impl core::fmt::Debug for Qdec1Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Qdec1Ns").finish()
    }
}
#[doc = "Quadrature Decoder 2"]
pub use self::qdec0_ns as qdec1_ns;
#[doc = "Quadrature Decoder 3"]
pub type Qdec1S = crate::Periph<qdec0_ns::RegisterBlock, 0x5003_4000>;
impl core::fmt::Debug for Qdec1S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Qdec1S").finish()
    }
}
#[doc = "Quadrature Decoder 3"]
pub use self::qdec0_ns as qdec1_s;
#[doc = "Universal serial bus device 0"]
pub type UsbdNs = crate::Periph<usbd_ns::RegisterBlock, 0x4003_6000>;
impl core::fmt::Debug for UsbdNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("UsbdNs").finish()
    }
}
#[doc = "Universal serial bus device 0"]
pub mod usbd_ns;
#[doc = "Universal serial bus device 1"]
pub type UsbdS = crate::Periph<usbd_ns::RegisterBlock, 0x5003_6000>;
impl core::fmt::Debug for UsbdS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("UsbdS").finish()
    }
}
#[doc = "Universal serial bus device 1"]
pub use self::usbd_ns as usbd_s;
#[doc = "USB Regulator 0"]
pub type UsbregulatorNs = crate::Periph<usbregulator_ns::RegisterBlock, 0x4003_7000>;
impl core::fmt::Debug for UsbregulatorNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("UsbregulatorNs").finish()
    }
}
#[doc = "USB Regulator 0"]
pub mod usbregulator_ns;
#[doc = "USB Regulator 1"]
pub type UsbregulatorS = crate::Periph<usbregulator_ns::RegisterBlock, 0x5003_7000>;
impl core::fmt::Debug for UsbregulatorS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("UsbregulatorS").finish()
    }
}
#[doc = "USB Regulator 1"]
pub use self::usbregulator_ns as usbregulator_s;
#[doc = "Key management unit 0"]
pub type KmuNs = crate::Periph<kmu_ns::RegisterBlock, 0x4003_9000>;
impl core::fmt::Debug for KmuNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("KmuNs").finish()
    }
}
#[doc = "Key management unit 0"]
pub mod kmu_ns;
#[doc = "Non-volatile memory controller 0"]
pub type NvmcNs = crate::Periph<nvmc_ns::RegisterBlock, 0x4003_9000>;
impl core::fmt::Debug for NvmcNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("NvmcNs").finish()
    }
}
#[doc = "Non-volatile memory controller 0"]
pub mod nvmc_ns;
#[doc = "Key management unit 1"]
pub type KmuS = crate::Periph<kmu_ns::RegisterBlock, 0x5003_9000>;
impl core::fmt::Debug for KmuS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("KmuS").finish()
    }
}
#[doc = "Key management unit 1"]
pub use self::kmu_ns as kmu_s;
#[doc = "Non-volatile memory controller 1"]
pub type NvmcS = crate::Periph<nvmc_ns::RegisterBlock, 0x5003_9000>;
impl core::fmt::Debug for NvmcS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("NvmcS").finish()
    }
}
#[doc = "Non-volatile memory controller 1"]
pub use self::nvmc_ns as nvmc_s;
#[doc = "GPIO Port 0"]
pub type P0Ns = crate::Periph<p0_ns::RegisterBlock, 0x4084_2500>;
impl core::fmt::Debug for P0Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("P0Ns").finish()
    }
}
#[doc = "GPIO Port 0"]
pub mod p0_ns;
#[doc = "GPIO Port 1"]
pub type P1Ns = crate::Periph<p0_ns::RegisterBlock, 0x4084_2800>;
impl core::fmt::Debug for P1Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("P1Ns").finish()
    }
}
#[doc = "GPIO Port 1"]
pub use self::p0_ns as p1_ns;
#[doc = "GPIO Port 2"]
pub type P0S = crate::Periph<p0_ns::RegisterBlock, 0x5084_2500>;
impl core::fmt::Debug for P0S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("P0S").finish()
    }
}
#[doc = "GPIO Port 2"]
pub use self::p0_ns as p0_s;
#[doc = "GPIO Port 3"]
pub type P1S = crate::Periph<p0_ns::RegisterBlock, 0x5084_2800>;
impl core::fmt::Debug for P1S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("P1S").finish()
    }
}
#[doc = "GPIO Port 3"]
pub use self::p0_ns as p1_s;
#[doc = "ARM TrustZone CryptoCell register interface"]
pub type CryptocellS = crate::Periph<cryptocell_s::RegisterBlock, 0x5084_4000>;
impl core::fmt::Debug for CryptocellS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("CryptocellS").finish()
    }
}
#[doc = "ARM TrustZone CryptoCell register interface"]
pub mod cryptocell_s;
#[doc = "Volatile Memory controller 0"]
pub type VmcNs = crate::Periph<vmc_ns::RegisterBlock, 0x4008_1000>;
impl core::fmt::Debug for VmcNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("VmcNs").finish()
    }
}
#[doc = "Volatile Memory controller 0"]
pub mod vmc_ns;
#[doc = "Volatile Memory controller 1"]
pub type VmcS = crate::Periph<vmc_ns::RegisterBlock, 0x5008_1000>;
impl core::fmt::Debug for VmcS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("VmcS").finish()
    }
}
#[doc = "Volatile Memory controller 1"]
pub use self::vmc_ns as vmc_s;
#[no_mangle]
static mut DEVICE_PERIPHERALS: bool = false;
#[doc = r" All the peripherals."]
#[allow(non_snake_case)]
pub struct Peripherals {
    #[doc = "CACHEDATA_S"]
    pub cachedata_s: CachedataS,
    #[doc = "CACHEINFO_S"]
    pub cacheinfo_s: CacheinfoS,
    #[doc = "FICR_S"]
    pub ficr_s: FicrS,
    #[doc = "UICR_S"]
    pub uicr_s: UicrS,
    #[doc = "CTI_S"]
    pub cti_s: CtiS,
    #[doc = "TAD_S"]
    pub tad_s: TadS,
    #[doc = "DCNF_NS"]
    pub dcnf_ns: DcnfNs,
    #[doc = "FPU_NS"]
    pub fpu_ns: FpuNs,
    #[doc = "DCNF_S"]
    pub dcnf_s: DcnfS,
    #[doc = "FPU_S"]
    pub fpu_s: FpuS,
    #[doc = "CACHE_S"]
    pub cache_s: CacheS,
    #[doc = "SPU_S"]
    pub spu_s: SpuS,
    #[doc = "OSCILLATORS_NS"]
    pub oscillators_ns: OscillatorsNs,
    #[doc = "REGULATORS_NS"]
    pub regulators_ns: RegulatorsNs,
    #[doc = "OSCILLATORS_S"]
    pub oscillators_s: OscillatorsS,
    #[doc = "REGULATORS_S"]
    pub regulators_s: RegulatorsS,
    #[doc = "CLOCK_NS"]
    pub clock_ns: ClockNs,
    #[doc = "POWER_NS"]
    pub power_ns: PowerNs,
    #[doc = "RESET_NS"]
    pub reset_ns: ResetNs,
    #[doc = "CLOCK_S"]
    pub clock_s: ClockS,
    #[doc = "POWER_S"]
    pub power_s: PowerS,
    #[doc = "RESET_S"]
    pub reset_s: ResetS,
    #[doc = "CTRLAP_NS"]
    pub ctrlap_ns: CtrlapNs,
    #[doc = "CTRLAP_S"]
    pub ctrlap_s: CtrlapS,
    #[doc = "SPIM0_NS"]
    pub spim0_ns: Spim0Ns,
    #[doc = "SPIS0_NS"]
    pub spis0_ns: Spis0Ns,
    #[doc = "TWIM0_NS"]
    pub twim0_ns: Twim0Ns,
    #[doc = "TWIS0_NS"]
    pub twis0_ns: Twis0Ns,
    #[doc = "UARTE0_NS"]
    pub uarte0_ns: Uarte0Ns,
    #[doc = "SPIM0_S"]
    pub spim0_s: Spim0S,
    #[doc = "SPIS0_S"]
    pub spis0_s: Spis0S,
    #[doc = "TWIM0_S"]
    pub twim0_s: Twim0S,
    #[doc = "TWIS0_S"]
    pub twis0_s: Twis0S,
    #[doc = "UARTE0_S"]
    pub uarte0_s: Uarte0S,
    #[doc = "SPIM1_NS"]
    pub spim1_ns: Spim1Ns,
    #[doc = "SPIS1_NS"]
    pub spis1_ns: Spis1Ns,
    #[doc = "TWIM1_NS"]
    pub twim1_ns: Twim1Ns,
    #[doc = "TWIS1_NS"]
    pub twis1_ns: Twis1Ns,
    #[doc = "UARTE1_NS"]
    pub uarte1_ns: Uarte1Ns,
    #[doc = "SPIM1_S"]
    pub spim1_s: Spim1S,
    #[doc = "SPIS1_S"]
    pub spis1_s: Spis1S,
    #[doc = "TWIM1_S"]
    pub twim1_s: Twim1S,
    #[doc = "TWIS1_S"]
    pub twis1_s: Twis1S,
    #[doc = "UARTE1_S"]
    pub uarte1_s: Uarte1S,
    #[doc = "SPIM4_NS"]
    pub spim4_ns: Spim4Ns,
    #[doc = "SPIM4_S"]
    pub spim4_s: Spim4S,
    #[doc = "SPIM2_NS"]
    pub spim2_ns: Spim2Ns,
    #[doc = "SPIS2_NS"]
    pub spis2_ns: Spis2Ns,
    #[doc = "TWIM2_NS"]
    pub twim2_ns: Twim2Ns,
    #[doc = "TWIS2_NS"]
    pub twis2_ns: Twis2Ns,
    #[doc = "UARTE2_NS"]
    pub uarte2_ns: Uarte2Ns,
    #[doc = "SPIM2_S"]
    pub spim2_s: Spim2S,
    #[doc = "SPIS2_S"]
    pub spis2_s: Spis2S,
    #[doc = "TWIM2_S"]
    pub twim2_s: Twim2S,
    #[doc = "TWIS2_S"]
    pub twis2_s: Twis2S,
    #[doc = "UARTE2_S"]
    pub uarte2_s: Uarte2S,
    #[doc = "SPIM3_NS"]
    pub spim3_ns: Spim3Ns,
    #[doc = "SPIS3_NS"]
    pub spis3_ns: Spis3Ns,
    #[doc = "TWIM3_NS"]
    pub twim3_ns: Twim3Ns,
    #[doc = "TWIS3_NS"]
    pub twis3_ns: Twis3Ns,
    #[doc = "UARTE3_NS"]
    pub uarte3_ns: Uarte3Ns,
    #[doc = "SPIM3_S"]
    pub spim3_s: Spim3S,
    #[doc = "SPIS3_S"]
    pub spis3_s: Spis3S,
    #[doc = "TWIM3_S"]
    pub twim3_s: Twim3S,
    #[doc = "TWIS3_S"]
    pub twis3_s: Twis3S,
    #[doc = "UARTE3_S"]
    pub uarte3_s: Uarte3S,
    #[doc = "GPIOTE0_S"]
    pub gpiote0_s: Gpiote0S,
    #[doc = "SAADC_NS"]
    pub saadc_ns: SaadcNs,
    #[doc = "SAADC_S"]
    pub saadc_s: SaadcS,
    #[doc = "TIMER0_NS"]
    pub timer0_ns: Timer0Ns,
    #[doc = "TIMER0_S"]
    pub timer0_s: Timer0S,
    #[doc = "TIMER1_NS"]
    pub timer1_ns: Timer1Ns,
    #[doc = "TIMER1_S"]
    pub timer1_s: Timer1S,
    #[doc = "TIMER2_NS"]
    pub timer2_ns: Timer2Ns,
    #[doc = "TIMER2_S"]
    pub timer2_s: Timer2S,
    #[doc = "RTC0_NS"]
    pub rtc0_ns: Rtc0Ns,
    #[doc = "RTC0_S"]
    pub rtc0_s: Rtc0S,
    #[doc = "RTC1_NS"]
    pub rtc1_ns: Rtc1Ns,
    #[doc = "RTC1_S"]
    pub rtc1_s: Rtc1S,
    #[doc = "DPPIC_NS"]
    pub dppic_ns: DppicNs,
    #[doc = "DPPIC_S"]
    pub dppic_s: DppicS,
    #[doc = "WDT0_NS"]
    pub wdt0_ns: Wdt0Ns,
    #[doc = "WDT0_S"]
    pub wdt0_s: Wdt0S,
    #[doc = "WDT1_NS"]
    pub wdt1_ns: Wdt1Ns,
    #[doc = "WDT1_S"]
    pub wdt1_s: Wdt1S,
    #[doc = "COMP_NS"]
    pub comp_ns: CompNs,
    #[doc = "LPCOMP_NS"]
    pub lpcomp_ns: LpcompNs,
    #[doc = "COMP_S"]
    pub comp_s: CompS,
    #[doc = "LPCOMP_S"]
    pub lpcomp_s: LpcompS,
    #[doc = "EGU0_NS"]
    pub egu0_ns: Egu0Ns,
    #[doc = "EGU0_S"]
    pub egu0_s: Egu0S,
    #[doc = "EGU1_NS"]
    pub egu1_ns: Egu1Ns,
    #[doc = "EGU1_S"]
    pub egu1_s: Egu1S,
    #[doc = "EGU2_NS"]
    pub egu2_ns: Egu2Ns,
    #[doc = "EGU2_S"]
    pub egu2_s: Egu2S,
    #[doc = "EGU3_NS"]
    pub egu3_ns: Egu3Ns,
    #[doc = "EGU3_S"]
    pub egu3_s: Egu3S,
    #[doc = "EGU4_NS"]
    pub egu4_ns: Egu4Ns,
    #[doc = "EGU4_S"]
    pub egu4_s: Egu4S,
    #[doc = "EGU5_NS"]
    pub egu5_ns: Egu5Ns,
    #[doc = "EGU5_S"]
    pub egu5_s: Egu5S,
    #[doc = "PWM0_NS"]
    pub pwm0_ns: Pwm0Ns,
    #[doc = "PWM0_S"]
    pub pwm0_s: Pwm0S,
    #[doc = "PWM1_NS"]
    pub pwm1_ns: Pwm1Ns,
    #[doc = "PWM1_S"]
    pub pwm1_s: Pwm1S,
    #[doc = "PWM2_NS"]
    pub pwm2_ns: Pwm2Ns,
    #[doc = "PWM2_S"]
    pub pwm2_s: Pwm2S,
    #[doc = "PWM3_NS"]
    pub pwm3_ns: Pwm3Ns,
    #[doc = "PWM3_S"]
    pub pwm3_s: Pwm3S,
    #[doc = "PDM0_NS"]
    pub pdm0_ns: Pdm0Ns,
    #[doc = "PDM0_S"]
    pub pdm0_s: Pdm0S,
    #[doc = "I2S0_NS"]
    pub i2s0_ns: I2s0Ns,
    #[doc = "I2S0_S"]
    pub i2s0_s: I2s0S,
    #[doc = "IPC_NS"]
    pub ipc_ns: IpcNs,
    #[doc = "IPC_S"]
    pub ipc_s: IpcS,
    #[doc = "QSPI_NS"]
    pub qspi_ns: QspiNs,
    #[doc = "QSPI_S"]
    pub qspi_s: QspiS,
    #[doc = "NFCT_NS"]
    pub nfct_ns: NfctNs,
    #[doc = "NFCT_S"]
    pub nfct_s: NfctS,
    #[doc = "GPIOTE1_NS"]
    pub gpiote1_ns: Gpiote1Ns,
    #[doc = "MUTEX_NS"]
    pub mutex_ns: MutexNs,
    #[doc = "MUTEX_S"]
    pub mutex_s: MutexS,
    #[doc = "QDEC0_NS"]
    pub qdec0_ns: Qdec0Ns,
    #[doc = "QDEC0_S"]
    pub qdec0_s: Qdec0S,
    #[doc = "QDEC1_NS"]
    pub qdec1_ns: Qdec1Ns,
    #[doc = "QDEC1_S"]
    pub qdec1_s: Qdec1S,
    #[doc = "USBD_NS"]
    pub usbd_ns: UsbdNs,
    #[doc = "USBD_S"]
    pub usbd_s: UsbdS,
    #[doc = "USBREGULATOR_NS"]
    pub usbregulator_ns: UsbregulatorNs,
    #[doc = "USBREGULATOR_S"]
    pub usbregulator_s: UsbregulatorS,
    #[doc = "KMU_NS"]
    pub kmu_ns: KmuNs,
    #[doc = "NVMC_NS"]
    pub nvmc_ns: NvmcNs,
    #[doc = "KMU_S"]
    pub kmu_s: KmuS,
    #[doc = "NVMC_S"]
    pub nvmc_s: NvmcS,
    #[doc = "P0_NS"]
    pub p0_ns: P0Ns,
    #[doc = "P1_NS"]
    pub p1_ns: P1Ns,
    #[doc = "P0_S"]
    pub p0_s: P0S,
    #[doc = "P1_S"]
    pub p1_s: P1S,
    #[doc = "CRYPTOCELL_S"]
    pub cryptocell_s: CryptocellS,
    #[doc = "VMC_NS"]
    pub vmc_ns: VmcNs,
    #[doc = "VMC_S"]
    pub vmc_s: VmcS,
}
impl Peripherals {
    #[doc = r" Returns all the peripherals *once*."]
    #[cfg(feature = "critical-section")]
    #[inline]
    pub fn take() -> Option<Self> {
        critical_section::with(|_| {
            if unsafe { DEVICE_PERIPHERALS } {
                return None;
            }
            Some(unsafe { Peripherals::steal() })
        })
    }
    #[doc = r" Unchecked version of `Peripherals::take`."]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Each of the returned peripherals must be used at most once."]
    #[inline]
    pub unsafe fn steal() -> Self {
        DEVICE_PERIPHERALS = true;
        Peripherals {
            cachedata_s: CachedataS::steal(),
            cacheinfo_s: CacheinfoS::steal(),
            ficr_s: FicrS::steal(),
            uicr_s: UicrS::steal(),
            cti_s: CtiS::steal(),
            tad_s: TadS::steal(),
            dcnf_ns: DcnfNs::steal(),
            fpu_ns: FpuNs::steal(),
            dcnf_s: DcnfS::steal(),
            fpu_s: FpuS::steal(),
            cache_s: CacheS::steal(),
            spu_s: SpuS::steal(),
            oscillators_ns: OscillatorsNs::steal(),
            regulators_ns: RegulatorsNs::steal(),
            oscillators_s: OscillatorsS::steal(),
            regulators_s: RegulatorsS::steal(),
            clock_ns: ClockNs::steal(),
            power_ns: PowerNs::steal(),
            reset_ns: ResetNs::steal(),
            clock_s: ClockS::steal(),
            power_s: PowerS::steal(),
            reset_s: ResetS::steal(),
            ctrlap_ns: CtrlapNs::steal(),
            ctrlap_s: CtrlapS::steal(),
            spim0_ns: Spim0Ns::steal(),
            spis0_ns: Spis0Ns::steal(),
            twim0_ns: Twim0Ns::steal(),
            twis0_ns: Twis0Ns::steal(),
            uarte0_ns: Uarte0Ns::steal(),
            spim0_s: Spim0S::steal(),
            spis0_s: Spis0S::steal(),
            twim0_s: Twim0S::steal(),
            twis0_s: Twis0S::steal(),
            uarte0_s: Uarte0S::steal(),
            spim1_ns: Spim1Ns::steal(),
            spis1_ns: Spis1Ns::steal(),
            twim1_ns: Twim1Ns::steal(),
            twis1_ns: Twis1Ns::steal(),
            uarte1_ns: Uarte1Ns::steal(),
            spim1_s: Spim1S::steal(),
            spis1_s: Spis1S::steal(),
            twim1_s: Twim1S::steal(),
            twis1_s: Twis1S::steal(),
            uarte1_s: Uarte1S::steal(),
            spim4_ns: Spim4Ns::steal(),
            spim4_s: Spim4S::steal(),
            spim2_ns: Spim2Ns::steal(),
            spis2_ns: Spis2Ns::steal(),
            twim2_ns: Twim2Ns::steal(),
            twis2_ns: Twis2Ns::steal(),
            uarte2_ns: Uarte2Ns::steal(),
            spim2_s: Spim2S::steal(),
            spis2_s: Spis2S::steal(),
            twim2_s: Twim2S::steal(),
            twis2_s: Twis2S::steal(),
            uarte2_s: Uarte2S::steal(),
            spim3_ns: Spim3Ns::steal(),
            spis3_ns: Spis3Ns::steal(),
            twim3_ns: Twim3Ns::steal(),
            twis3_ns: Twis3Ns::steal(),
            uarte3_ns: Uarte3Ns::steal(),
            spim3_s: Spim3S::steal(),
            spis3_s: Spis3S::steal(),
            twim3_s: Twim3S::steal(),
            twis3_s: Twis3S::steal(),
            uarte3_s: Uarte3S::steal(),
            gpiote0_s: Gpiote0S::steal(),
            saadc_ns: SaadcNs::steal(),
            saadc_s: SaadcS::steal(),
            timer0_ns: Timer0Ns::steal(),
            timer0_s: Timer0S::steal(),
            timer1_ns: Timer1Ns::steal(),
            timer1_s: Timer1S::steal(),
            timer2_ns: Timer2Ns::steal(),
            timer2_s: Timer2S::steal(),
            rtc0_ns: Rtc0Ns::steal(),
            rtc0_s: Rtc0S::steal(),
            rtc1_ns: Rtc1Ns::steal(),
            rtc1_s: Rtc1S::steal(),
            dppic_ns: DppicNs::steal(),
            dppic_s: DppicS::steal(),
            wdt0_ns: Wdt0Ns::steal(),
            wdt0_s: Wdt0S::steal(),
            wdt1_ns: Wdt1Ns::steal(),
            wdt1_s: Wdt1S::steal(),
            comp_ns: CompNs::steal(),
            lpcomp_ns: LpcompNs::steal(),
            comp_s: CompS::steal(),
            lpcomp_s: LpcompS::steal(),
            egu0_ns: Egu0Ns::steal(),
            egu0_s: Egu0S::steal(),
            egu1_ns: Egu1Ns::steal(),
            egu1_s: Egu1S::steal(),
            egu2_ns: Egu2Ns::steal(),
            egu2_s: Egu2S::steal(),
            egu3_ns: Egu3Ns::steal(),
            egu3_s: Egu3S::steal(),
            egu4_ns: Egu4Ns::steal(),
            egu4_s: Egu4S::steal(),
            egu5_ns: Egu5Ns::steal(),
            egu5_s: Egu5S::steal(),
            pwm0_ns: Pwm0Ns::steal(),
            pwm0_s: Pwm0S::steal(),
            pwm1_ns: Pwm1Ns::steal(),
            pwm1_s: Pwm1S::steal(),
            pwm2_ns: Pwm2Ns::steal(),
            pwm2_s: Pwm2S::steal(),
            pwm3_ns: Pwm3Ns::steal(),
            pwm3_s: Pwm3S::steal(),
            pdm0_ns: Pdm0Ns::steal(),
            pdm0_s: Pdm0S::steal(),
            i2s0_ns: I2s0Ns::steal(),
            i2s0_s: I2s0S::steal(),
            ipc_ns: IpcNs::steal(),
            ipc_s: IpcS::steal(),
            qspi_ns: QspiNs::steal(),
            qspi_s: QspiS::steal(),
            nfct_ns: NfctNs::steal(),
            nfct_s: NfctS::steal(),
            gpiote1_ns: Gpiote1Ns::steal(),
            mutex_ns: MutexNs::steal(),
            mutex_s: MutexS::steal(),
            qdec0_ns: Qdec0Ns::steal(),
            qdec0_s: Qdec0S::steal(),
            qdec1_ns: Qdec1Ns::steal(),
            qdec1_s: Qdec1S::steal(),
            usbd_ns: UsbdNs::steal(),
            usbd_s: UsbdS::steal(),
            usbregulator_ns: UsbregulatorNs::steal(),
            usbregulator_s: UsbregulatorS::steal(),
            kmu_ns: KmuNs::steal(),
            nvmc_ns: NvmcNs::steal(),
            kmu_s: KmuS::steal(),
            nvmc_s: NvmcS::steal(),
            p0_ns: P0Ns::steal(),
            p1_ns: P1Ns::steal(),
            p0_s: P0S::steal(),
            p1_s: P1S::steal(),
            cryptocell_s: CryptocellS::steal(),
            vmc_ns: VmcNs::steal(),
            vmc_s: VmcS::steal(),
        }
    }
}
