#![doc = "Peripheral access API for NRF52810 microcontrollers (generated using svd2rust v0.37.0 ( ))\n\nYou can find an overview of the generated API [here].\n\nAPI features to be included in the [next] svd2rust release can be generated by cloning the svd2rust [repository], checking out the above commit, and running `cargo doc --open`.\n\n[here]: https://docs.rs/svd2rust/0.37.0/svd2rust/#peripheral-api\n[next]: https://github.com/rust-embedded/svd2rust/blob/master/CHANGELOG.md#unreleased\n[repository]: https://github.com/rust-embedded/svd2rust"]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![no_std]
#![cfg_attr(docsrs, feature(doc_auto_cfg))]
#[doc = r"Number available in the NVIC for configuring priority"]
pub const NVIC_PRIO_BITS: u8 = 3;
#[allow(unused_imports)]
use generic::*;
#[doc = r"Common register and bit access and modify traits"]
pub mod generic;
#[cfg(feature = "rt")]
extern "C" {
    fn POWER_CLOCK();
    fn RADIO();
    fn UARTE0_UART0();
    fn TWIM0_TWIS0_TWI0();
    fn SPIM0_SPIS0_SPI0();
    fn GPIOTE();
    fn SAADC();
    fn TIMER0();
    fn TIMER1();
    fn TIMER2();
    fn RTC0();
    fn TEMP();
    fn RNG();
    fn ECB();
    fn CCM_AAR();
    fn WDT();
    fn RTC1();
    fn QDEC();
    fn COMP();
    fn SWI0_EGU0();
    fn SWI1_EGU1();
    fn SWI2();
    fn SWI3();
    fn SWI4();
    fn SWI5();
    fn PWM0();
    fn PDM();
}
#[doc(hidden)]
#[repr(C)]
pub union Vector {
    _handler: unsafe extern "C" fn(),
    _reserved: u32,
}
#[cfg(feature = "rt")]
#[doc(hidden)]
#[link_section = ".vector_table.interrupts"]
#[no_mangle]
pub static __INTERRUPTS: [Vector; 30] = [
    Vector {
        _handler: POWER_CLOCK,
    },
    Vector { _handler: RADIO },
    Vector {
        _handler: UARTE0_UART0,
    },
    Vector {
        _handler: TWIM0_TWIS0_TWI0,
    },
    Vector {
        _handler: SPIM0_SPIS0_SPI0,
    },
    Vector { _reserved: 0 },
    Vector { _handler: GPIOTE },
    Vector { _handler: SAADC },
    Vector { _handler: TIMER0 },
    Vector { _handler: TIMER1 },
    Vector { _handler: TIMER2 },
    Vector { _handler: RTC0 },
    Vector { _handler: TEMP },
    Vector { _handler: RNG },
    Vector { _handler: ECB },
    Vector { _handler: CCM_AAR },
    Vector { _handler: WDT },
    Vector { _handler: RTC1 },
    Vector { _handler: QDEC },
    Vector { _handler: COMP },
    Vector {
        _handler: SWI0_EGU0,
    },
    Vector {
        _handler: SWI1_EGU1,
    },
    Vector { _handler: SWI2 },
    Vector { _handler: SWI3 },
    Vector { _handler: SWI4 },
    Vector { _handler: SWI5 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: PWM0 },
    Vector { _handler: PDM },
];
#[doc = r"Enumeration of all the interrupts."]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
#[repr(u16)]
pub enum Interrupt {
    #[doc = "0 - POWER_CLOCK"]
    POWER_CLOCK = 0,
    #[doc = "1 - RADIO"]
    RADIO = 1,
    #[doc = "2 - UARTE0_UART0"]
    UARTE0_UART0 = 2,
    #[doc = "3 - TWIM0_TWIS0_TWI0"]
    TWIM0_TWIS0_TWI0 = 3,
    #[doc = "4 - SPIM0_SPIS0_SPI0"]
    SPIM0_SPIS0_SPI0 = 4,
    #[doc = "6 - GPIOTE"]
    GPIOTE = 6,
    #[doc = "7 - SAADC"]
    SAADC = 7,
    #[doc = "8 - TIMER0"]
    TIMER0 = 8,
    #[doc = "9 - TIMER1"]
    TIMER1 = 9,
    #[doc = "10 - TIMER2"]
    TIMER2 = 10,
    #[doc = "11 - RTC0"]
    RTC0 = 11,
    #[doc = "12 - TEMP"]
    TEMP = 12,
    #[doc = "13 - RNG"]
    RNG = 13,
    #[doc = "14 - ECB"]
    ECB = 14,
    #[doc = "15 - CCM_AAR"]
    CCM_AAR = 15,
    #[doc = "16 - WDT"]
    WDT = 16,
    #[doc = "17 - RTC1"]
    RTC1 = 17,
    #[doc = "18 - QDEC"]
    QDEC = 18,
    #[doc = "19 - COMP"]
    COMP = 19,
    #[doc = "20 - SWI0_EGU0"]
    SWI0_EGU0 = 20,
    #[doc = "21 - SWI1_EGU1"]
    SWI1_EGU1 = 21,
    #[doc = "22 - SWI2"]
    SWI2 = 22,
    #[doc = "23 - SWI3"]
    SWI3 = 23,
    #[doc = "24 - SWI4"]
    SWI4 = 24,
    #[doc = "25 - SWI5"]
    SWI5 = 25,
    #[doc = "28 - PWM0"]
    PWM0 = 28,
    #[doc = "29 - PDM"]
    PDM = 29,
}
unsafe impl cortex_m::interrupt::InterruptNumber for Interrupt {
    #[inline(always)]
    fn number(self) -> u16 {
        self as u16
    }
}
#[doc = "Factory information configuration registers"]
pub type Ficr = crate::Periph<ficr::RegisterBlock, 0x1000_0000>;
impl core::fmt::Debug for Ficr {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Ficr").finish()
    }
}
#[doc = "Factory information configuration registers"]
pub mod ficr;
#[doc = "User information configuration registers"]
pub type Uicr = crate::Periph<uicr::RegisterBlock, 0x1000_1000>;
impl core::fmt::Debug for Uicr {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uicr").finish()
    }
}
#[doc = "User information configuration registers"]
pub mod uicr;
#[doc = "Block Protect"]
pub type Bprot = crate::Periph<bprot::RegisterBlock, 0x4000_0000>;
impl core::fmt::Debug for Bprot {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Bprot").finish()
    }
}
#[doc = "Block Protect"]
pub mod bprot;
#[doc = "Only for emulation on devices that support hardened AP-PROTECT."]
pub type Approtect = crate::Periph<approtect::RegisterBlock, 0x4000_0000>;
impl core::fmt::Debug for Approtect {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Approtect").finish()
    }
}
#[doc = "Only for emulation on devices that support hardened AP-PROTECT."]
pub mod approtect;
#[doc = "Clock control"]
pub type Clock = crate::Periph<clock::RegisterBlock, 0x4000_0000>;
impl core::fmt::Debug for Clock {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Clock").finish()
    }
}
#[doc = "Clock control"]
pub mod clock;
#[doc = "Power control"]
pub type Power = crate::Periph<power::RegisterBlock, 0x4000_0000>;
impl core::fmt::Debug for Power {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Power").finish()
    }
}
#[doc = "Power control"]
pub mod power;
#[doc = "GPIO Port"]
pub type P0 = crate::Periph<p0::RegisterBlock, 0x5000_0000>;
impl core::fmt::Debug for P0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("P0").finish()
    }
}
#[doc = "GPIO Port"]
pub mod p0;
#[doc = "2.4 GHz Radio"]
pub type Radio = crate::Periph<radio::RegisterBlock, 0x4000_1000>;
impl core::fmt::Debug for Radio {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Radio").finish()
    }
}
#[doc = "2.4 GHz Radio"]
pub mod radio;
#[doc = "Universal Asynchronous Receiver/Transmitter"]
pub type Uart0 = crate::Periph<uart0::RegisterBlock, 0x4000_2000>;
impl core::fmt::Debug for Uart0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uart0").finish()
    }
}
#[doc = "Universal Asynchronous Receiver/Transmitter"]
pub mod uart0;
#[doc = "UART with EasyDMA"]
pub type Uarte0 = crate::Periph<uarte0::RegisterBlock, 0x4000_2000>;
impl core::fmt::Debug for Uarte0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uarte0").finish()
    }
}
#[doc = "UART with EasyDMA"]
pub mod uarte0;
#[doc = "I2C compatible Two-Wire Interface"]
pub type Twi0 = crate::Periph<twi0::RegisterBlock, 0x4000_3000>;
impl core::fmt::Debug for Twi0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Twi0").finish()
    }
}
#[doc = "I2C compatible Two-Wire Interface"]
pub mod twi0;
#[doc = "I2C compatible Two-Wire Master Interface with EasyDMA"]
pub type Twim0 = crate::Periph<twim0::RegisterBlock, 0x4000_3000>;
impl core::fmt::Debug for Twim0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Twim0").finish()
    }
}
#[doc = "I2C compatible Two-Wire Master Interface with EasyDMA"]
pub mod twim0;
#[doc = "I2C compatible Two-Wire Slave Interface with EasyDMA"]
pub type Twis0 = crate::Periph<twis0::RegisterBlock, 0x4000_3000>;
impl core::fmt::Debug for Twis0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Twis0").finish()
    }
}
#[doc = "I2C compatible Two-Wire Slave Interface with EasyDMA"]
pub mod twis0;
#[doc = "Serial Peripheral Interface"]
pub type Spi0 = crate::Periph<spi0::RegisterBlock, 0x4000_4000>;
impl core::fmt::Debug for Spi0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spi0").finish()
    }
}
#[doc = "Serial Peripheral Interface"]
pub mod spi0;
#[doc = "Serial Peripheral Interface Master with EasyDMA"]
pub type Spim0 = crate::Periph<spim0::RegisterBlock, 0x4000_4000>;
impl core::fmt::Debug for Spim0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spim0").finish()
    }
}
#[doc = "Serial Peripheral Interface Master with EasyDMA"]
pub mod spim0;
#[doc = "SPI Slave"]
pub type Spis0 = crate::Periph<spis0::RegisterBlock, 0x4000_4000>;
impl core::fmt::Debug for Spis0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spis0").finish()
    }
}
#[doc = "SPI Slave"]
pub mod spis0;
#[doc = "GPIO Tasks and Events"]
pub type Gpiote = crate::Periph<gpiote::RegisterBlock, 0x4000_6000>;
impl core::fmt::Debug for Gpiote {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpiote").finish()
    }
}
#[doc = "GPIO Tasks and Events"]
pub mod gpiote;
#[doc = "Analog to Digital Converter"]
pub type Saadc = crate::Periph<saadc::RegisterBlock, 0x4000_7000>;
impl core::fmt::Debug for Saadc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Saadc").finish()
    }
}
#[doc = "Analog to Digital Converter"]
pub mod saadc;
#[doc = "Timer/Counter 0"]
pub type Timer0 = crate::Periph<timer0::RegisterBlock, 0x4000_8000>;
impl core::fmt::Debug for Timer0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timer0").finish()
    }
}
#[doc = "Timer/Counter 0"]
pub mod timer0;
#[doc = "Timer/Counter 1"]
pub type Timer1 = crate::Periph<timer0::RegisterBlock, 0x4000_9000>;
impl core::fmt::Debug for Timer1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timer1").finish()
    }
}
#[doc = "Timer/Counter 1"]
pub use self::timer0 as timer1;
#[doc = "Timer/Counter 2"]
pub type Timer2 = crate::Periph<timer0::RegisterBlock, 0x4000_a000>;
impl core::fmt::Debug for Timer2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timer2").finish()
    }
}
#[doc = "Timer/Counter 2"]
pub use self::timer0 as timer2;
#[doc = "Real time counter 0"]
pub type Rtc0 = crate::Periph<rtc0::RegisterBlock, 0x4000_b000>;
impl core::fmt::Debug for Rtc0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Rtc0").finish()
    }
}
#[doc = "Real time counter 0"]
pub mod rtc0;
#[doc = "Temperature Sensor"]
pub type Temp = crate::Periph<temp::RegisterBlock, 0x4000_c000>;
impl core::fmt::Debug for Temp {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Temp").finish()
    }
}
#[doc = "Temperature Sensor"]
pub mod temp;
#[doc = "Random Number Generator"]
pub type Rng = crate::Periph<rng::RegisterBlock, 0x4000_d000>;
impl core::fmt::Debug for Rng {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Rng").finish()
    }
}
#[doc = "Random Number Generator"]
pub mod rng;
#[doc = "AES ECB Mode Encryption"]
pub type Ecb = crate::Periph<ecb::RegisterBlock, 0x4000_e000>;
impl core::fmt::Debug for Ecb {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Ecb").finish()
    }
}
#[doc = "AES ECB Mode Encryption"]
pub mod ecb;
#[doc = "Accelerated Address Resolver"]
pub type Aar = crate::Periph<aar::RegisterBlock, 0x4000_f000>;
impl core::fmt::Debug for Aar {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Aar").finish()
    }
}
#[doc = "Accelerated Address Resolver"]
pub mod aar;
#[doc = "AES CCM Mode Encryption"]
pub type Ccm = crate::Periph<ccm::RegisterBlock, 0x4000_f000>;
impl core::fmt::Debug for Ccm {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Ccm").finish()
    }
}
#[doc = "AES CCM Mode Encryption"]
pub mod ccm;
#[doc = "Watchdog Timer"]
pub type Wdt = crate::Periph<wdt::RegisterBlock, 0x4001_0000>;
impl core::fmt::Debug for Wdt {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Wdt").finish()
    }
}
#[doc = "Watchdog Timer"]
pub mod wdt;
#[doc = "Real time counter 1"]
pub type Rtc1 = crate::Periph<rtc0::RegisterBlock, 0x4001_1000>;
impl core::fmt::Debug for Rtc1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Rtc1").finish()
    }
}
#[doc = "Real time counter 1"]
pub use self::rtc0 as rtc1;
#[doc = "Quadrature Decoder"]
pub type Qdec = crate::Periph<qdec::RegisterBlock, 0x4001_2000>;
impl core::fmt::Debug for Qdec {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Qdec").finish()
    }
}
#[doc = "Quadrature Decoder"]
pub mod qdec;
#[doc = "Comparator"]
pub type Comp = crate::Periph<comp::RegisterBlock, 0x4001_3000>;
impl core::fmt::Debug for Comp {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Comp").finish()
    }
}
#[doc = "Comparator"]
pub mod comp;
#[doc = "Event Generator Unit 0"]
pub type Egu0 = crate::Periph<egu0::RegisterBlock, 0x4001_4000>;
impl core::fmt::Debug for Egu0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Egu0").finish()
    }
}
#[doc = "Event Generator Unit 0"]
pub mod egu0;
#[doc = "Software interrupt 0"]
pub type Swi0 = crate::Periph<swi0::RegisterBlock, 0x4001_4000>;
impl core::fmt::Debug for Swi0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Swi0").finish()
    }
}
#[doc = "Software interrupt 0"]
pub mod swi0;
#[doc = "Event Generator Unit 1"]
pub type Egu1 = crate::Periph<egu0::RegisterBlock, 0x4001_5000>;
impl core::fmt::Debug for Egu1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Egu1").finish()
    }
}
#[doc = "Event Generator Unit 1"]
pub use self::egu0 as egu1;
#[doc = "Software interrupt 1"]
pub type Swi1 = crate::Periph<swi0::RegisterBlock, 0x4001_5000>;
impl core::fmt::Debug for Swi1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Swi1").finish()
    }
}
#[doc = "Software interrupt 1"]
pub use self::swi0 as swi1;
#[doc = "Software interrupt 2"]
pub type Swi2 = crate::Periph<swi0::RegisterBlock, 0x4001_6000>;
impl core::fmt::Debug for Swi2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Swi2").finish()
    }
}
#[doc = "Software interrupt 2"]
pub use self::swi0 as swi2;
#[doc = "Software interrupt 3"]
pub type Swi3 = crate::Periph<swi0::RegisterBlock, 0x4001_7000>;
impl core::fmt::Debug for Swi3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Swi3").finish()
    }
}
#[doc = "Software interrupt 3"]
pub use self::swi0 as swi3;
#[doc = "Software interrupt 4"]
pub type Swi4 = crate::Periph<swi0::RegisterBlock, 0x4001_8000>;
impl core::fmt::Debug for Swi4 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Swi4").finish()
    }
}
#[doc = "Software interrupt 4"]
pub use self::swi0 as swi4;
#[doc = "Software interrupt 5"]
pub type Swi5 = crate::Periph<swi0::RegisterBlock, 0x4001_9000>;
impl core::fmt::Debug for Swi5 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Swi5").finish()
    }
}
#[doc = "Software interrupt 5"]
pub use self::swi0 as swi5;
#[doc = "Pulse width modulation unit"]
pub type Pwm0 = crate::Periph<pwm0::RegisterBlock, 0x4001_c000>;
impl core::fmt::Debug for Pwm0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pwm0").finish()
    }
}
#[doc = "Pulse width modulation unit"]
pub mod pwm0;
#[doc = "Pulse Density Modulation (Digital Microphone) Interface"]
pub type Pdm = crate::Periph<pdm::RegisterBlock, 0x4001_d000>;
impl core::fmt::Debug for Pdm {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pdm").finish()
    }
}
#[doc = "Pulse Density Modulation (Digital Microphone) Interface"]
pub mod pdm;
#[doc = "Non-volatile memory controller"]
pub type Nvmc = crate::Periph<nvmc::RegisterBlock, 0x4001_e000>;
impl core::fmt::Debug for Nvmc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Nvmc").finish()
    }
}
#[doc = "Non-volatile memory controller"]
pub mod nvmc;
#[doc = "Programmable Peripheral Interconnect"]
pub type Ppi = crate::Periph<ppi::RegisterBlock, 0x4001_f000>;
impl core::fmt::Debug for Ppi {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Ppi").finish()
    }
}
#[doc = "Programmable Peripheral Interconnect"]
pub mod ppi;
#[no_mangle]
static mut DEVICE_PERIPHERALS: bool = false;
#[doc = r" All the peripherals."]
#[allow(non_snake_case)]
pub struct Peripherals {
    #[doc = "FICR"]
    pub ficr: Ficr,
    #[doc = "UICR"]
    pub uicr: Uicr,
    #[doc = "BPROT"]
    pub bprot: Bprot,
    #[doc = "APPROTECT"]
    pub approtect: Approtect,
    #[doc = "CLOCK"]
    pub clock: Clock,
    #[doc = "POWER"]
    pub power: Power,
    #[doc = "P0"]
    pub p0: P0,
    #[doc = "RADIO"]
    pub radio: Radio,
    #[doc = "UART0"]
    pub uart0: Uart0,
    #[doc = "UARTE0"]
    pub uarte0: Uarte0,
    #[doc = "TWI0"]
    pub twi0: Twi0,
    #[doc = "TWIM0"]
    pub twim0: Twim0,
    #[doc = "TWIS0"]
    pub twis0: Twis0,
    #[doc = "SPI0"]
    pub spi0: Spi0,
    #[doc = "SPIM0"]
    pub spim0: Spim0,
    #[doc = "SPIS0"]
    pub spis0: Spis0,
    #[doc = "GPIOTE"]
    pub gpiote: Gpiote,
    #[doc = "SAADC"]
    pub saadc: Saadc,
    #[doc = "TIMER0"]
    pub timer0: Timer0,
    #[doc = "TIMER1"]
    pub timer1: Timer1,
    #[doc = "TIMER2"]
    pub timer2: Timer2,
    #[doc = "RTC0"]
    pub rtc0: Rtc0,
    #[doc = "TEMP"]
    pub temp: Temp,
    #[doc = "RNG"]
    pub rng: Rng,
    #[doc = "ECB"]
    pub ecb: Ecb,
    #[doc = "AAR"]
    pub aar: Aar,
    #[doc = "CCM"]
    pub ccm: Ccm,
    #[doc = "WDT"]
    pub wdt: Wdt,
    #[doc = "RTC1"]
    pub rtc1: Rtc1,
    #[doc = "QDEC"]
    pub qdec: Qdec,
    #[doc = "COMP"]
    pub comp: Comp,
    #[doc = "EGU0"]
    pub egu0: Egu0,
    #[doc = "SWI0"]
    pub swi0: Swi0,
    #[doc = "EGU1"]
    pub egu1: Egu1,
    #[doc = "SWI1"]
    pub swi1: Swi1,
    #[doc = "SWI2"]
    pub swi2: Swi2,
    #[doc = "SWI3"]
    pub swi3: Swi3,
    #[doc = "SWI4"]
    pub swi4: Swi4,
    #[doc = "SWI5"]
    pub swi5: Swi5,
    #[doc = "PWM0"]
    pub pwm0: Pwm0,
    #[doc = "PDM"]
    pub pdm: Pdm,
    #[doc = "NVMC"]
    pub nvmc: Nvmc,
    #[doc = "PPI"]
    pub ppi: Ppi,
}
impl Peripherals {
    #[doc = r" Returns all the peripherals *once*."]
    #[cfg(feature = "critical-section")]
    #[inline]
    pub fn take() -> Option<Self> {
        critical_section::with(|_| {
            if unsafe { DEVICE_PERIPHERALS } {
                return None;
            }
            Some(unsafe { Peripherals::steal() })
        })
    }
    #[doc = r" Unchecked version of `Peripherals::take`."]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Each of the returned peripherals must be used at most once."]
    #[inline]
    pub unsafe fn steal() -> Self {
        DEVICE_PERIPHERALS = true;
        Peripherals {
            ficr: Ficr::steal(),
            uicr: Uicr::steal(),
            bprot: Bprot::steal(),
            approtect: Approtect::steal(),
            clock: Clock::steal(),
            power: Power::steal(),
            p0: P0::steal(),
            radio: Radio::steal(),
            uart0: Uart0::steal(),
            uarte0: Uarte0::steal(),
            twi0: Twi0::steal(),
            twim0: Twim0::steal(),
            twis0: Twis0::steal(),
            spi0: Spi0::steal(),
            spim0: Spim0::steal(),
            spis0: Spis0::steal(),
            gpiote: Gpiote::steal(),
            saadc: Saadc::steal(),
            timer0: Timer0::steal(),
            timer1: Timer1::steal(),
            timer2: Timer2::steal(),
            rtc0: Rtc0::steal(),
            temp: Temp::steal(),
            rng: Rng::steal(),
            ecb: Ecb::steal(),
            aar: Aar::steal(),
            ccm: Ccm::steal(),
            wdt: Wdt::steal(),
            rtc1: Rtc1::steal(),
            qdec: Qdec::steal(),
            comp: Comp::steal(),
            egu0: Egu0::steal(),
            swi0: Swi0::steal(),
            egu1: Egu1::steal(),
            swi1: Swi1::steal(),
            swi2: Swi2::steal(),
            swi3: Swi3::steal(),
            swi4: Swi4::steal(),
            swi5: Swi5::steal(),
            pwm0: Pwm0::steal(),
            pdm: Pdm::steal(),
            nvmc: Nvmc::steal(),
            ppi: Ppi::steal(),
        }
    }
}
