#![doc = "Peripheral access API for NRF9160 microcontrollers (generated using svd2rust v0.37.0 ( ))\n\nYou can find an overview of the generated API [here].\n\nAPI features to be included in the [next] svd2rust release can be generated by cloning the svd2rust [repository], checking out the above commit, and running `cargo doc --open`.\n\n[here]: https://docs.rs/svd2rust/0.37.0/svd2rust/#peripheral-api\n[next]: https://github.com/rust-embedded/svd2rust/blob/master/CHANGELOG.md#unreleased\n[repository]: https://github.com/rust-embedded/svd2rust"]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![no_std]
#![cfg_attr(docsrs, feature(doc_auto_cfg))]
#[doc = r"Number available in the NVIC for configuring priority"]
pub const NVIC_PRIO_BITS: u8 = 3;
#[allow(unused_imports)]
use generic::*;
#[doc = r"Common register and bit access and modify traits"]
pub mod generic;
#[cfg(feature = "rt")]
extern "C" {
    fn SPU();
    fn CLOCK_POWER();
    fn SPIM0_SPIS0_TWIM0_TWIS0_UARTE0();
    fn SPIM1_SPIS1_TWIM1_TWIS1_UARTE1();
    fn SPIM2_SPIS2_TWIM2_TWIS2_UARTE2();
    fn SPIM3_SPIS3_TWIM3_TWIS3_UARTE3();
    fn GPIOTE0();
    fn SAADC();
    fn TIMER0();
    fn TIMER1();
    fn TIMER2();
    fn RTC0();
    fn RTC1();
    fn WDT();
    fn EGU0();
    fn EGU1();
    fn EGU2();
    fn EGU3();
    fn EGU4();
    fn EGU5();
    fn PWM0();
    fn PWM1();
    fn PWM2();
    fn PWM3();
    fn PDM();
    fn I2S();
    fn IPC();
    fn FPU();
    fn GPIOTE1();
    fn KMU();
    fn CRYPTOCELL();
}
#[doc(hidden)]
#[repr(C)]
pub union Vector {
    _handler: unsafe extern "C" fn(),
    _reserved: u32,
}
#[cfg(feature = "rt")]
#[doc(hidden)]
#[link_section = ".vector_table.interrupts"]
#[no_mangle]
pub static __INTERRUPTS: [Vector; 65] = [
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: SPU },
    Vector { _reserved: 0 },
    Vector {
        _handler: CLOCK_POWER,
    },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector {
        _handler: SPIM0_SPIS0_TWIM0_TWIS0_UARTE0,
    },
    Vector {
        _handler: SPIM1_SPIS1_TWIM1_TWIS1_UARTE1,
    },
    Vector {
        _handler: SPIM2_SPIS2_TWIM2_TWIS2_UARTE2,
    },
    Vector {
        _handler: SPIM3_SPIS3_TWIM3_TWIS3_UARTE3,
    },
    Vector { _reserved: 0 },
    Vector { _handler: GPIOTE0 },
    Vector { _handler: SAADC },
    Vector { _handler: TIMER0 },
    Vector { _handler: TIMER1 },
    Vector { _handler: TIMER2 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: RTC0 },
    Vector { _handler: RTC1 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: WDT },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: EGU0 },
    Vector { _handler: EGU1 },
    Vector { _handler: EGU2 },
    Vector { _handler: EGU3 },
    Vector { _handler: EGU4 },
    Vector { _handler: EGU5 },
    Vector { _handler: PWM0 },
    Vector { _handler: PWM1 },
    Vector { _handler: PWM2 },
    Vector { _handler: PWM3 },
    Vector { _reserved: 0 },
    Vector { _handler: PDM },
    Vector { _reserved: 0 },
    Vector { _handler: I2S },
    Vector { _reserved: 0 },
    Vector { _handler: IPC },
    Vector { _reserved: 0 },
    Vector { _handler: FPU },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: GPIOTE1 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: KMU },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector {
        _handler: CRYPTOCELL,
    },
];
#[doc = r"Enumeration of all the interrupts."]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
#[repr(u16)]
pub enum Interrupt {
    #[doc = "3 - SPU"]
    SPU = 3,
    #[doc = "5 - CLOCK_POWER"]
    CLOCK_POWER = 5,
    #[doc = "8 - SPIM0_SPIS0_TWIM0_TWIS0_UARTE0"]
    SPIM0_SPIS0_TWIM0_TWIS0_UARTE0 = 8,
    #[doc = "9 - SPIM1_SPIS1_TWIM1_TWIS1_UARTE1"]
    SPIM1_SPIS1_TWIM1_TWIS1_UARTE1 = 9,
    #[doc = "10 - SPIM2_SPIS2_TWIM2_TWIS2_UARTE2"]
    SPIM2_SPIS2_TWIM2_TWIS2_UARTE2 = 10,
    #[doc = "11 - SPIM3_SPIS3_TWIM3_TWIS3_UARTE3"]
    SPIM3_SPIS3_TWIM3_TWIS3_UARTE3 = 11,
    #[doc = "13 - GPIOTE0"]
    GPIOTE0 = 13,
    #[doc = "14 - SAADC"]
    SAADC = 14,
    #[doc = "15 - TIMER0"]
    TIMER0 = 15,
    #[doc = "16 - TIMER1"]
    TIMER1 = 16,
    #[doc = "17 - TIMER2"]
    TIMER2 = 17,
    #[doc = "20 - RTC0"]
    RTC0 = 20,
    #[doc = "21 - RTC1"]
    RTC1 = 21,
    #[doc = "24 - WDT"]
    WDT = 24,
    #[doc = "27 - EGU0"]
    EGU0 = 27,
    #[doc = "28 - EGU1"]
    EGU1 = 28,
    #[doc = "29 - EGU2"]
    EGU2 = 29,
    #[doc = "30 - EGU3"]
    EGU3 = 30,
    #[doc = "31 - EGU4"]
    EGU4 = 31,
    #[doc = "32 - EGU5"]
    EGU5 = 32,
    #[doc = "33 - PWM0"]
    PWM0 = 33,
    #[doc = "34 - PWM1"]
    PWM1 = 34,
    #[doc = "35 - PWM2"]
    PWM2 = 35,
    #[doc = "36 - PWM3"]
    PWM3 = 36,
    #[doc = "38 - PDM"]
    PDM = 38,
    #[doc = "40 - I2S"]
    I2S = 40,
    #[doc = "42 - IPC"]
    IPC = 42,
    #[doc = "44 - FPU"]
    FPU = 44,
    #[doc = "49 - GPIOTE1"]
    GPIOTE1 = 49,
    #[doc = "57 - KMU"]
    KMU = 57,
    #[doc = "64 - CRYPTOCELL"]
    CRYPTOCELL = 64,
}
unsafe impl cortex_m::interrupt::InterruptNumber for Interrupt {
    #[inline(always)]
    fn number(self) -> u16 {
        self as u16
    }
}
#[doc = "Factory Information Configuration Registers"]
pub type FicrS = crate::Periph<ficr_s::RegisterBlock, 0x00ff_0000>;
impl core::fmt::Debug for FicrS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("FicrS").finish()
    }
}
#[doc = "Factory Information Configuration Registers"]
pub mod ficr_s;
#[doc = "User information configuration registers User information configuration registers"]
pub type UicrS = crate::Periph<uicr_s::RegisterBlock, 0x00ff_8000>;
impl core::fmt::Debug for UicrS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("UicrS").finish()
    }
}
#[doc = "User information configuration registers User information configuration registers"]
pub mod uicr_s;
#[doc = "Embedded Trace Macrocell"]
pub type EtmNs = crate::Periph<etm_ns::RegisterBlock, 0xe004_1000>;
impl core::fmt::Debug for EtmNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("EtmNs").finish()
    }
}
#[doc = "Embedded Trace Macrocell"]
pub mod etm_ns;
#[doc = "Embedded Trace Buffer"]
pub type EtbNs = crate::Periph<etb_ns::RegisterBlock, 0xe005_1000>;
impl core::fmt::Debug for EtbNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("EtbNs").finish()
    }
}
#[doc = "Embedded Trace Buffer"]
pub mod etb_ns;
#[doc = "Trace Port Interface Unit"]
pub type TpiuNs = crate::Periph<tpiu_ns::RegisterBlock, 0xe005_4000>;
impl core::fmt::Debug for TpiuNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("TpiuNs").finish()
    }
}
#[doc = "Trace Port Interface Unit"]
pub mod tpiu_ns;
#[doc = "ATB Replicator module"]
pub type AtbreplicatorNs = crate::Periph<atbreplicator_ns::RegisterBlock, 0xe005_8000>;
impl core::fmt::Debug for AtbreplicatorNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("AtbreplicatorNs").finish()
    }
}
#[doc = "ATB Replicator module"]
pub mod atbreplicator_ns;
#[doc = "ATB funnel module 0"]
pub type Atbfunnel1Ns = crate::Periph<atbfunnel1_ns::RegisterBlock, 0xe005_a000>;
impl core::fmt::Debug for Atbfunnel1Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Atbfunnel1Ns").finish()
    }
}
#[doc = "ATB funnel module 0"]
pub mod atbfunnel1_ns;
#[doc = "ATB funnel module 1"]
pub type Atbfunnel2Ns = crate::Periph<atbfunnel1_ns::RegisterBlock, 0xe005_b000>;
impl core::fmt::Debug for Atbfunnel2Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Atbfunnel2Ns").finish()
    }
}
#[doc = "ATB funnel module 1"]
pub use self::atbfunnel1_ns as atbfunnel2_ns;
#[doc = "Trace and debug control"]
pub type TadS = crate::Periph<tad_s::RegisterBlock, 0xe008_0000>;
impl core::fmt::Debug for TadS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("TadS").finish()
    }
}
#[doc = "Trace and debug control"]
pub mod tad_s;
#[doc = "System protection unit"]
pub type SpuS = crate::Periph<spu_s::RegisterBlock, 0x5000_3000>;
impl core::fmt::Debug for SpuS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SpuS").finish()
    }
}
#[doc = "System protection unit"]
pub mod spu_s;
#[doc = "Voltage regulators control 0"]
pub type RegulatorsNs = crate::Periph<regulators_ns::RegisterBlock, 0x4000_4000>;
impl core::fmt::Debug for RegulatorsNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("RegulatorsNs").finish()
    }
}
#[doc = "Voltage regulators control 0"]
pub mod regulators_ns;
#[doc = "Voltage regulators control 1"]
pub type RegulatorsS = crate::Periph<regulators_ns::RegisterBlock, 0x5000_4000>;
impl core::fmt::Debug for RegulatorsS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("RegulatorsS").finish()
    }
}
#[doc = "Voltage regulators control 1"]
pub use self::regulators_ns as regulators_s;
#[doc = "Clock management 0"]
pub type ClockNs = crate::Periph<clock_ns::RegisterBlock, 0x4000_5000>;
impl core::fmt::Debug for ClockNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("ClockNs").finish()
    }
}
#[doc = "Clock management 0"]
pub mod clock_ns;
#[doc = "Power control 0"]
pub type PowerNs = crate::Periph<power_ns::RegisterBlock, 0x4000_5000>;
impl core::fmt::Debug for PowerNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("PowerNs").finish()
    }
}
#[doc = "Power control 0"]
pub mod power_ns;
#[doc = "Clock management 1"]
pub type ClockS = crate::Periph<clock_ns::RegisterBlock, 0x5000_5000>;
impl core::fmt::Debug for ClockS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("ClockS").finish()
    }
}
#[doc = "Clock management 1"]
pub use self::clock_ns as clock_s;
#[doc = "Power control 1"]
pub type PowerS = crate::Periph<power_ns::RegisterBlock, 0x5000_5000>;
impl core::fmt::Debug for PowerS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("PowerS").finish()
    }
}
#[doc = "Power control 1"]
pub use self::power_ns as power_s;
#[doc = "Control access port"]
pub type CtrlApPeriS = crate::Periph<ctrl_ap_peri_s::RegisterBlock, 0x5000_6000>;
impl core::fmt::Debug for CtrlApPeriS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("CtrlApPeriS").finish()
    }
}
#[doc = "Control access port"]
pub mod ctrl_ap_peri_s;
#[doc = "Serial Peripheral Interface Master with EasyDMA 0"]
pub type Spim0Ns = crate::Periph<spim0_ns::RegisterBlock, 0x4000_8000>;
impl core::fmt::Debug for Spim0Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spim0Ns").finish()
    }
}
#[doc = "Serial Peripheral Interface Master with EasyDMA 0"]
pub mod spim0_ns;
#[doc = "SPI Slave 0"]
pub type Spis0Ns = crate::Periph<spis0_ns::RegisterBlock, 0x4000_8000>;
impl core::fmt::Debug for Spis0Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spis0Ns").finish()
    }
}
#[doc = "SPI Slave 0"]
pub mod spis0_ns;
#[doc = "I2C compatible Two-Wire Master Interface with EasyDMA 0"]
pub type Twim0Ns = crate::Periph<twim0_ns::RegisterBlock, 0x4000_8000>;
impl core::fmt::Debug for Twim0Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Twim0Ns").finish()
    }
}
#[doc = "I2C compatible Two-Wire Master Interface with EasyDMA 0"]
pub mod twim0_ns;
#[doc = "I2C compatible Two-Wire Slave Interface with EasyDMA 0"]
pub type Twis0Ns = crate::Periph<twis0_ns::RegisterBlock, 0x4000_8000>;
impl core::fmt::Debug for Twis0Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Twis0Ns").finish()
    }
}
#[doc = "I2C compatible Two-Wire Slave Interface with EasyDMA 0"]
pub mod twis0_ns;
#[doc = "UART with EasyDMA 0"]
pub type Uarte0Ns = crate::Periph<uarte0_ns::RegisterBlock, 0x4000_8000>;
impl core::fmt::Debug for Uarte0Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uarte0Ns").finish()
    }
}
#[doc = "UART with EasyDMA 0"]
pub mod uarte0_ns;
#[doc = "Serial Peripheral Interface Master with EasyDMA 1"]
pub type Spim0S = crate::Periph<spim0_ns::RegisterBlock, 0x5000_8000>;
impl core::fmt::Debug for Spim0S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spim0S").finish()
    }
}
#[doc = "Serial Peripheral Interface Master with EasyDMA 1"]
pub use self::spim0_ns as spim0_s;
#[doc = "SPI Slave 1"]
pub type Spis0S = crate::Periph<spis0_ns::RegisterBlock, 0x5000_8000>;
impl core::fmt::Debug for Spis0S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spis0S").finish()
    }
}
#[doc = "SPI Slave 1"]
pub use self::spis0_ns as spis0_s;
#[doc = "I2C compatible Two-Wire Master Interface with EasyDMA 1"]
pub type Twim0S = crate::Periph<twim0_ns::RegisterBlock, 0x5000_8000>;
impl core::fmt::Debug for Twim0S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Twim0S").finish()
    }
}
#[doc = "I2C compatible Two-Wire Master Interface with EasyDMA 1"]
pub use self::twim0_ns as twim0_s;
#[doc = "I2C compatible Two-Wire Slave Interface with EasyDMA 1"]
pub type Twis0S = crate::Periph<twis0_ns::RegisterBlock, 0x5000_8000>;
impl core::fmt::Debug for Twis0S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Twis0S").finish()
    }
}
#[doc = "I2C compatible Two-Wire Slave Interface with EasyDMA 1"]
pub use self::twis0_ns as twis0_s;
#[doc = "UART with EasyDMA 1"]
pub type Uarte0S = crate::Periph<uarte0_ns::RegisterBlock, 0x5000_8000>;
impl core::fmt::Debug for Uarte0S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uarte0S").finish()
    }
}
#[doc = "UART with EasyDMA 1"]
pub use self::uarte0_ns as uarte0_s;
#[doc = "Serial Peripheral Interface Master with EasyDMA 2"]
pub type Spim1Ns = crate::Periph<spim0_ns::RegisterBlock, 0x4000_9000>;
impl core::fmt::Debug for Spim1Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spim1Ns").finish()
    }
}
#[doc = "Serial Peripheral Interface Master with EasyDMA 2"]
pub use self::spim0_ns as spim1_ns;
#[doc = "SPI Slave 2"]
pub type Spis1Ns = crate::Periph<spis0_ns::RegisterBlock, 0x4000_9000>;
impl core::fmt::Debug for Spis1Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spis1Ns").finish()
    }
}
#[doc = "SPI Slave 2"]
pub use self::spis0_ns as spis1_ns;
#[doc = "I2C compatible Two-Wire Master Interface with EasyDMA 2"]
pub type Twim1Ns = crate::Periph<twim0_ns::RegisterBlock, 0x4000_9000>;
impl core::fmt::Debug for Twim1Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Twim1Ns").finish()
    }
}
#[doc = "I2C compatible Two-Wire Master Interface with EasyDMA 2"]
pub use self::twim0_ns as twim1_ns;
#[doc = "I2C compatible Two-Wire Slave Interface with EasyDMA 2"]
pub type Twis1Ns = crate::Periph<twis0_ns::RegisterBlock, 0x4000_9000>;
impl core::fmt::Debug for Twis1Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Twis1Ns").finish()
    }
}
#[doc = "I2C compatible Two-Wire Slave Interface with EasyDMA 2"]
pub use self::twis0_ns as twis1_ns;
#[doc = "UART with EasyDMA 2"]
pub type Uarte1Ns = crate::Periph<uarte0_ns::RegisterBlock, 0x4000_9000>;
impl core::fmt::Debug for Uarte1Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uarte1Ns").finish()
    }
}
#[doc = "UART with EasyDMA 2"]
pub use self::uarte0_ns as uarte1_ns;
#[doc = "Serial Peripheral Interface Master with EasyDMA 3"]
pub type Spim1S = crate::Periph<spim0_ns::RegisterBlock, 0x5000_9000>;
impl core::fmt::Debug for Spim1S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spim1S").finish()
    }
}
#[doc = "Serial Peripheral Interface Master with EasyDMA 3"]
pub use self::spim0_ns as spim1_s;
#[doc = "SPI Slave 3"]
pub type Spis1S = crate::Periph<spis0_ns::RegisterBlock, 0x5000_9000>;
impl core::fmt::Debug for Spis1S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spis1S").finish()
    }
}
#[doc = "SPI Slave 3"]
pub use self::spis0_ns as spis1_s;
#[doc = "I2C compatible Two-Wire Master Interface with EasyDMA 3"]
pub type Twim1S = crate::Periph<twim0_ns::RegisterBlock, 0x5000_9000>;
impl core::fmt::Debug for Twim1S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Twim1S").finish()
    }
}
#[doc = "I2C compatible Two-Wire Master Interface with EasyDMA 3"]
pub use self::twim0_ns as twim1_s;
#[doc = "I2C compatible Two-Wire Slave Interface with EasyDMA 3"]
pub type Twis1S = crate::Periph<twis0_ns::RegisterBlock, 0x5000_9000>;
impl core::fmt::Debug for Twis1S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Twis1S").finish()
    }
}
#[doc = "I2C compatible Two-Wire Slave Interface with EasyDMA 3"]
pub use self::twis0_ns as twis1_s;
#[doc = "UART with EasyDMA 3"]
pub type Uarte1S = crate::Periph<uarte0_ns::RegisterBlock, 0x5000_9000>;
impl core::fmt::Debug for Uarte1S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uarte1S").finish()
    }
}
#[doc = "UART with EasyDMA 3"]
pub use self::uarte0_ns as uarte1_s;
#[doc = "Serial Peripheral Interface Master with EasyDMA 4"]
pub type Spim2Ns = crate::Periph<spim0_ns::RegisterBlock, 0x4000_a000>;
impl core::fmt::Debug for Spim2Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spim2Ns").finish()
    }
}
#[doc = "Serial Peripheral Interface Master with EasyDMA 4"]
pub use self::spim0_ns as spim2_ns;
#[doc = "SPI Slave 4"]
pub type Spis2Ns = crate::Periph<spis0_ns::RegisterBlock, 0x4000_a000>;
impl core::fmt::Debug for Spis2Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spis2Ns").finish()
    }
}
#[doc = "SPI Slave 4"]
pub use self::spis0_ns as spis2_ns;
#[doc = "I2C compatible Two-Wire Master Interface with EasyDMA 4"]
pub type Twim2Ns = crate::Periph<twim0_ns::RegisterBlock, 0x4000_a000>;
impl core::fmt::Debug for Twim2Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Twim2Ns").finish()
    }
}
#[doc = "I2C compatible Two-Wire Master Interface with EasyDMA 4"]
pub use self::twim0_ns as twim2_ns;
#[doc = "I2C compatible Two-Wire Slave Interface with EasyDMA 4"]
pub type Twis2Ns = crate::Periph<twis0_ns::RegisterBlock, 0x4000_a000>;
impl core::fmt::Debug for Twis2Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Twis2Ns").finish()
    }
}
#[doc = "I2C compatible Two-Wire Slave Interface with EasyDMA 4"]
pub use self::twis0_ns as twis2_ns;
#[doc = "UART with EasyDMA 4"]
pub type Uarte2Ns = crate::Periph<uarte0_ns::RegisterBlock, 0x4000_a000>;
impl core::fmt::Debug for Uarte2Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uarte2Ns").finish()
    }
}
#[doc = "UART with EasyDMA 4"]
pub use self::uarte0_ns as uarte2_ns;
#[doc = "Serial Peripheral Interface Master with EasyDMA 5"]
pub type Spim2S = crate::Periph<spim0_ns::RegisterBlock, 0x5000_a000>;
impl core::fmt::Debug for Spim2S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spim2S").finish()
    }
}
#[doc = "Serial Peripheral Interface Master with EasyDMA 5"]
pub use self::spim0_ns as spim2_s;
#[doc = "SPI Slave 5"]
pub type Spis2S = crate::Periph<spis0_ns::RegisterBlock, 0x5000_a000>;
impl core::fmt::Debug for Spis2S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spis2S").finish()
    }
}
#[doc = "SPI Slave 5"]
pub use self::spis0_ns as spis2_s;
#[doc = "I2C compatible Two-Wire Master Interface with EasyDMA 5"]
pub type Twim2S = crate::Periph<twim0_ns::RegisterBlock, 0x5000_a000>;
impl core::fmt::Debug for Twim2S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Twim2S").finish()
    }
}
#[doc = "I2C compatible Two-Wire Master Interface with EasyDMA 5"]
pub use self::twim0_ns as twim2_s;
#[doc = "I2C compatible Two-Wire Slave Interface with EasyDMA 5"]
pub type Twis2S = crate::Periph<twis0_ns::RegisterBlock, 0x5000_a000>;
impl core::fmt::Debug for Twis2S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Twis2S").finish()
    }
}
#[doc = "I2C compatible Two-Wire Slave Interface with EasyDMA 5"]
pub use self::twis0_ns as twis2_s;
#[doc = "UART with EasyDMA 5"]
pub type Uarte2S = crate::Periph<uarte0_ns::RegisterBlock, 0x5000_a000>;
impl core::fmt::Debug for Uarte2S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uarte2S").finish()
    }
}
#[doc = "UART with EasyDMA 5"]
pub use self::uarte0_ns as uarte2_s;
#[doc = "Serial Peripheral Interface Master with EasyDMA 6"]
pub type Spim3Ns = crate::Periph<spim0_ns::RegisterBlock, 0x4000_b000>;
impl core::fmt::Debug for Spim3Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spim3Ns").finish()
    }
}
#[doc = "Serial Peripheral Interface Master with EasyDMA 6"]
pub use self::spim0_ns as spim3_ns;
#[doc = "SPI Slave 6"]
pub type Spis3Ns = crate::Periph<spis0_ns::RegisterBlock, 0x4000_b000>;
impl core::fmt::Debug for Spis3Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spis3Ns").finish()
    }
}
#[doc = "SPI Slave 6"]
pub use self::spis0_ns as spis3_ns;
#[doc = "I2C compatible Two-Wire Master Interface with EasyDMA 6"]
pub type Twim3Ns = crate::Periph<twim0_ns::RegisterBlock, 0x4000_b000>;
impl core::fmt::Debug for Twim3Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Twim3Ns").finish()
    }
}
#[doc = "I2C compatible Two-Wire Master Interface with EasyDMA 6"]
pub use self::twim0_ns as twim3_ns;
#[doc = "I2C compatible Two-Wire Slave Interface with EasyDMA 6"]
pub type Twis3Ns = crate::Periph<twis0_ns::RegisterBlock, 0x4000_b000>;
impl core::fmt::Debug for Twis3Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Twis3Ns").finish()
    }
}
#[doc = "I2C compatible Two-Wire Slave Interface with EasyDMA 6"]
pub use self::twis0_ns as twis3_ns;
#[doc = "UART with EasyDMA 6"]
pub type Uarte3Ns = crate::Periph<uarte0_ns::RegisterBlock, 0x4000_b000>;
impl core::fmt::Debug for Uarte3Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uarte3Ns").finish()
    }
}
#[doc = "UART with EasyDMA 6"]
pub use self::uarte0_ns as uarte3_ns;
#[doc = "Serial Peripheral Interface Master with EasyDMA 7"]
pub type Spim3S = crate::Periph<spim0_ns::RegisterBlock, 0x5000_b000>;
impl core::fmt::Debug for Spim3S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spim3S").finish()
    }
}
#[doc = "Serial Peripheral Interface Master with EasyDMA 7"]
pub use self::spim0_ns as spim3_s;
#[doc = "SPI Slave 7"]
pub type Spis3S = crate::Periph<spis0_ns::RegisterBlock, 0x5000_b000>;
impl core::fmt::Debug for Spis3S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spis3S").finish()
    }
}
#[doc = "SPI Slave 7"]
pub use self::spis0_ns as spis3_s;
#[doc = "I2C compatible Two-Wire Master Interface with EasyDMA 7"]
pub type Twim3S = crate::Periph<twim0_ns::RegisterBlock, 0x5000_b000>;
impl core::fmt::Debug for Twim3S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Twim3S").finish()
    }
}
#[doc = "I2C compatible Two-Wire Master Interface with EasyDMA 7"]
pub use self::twim0_ns as twim3_s;
#[doc = "I2C compatible Two-Wire Slave Interface with EasyDMA 7"]
pub type Twis3S = crate::Periph<twis0_ns::RegisterBlock, 0x5000_b000>;
impl core::fmt::Debug for Twis3S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Twis3S").finish()
    }
}
#[doc = "I2C compatible Two-Wire Slave Interface with EasyDMA 7"]
pub use self::twis0_ns as twis3_s;
#[doc = "UART with EasyDMA 7"]
pub type Uarte3S = crate::Periph<uarte0_ns::RegisterBlock, 0x5000_b000>;
impl core::fmt::Debug for Uarte3S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uarte3S").finish()
    }
}
#[doc = "UART with EasyDMA 7"]
pub use self::uarte0_ns as uarte3_s;
#[doc = "GPIO Tasks and Events 0"]
pub type Gpiote0S = crate::Periph<gpiote0_s::RegisterBlock, 0x5000_d000>;
impl core::fmt::Debug for Gpiote0S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpiote0S").finish()
    }
}
#[doc = "GPIO Tasks and Events 0"]
pub mod gpiote0_s;
#[doc = "Analog to Digital Converter 0"]
pub type SaadcNs = crate::Periph<saadc_ns::RegisterBlock, 0x4000_e000>;
impl core::fmt::Debug for SaadcNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SaadcNs").finish()
    }
}
#[doc = "Analog to Digital Converter 0"]
pub mod saadc_ns;
#[doc = "Analog to Digital Converter 1"]
pub type SaadcS = crate::Periph<saadc_ns::RegisterBlock, 0x5000_e000>;
impl core::fmt::Debug for SaadcS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SaadcS").finish()
    }
}
#[doc = "Analog to Digital Converter 1"]
pub use self::saadc_ns as saadc_s;
#[doc = "Timer/Counter 0"]
pub type Timer0Ns = crate::Periph<timer0_ns::RegisterBlock, 0x4000_f000>;
impl core::fmt::Debug for Timer0Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timer0Ns").finish()
    }
}
#[doc = "Timer/Counter 0"]
pub mod timer0_ns;
#[doc = "Timer/Counter 1"]
pub type Timer0S = crate::Periph<timer0_ns::RegisterBlock, 0x5000_f000>;
impl core::fmt::Debug for Timer0S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timer0S").finish()
    }
}
#[doc = "Timer/Counter 1"]
pub use self::timer0_ns as timer0_s;
#[doc = "Timer/Counter 2"]
pub type Timer1Ns = crate::Periph<timer0_ns::RegisterBlock, 0x4001_0000>;
impl core::fmt::Debug for Timer1Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timer1Ns").finish()
    }
}
#[doc = "Timer/Counter 2"]
pub use self::timer0_ns as timer1_ns;
#[doc = "Timer/Counter 3"]
pub type Timer1S = crate::Periph<timer0_ns::RegisterBlock, 0x5001_0000>;
impl core::fmt::Debug for Timer1S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timer1S").finish()
    }
}
#[doc = "Timer/Counter 3"]
pub use self::timer0_ns as timer1_s;
#[doc = "Timer/Counter 4"]
pub type Timer2Ns = crate::Periph<timer0_ns::RegisterBlock, 0x4001_1000>;
impl core::fmt::Debug for Timer2Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timer2Ns").finish()
    }
}
#[doc = "Timer/Counter 4"]
pub use self::timer0_ns as timer2_ns;
#[doc = "Timer/Counter 5"]
pub type Timer2S = crate::Periph<timer0_ns::RegisterBlock, 0x5001_1000>;
impl core::fmt::Debug for Timer2S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timer2S").finish()
    }
}
#[doc = "Timer/Counter 5"]
pub use self::timer0_ns as timer2_s;
#[doc = "Real-time counter 0"]
pub type Rtc0Ns = crate::Periph<rtc0_ns::RegisterBlock, 0x4001_4000>;
impl core::fmt::Debug for Rtc0Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Rtc0Ns").finish()
    }
}
#[doc = "Real-time counter 0"]
pub mod rtc0_ns;
#[doc = "Real-time counter 1"]
pub type Rtc0S = crate::Periph<rtc0_ns::RegisterBlock, 0x5001_4000>;
impl core::fmt::Debug for Rtc0S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Rtc0S").finish()
    }
}
#[doc = "Real-time counter 1"]
pub use self::rtc0_ns as rtc0_s;
#[doc = "Real-time counter 2"]
pub type Rtc1Ns = crate::Periph<rtc0_ns::RegisterBlock, 0x4001_5000>;
impl core::fmt::Debug for Rtc1Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Rtc1Ns").finish()
    }
}
#[doc = "Real-time counter 2"]
pub use self::rtc0_ns as rtc1_ns;
#[doc = "Real-time counter 3"]
pub type Rtc1S = crate::Periph<rtc0_ns::RegisterBlock, 0x5001_5000>;
impl core::fmt::Debug for Rtc1S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Rtc1S").finish()
    }
}
#[doc = "Real-time counter 3"]
pub use self::rtc0_ns as rtc1_s;
#[doc = "Distributed programmable peripheral interconnect controller 0"]
pub type DppicNs = crate::Periph<dppic_ns::RegisterBlock, 0x4001_7000>;
impl core::fmt::Debug for DppicNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("DppicNs").finish()
    }
}
#[doc = "Distributed programmable peripheral interconnect controller 0"]
pub mod dppic_ns;
#[doc = "Distributed programmable peripheral interconnect controller 1"]
pub type DppicS = crate::Periph<dppic_ns::RegisterBlock, 0x5001_7000>;
impl core::fmt::Debug for DppicS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("DppicS").finish()
    }
}
#[doc = "Distributed programmable peripheral interconnect controller 1"]
pub use self::dppic_ns as dppic_s;
#[doc = "Watchdog Timer 0"]
pub type WdtNs = crate::Periph<wdt_ns::RegisterBlock, 0x4001_8000>;
impl core::fmt::Debug for WdtNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("WdtNs").finish()
    }
}
#[doc = "Watchdog Timer 0"]
pub mod wdt_ns;
#[doc = "Watchdog Timer 1"]
pub type WdtS = crate::Periph<wdt_ns::RegisterBlock, 0x5001_8000>;
impl core::fmt::Debug for WdtS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("WdtS").finish()
    }
}
#[doc = "Watchdog Timer 1"]
pub use self::wdt_ns as wdt_s;
#[doc = "Event generator unit 0"]
pub type Egu0Ns = crate::Periph<egu0_ns::RegisterBlock, 0x4001_b000>;
impl core::fmt::Debug for Egu0Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Egu0Ns").finish()
    }
}
#[doc = "Event generator unit 0"]
pub mod egu0_ns;
#[doc = "Event generator unit 1"]
pub type Egu0S = crate::Periph<egu0_ns::RegisterBlock, 0x5001_b000>;
impl core::fmt::Debug for Egu0S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Egu0S").finish()
    }
}
#[doc = "Event generator unit 1"]
pub use self::egu0_ns as egu0_s;
#[doc = "Event generator unit 2"]
pub type Egu1Ns = crate::Periph<egu0_ns::RegisterBlock, 0x4001_c000>;
impl core::fmt::Debug for Egu1Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Egu1Ns").finish()
    }
}
#[doc = "Event generator unit 2"]
pub use self::egu0_ns as egu1_ns;
#[doc = "Event generator unit 3"]
pub type Egu1S = crate::Periph<egu0_ns::RegisterBlock, 0x5001_c000>;
impl core::fmt::Debug for Egu1S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Egu1S").finish()
    }
}
#[doc = "Event generator unit 3"]
pub use self::egu0_ns as egu1_s;
#[doc = "Event generator unit 4"]
pub type Egu2Ns = crate::Periph<egu0_ns::RegisterBlock, 0x4001_d000>;
impl core::fmt::Debug for Egu2Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Egu2Ns").finish()
    }
}
#[doc = "Event generator unit 4"]
pub use self::egu0_ns as egu2_ns;
#[doc = "Event generator unit 5"]
pub type Egu2S = crate::Periph<egu0_ns::RegisterBlock, 0x5001_d000>;
impl core::fmt::Debug for Egu2S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Egu2S").finish()
    }
}
#[doc = "Event generator unit 5"]
pub use self::egu0_ns as egu2_s;
#[doc = "Event generator unit 6"]
pub type Egu3Ns = crate::Periph<egu0_ns::RegisterBlock, 0x4001_e000>;
impl core::fmt::Debug for Egu3Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Egu3Ns").finish()
    }
}
#[doc = "Event generator unit 6"]
pub use self::egu0_ns as egu3_ns;
#[doc = "Event generator unit 7"]
pub type Egu3S = crate::Periph<egu0_ns::RegisterBlock, 0x5001_e000>;
impl core::fmt::Debug for Egu3S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Egu3S").finish()
    }
}
#[doc = "Event generator unit 7"]
pub use self::egu0_ns as egu3_s;
#[doc = "Event generator unit 8"]
pub type Egu4Ns = crate::Periph<egu0_ns::RegisterBlock, 0x4001_f000>;
impl core::fmt::Debug for Egu4Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Egu4Ns").finish()
    }
}
#[doc = "Event generator unit 8"]
pub use self::egu0_ns as egu4_ns;
#[doc = "Event generator unit 9"]
pub type Egu4S = crate::Periph<egu0_ns::RegisterBlock, 0x5001_f000>;
impl core::fmt::Debug for Egu4S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Egu4S").finish()
    }
}
#[doc = "Event generator unit 9"]
pub use self::egu0_ns as egu4_s;
#[doc = "Event generator unit 10"]
pub type Egu5Ns = crate::Periph<egu0_ns::RegisterBlock, 0x4002_0000>;
impl core::fmt::Debug for Egu5Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Egu5Ns").finish()
    }
}
#[doc = "Event generator unit 10"]
pub use self::egu0_ns as egu5_ns;
#[doc = "Event generator unit 11"]
pub type Egu5S = crate::Periph<egu0_ns::RegisterBlock, 0x5002_0000>;
impl core::fmt::Debug for Egu5S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Egu5S").finish()
    }
}
#[doc = "Event generator unit 11"]
pub use self::egu0_ns as egu5_s;
#[doc = "Pulse width modulation unit 0"]
pub type Pwm0Ns = crate::Periph<pwm0_ns::RegisterBlock, 0x4002_1000>;
impl core::fmt::Debug for Pwm0Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pwm0Ns").finish()
    }
}
#[doc = "Pulse width modulation unit 0"]
pub mod pwm0_ns;
#[doc = "Pulse width modulation unit 1"]
pub type Pwm0S = crate::Periph<pwm0_ns::RegisterBlock, 0x5002_1000>;
impl core::fmt::Debug for Pwm0S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pwm0S").finish()
    }
}
#[doc = "Pulse width modulation unit 1"]
pub use self::pwm0_ns as pwm0_s;
#[doc = "Pulse width modulation unit 2"]
pub type Pwm1Ns = crate::Periph<pwm0_ns::RegisterBlock, 0x4002_2000>;
impl core::fmt::Debug for Pwm1Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pwm1Ns").finish()
    }
}
#[doc = "Pulse width modulation unit 2"]
pub use self::pwm0_ns as pwm1_ns;
#[doc = "Pulse width modulation unit 3"]
pub type Pwm1S = crate::Periph<pwm0_ns::RegisterBlock, 0x5002_2000>;
impl core::fmt::Debug for Pwm1S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pwm1S").finish()
    }
}
#[doc = "Pulse width modulation unit 3"]
pub use self::pwm0_ns as pwm1_s;
#[doc = "Pulse width modulation unit 4"]
pub type Pwm2Ns = crate::Periph<pwm0_ns::RegisterBlock, 0x4002_3000>;
impl core::fmt::Debug for Pwm2Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pwm2Ns").finish()
    }
}
#[doc = "Pulse width modulation unit 4"]
pub use self::pwm0_ns as pwm2_ns;
#[doc = "Pulse width modulation unit 5"]
pub type Pwm2S = crate::Periph<pwm0_ns::RegisterBlock, 0x5002_3000>;
impl core::fmt::Debug for Pwm2S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pwm2S").finish()
    }
}
#[doc = "Pulse width modulation unit 5"]
pub use self::pwm0_ns as pwm2_s;
#[doc = "Pulse width modulation unit 6"]
pub type Pwm3Ns = crate::Periph<pwm0_ns::RegisterBlock, 0x4002_4000>;
impl core::fmt::Debug for Pwm3Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pwm3Ns").finish()
    }
}
#[doc = "Pulse width modulation unit 6"]
pub use self::pwm0_ns as pwm3_ns;
#[doc = "Pulse width modulation unit 7"]
pub type Pwm3S = crate::Periph<pwm0_ns::RegisterBlock, 0x5002_4000>;
impl core::fmt::Debug for Pwm3S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pwm3S").finish()
    }
}
#[doc = "Pulse width modulation unit 7"]
pub use self::pwm0_ns as pwm3_s;
#[doc = "Pulse Density Modulation (Digital Microphone) Interface 0"]
pub type PdmNs = crate::Periph<pdm_ns::RegisterBlock, 0x4002_6000>;
impl core::fmt::Debug for PdmNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("PdmNs").finish()
    }
}
#[doc = "Pulse Density Modulation (Digital Microphone) Interface 0"]
pub mod pdm_ns;
#[doc = "Pulse Density Modulation (Digital Microphone) Interface 1"]
pub type PdmS = crate::Periph<pdm_ns::RegisterBlock, 0x5002_6000>;
impl core::fmt::Debug for PdmS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("PdmS").finish()
    }
}
#[doc = "Pulse Density Modulation (Digital Microphone) Interface 1"]
pub use self::pdm_ns as pdm_s;
#[doc = "Inter-IC Sound 0"]
pub type I2sNs = crate::Periph<i2s_ns::RegisterBlock, 0x4002_8000>;
impl core::fmt::Debug for I2sNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2sNs").finish()
    }
}
#[doc = "Inter-IC Sound 0"]
pub mod i2s_ns;
#[doc = "Inter-IC Sound 1"]
pub type I2sS = crate::Periph<i2s_ns::RegisterBlock, 0x5002_8000>;
impl core::fmt::Debug for I2sS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2sS").finish()
    }
}
#[doc = "Inter-IC Sound 1"]
pub use self::i2s_ns as i2s_s;
#[doc = "Interprocessor communication 0"]
pub type IpcNs = crate::Periph<ipc_ns::RegisterBlock, 0x4002_a000>;
impl core::fmt::Debug for IpcNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("IpcNs").finish()
    }
}
#[doc = "Interprocessor communication 0"]
pub mod ipc_ns;
#[doc = "Interprocessor communication 1"]
pub type IpcS = crate::Periph<ipc_ns::RegisterBlock, 0x5002_a000>;
impl core::fmt::Debug for IpcS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("IpcS").finish()
    }
}
#[doc = "Interprocessor communication 1"]
pub use self::ipc_ns as ipc_s;
#[doc = "FPU"]
pub type FpuNs = crate::Periph<fpu_ns::RegisterBlock, 0x4002_c000>;
impl core::fmt::Debug for FpuNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("FpuNs").finish()
    }
}
#[doc = "FPU"]
pub mod fpu_ns;
#[doc = "GPIO Tasks and Events 1"]
pub type Gpiote1Ns = crate::Periph<gpiote0_s::RegisterBlock, 0x4003_1000>;
impl core::fmt::Debug for Gpiote1Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpiote1Ns").finish()
    }
}
#[doc = "GPIO Tasks and Events 1"]
pub use self::gpiote0_s as gpiote1_ns;
#[doc = "Key management unit 0"]
pub type KmuNs = crate::Periph<kmu_ns::RegisterBlock, 0x4003_9000>;
impl core::fmt::Debug for KmuNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("KmuNs").finish()
    }
}
#[doc = "Key management unit 0"]
pub mod kmu_ns;
#[doc = "Non-volatile memory controller 0"]
pub type NvmcNs = crate::Periph<nvmc_ns::RegisterBlock, 0x4003_9000>;
impl core::fmt::Debug for NvmcNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("NvmcNs").finish()
    }
}
#[doc = "Non-volatile memory controller 0"]
pub mod nvmc_ns;
#[doc = "Key management unit 1"]
pub type KmuS = crate::Periph<kmu_ns::RegisterBlock, 0x5003_9000>;
impl core::fmt::Debug for KmuS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("KmuS").finish()
    }
}
#[doc = "Key management unit 1"]
pub use self::kmu_ns as kmu_s;
#[doc = "Non-volatile memory controller 1"]
pub type NvmcS = crate::Periph<nvmc_ns::RegisterBlock, 0x5003_9000>;
impl core::fmt::Debug for NvmcS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("NvmcS").finish()
    }
}
#[doc = "Non-volatile memory controller 1"]
pub use self::nvmc_ns as nvmc_s;
#[doc = "Volatile Memory controller 0"]
pub type VmcNs = crate::Periph<vmc_ns::RegisterBlock, 0x4003_a000>;
impl core::fmt::Debug for VmcNs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("VmcNs").finish()
    }
}
#[doc = "Volatile Memory controller 0"]
pub mod vmc_ns;
#[doc = "Volatile Memory controller 1"]
pub type VmcS = crate::Periph<vmc_ns::RegisterBlock, 0x5003_a000>;
impl core::fmt::Debug for VmcS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("VmcS").finish()
    }
}
#[doc = "Volatile Memory controller 1"]
pub use self::vmc_ns as vmc_s;
#[doc = "CRYPTOCELL register interface"]
pub type CryptocellS = crate::Periph<cryptocell_s::RegisterBlock, 0x5084_0000>;
impl core::fmt::Debug for CryptocellS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("CryptocellS").finish()
    }
}
#[doc = "CRYPTOCELL register interface"]
pub mod cryptocell_s;
#[doc = "CRYPTOCELL AES engine"]
pub type CcAesS = crate::Periph<cc_aes_s::RegisterBlock, 0x5084_1000>;
impl core::fmt::Debug for CcAesS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("CcAesS").finish()
    }
}
#[doc = "CRYPTOCELL AES engine"]
pub mod cc_aes_s;
#[doc = "CRYPTOCELL AHB interface"]
pub type CcAhbS = crate::Periph<cc_ahb_s::RegisterBlock, 0x5084_1000>;
impl core::fmt::Debug for CcAhbS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("CcAhbS").finish()
    }
}
#[doc = "CRYPTOCELL AHB interface"]
pub mod cc_ahb_s;
#[doc = "CRYPTOCELL CHACHA engine"]
pub type CcChachaS = crate::Periph<cc_chacha_s::RegisterBlock, 0x5084_1000>;
impl core::fmt::Debug for CcChachaS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("CcChachaS").finish()
    }
}
#[doc = "CRYPTOCELL CHACHA engine"]
pub mod cc_chacha_s;
#[doc = "CRYPTOCELL CTL interface"]
pub type CcCtlS = crate::Periph<cc_ctl_s::RegisterBlock, 0x5084_1000>;
impl core::fmt::Debug for CcCtlS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("CcCtlS").finish()
    }
}
#[doc = "CRYPTOCELL CTL interface"]
pub mod cc_ctl_s;
#[doc = "CRYPTOCELL Data IN interface"]
pub type CcDinS = crate::Periph<cc_din_s::RegisterBlock, 0x5084_1000>;
impl core::fmt::Debug for CcDinS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("CcDinS").finish()
    }
}
#[doc = "CRYPTOCELL Data IN interface"]
pub mod cc_din_s;
#[doc = "CRYPTOCELL Data OUT interface"]
pub type CcDoutS = crate::Periph<cc_dout_s::RegisterBlock, 0x5084_1000>;
impl core::fmt::Debug for CcDoutS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("CcDoutS").finish()
    }
}
#[doc = "CRYPTOCELL Data OUT interface"]
pub mod cc_dout_s;
#[doc = "CRYPTOCELL HASH engine"]
pub type CcHashS = crate::Periph<cc_hash_s::RegisterBlock, 0x5084_1000>;
impl core::fmt::Debug for CcHashS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("CcHashS").finish()
    }
}
#[doc = "CRYPTOCELL HASH engine"]
pub mod cc_hash_s;
#[doc = "CRYPTOCELL HOST register interface"]
pub type CcHostRgfS = crate::Periph<cc_host_rgf_s::RegisterBlock, 0x5084_1000>;
impl core::fmt::Debug for CcHostRgfS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("CcHostRgfS").finish()
    }
}
#[doc = "CRYPTOCELL HOST register interface"]
pub mod cc_host_rgf_s;
#[doc = "CRYPTOCELL MISC interface"]
pub type CcMiscS = crate::Periph<cc_misc_s::RegisterBlock, 0x5084_1000>;
impl core::fmt::Debug for CcMiscS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("CcMiscS").finish()
    }
}
#[doc = "CRYPTOCELL MISC interface"]
pub mod cc_misc_s;
#[doc = "CRYPTOCELL PKA engine"]
pub type CcPkaS = crate::Periph<cc_pka_s::RegisterBlock, 0x5084_1000>;
impl core::fmt::Debug for CcPkaS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("CcPkaS").finish()
    }
}
#[doc = "CRYPTOCELL PKA engine"]
pub mod cc_pka_s;
#[doc = "CRYPTOCELL RNG engine"]
pub type CcRngS = crate::Periph<cc_rng_s::RegisterBlock, 0x5084_1000>;
impl core::fmt::Debug for CcRngS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("CcRngS").finish()
    }
}
#[doc = "CRYPTOCELL RNG engine"]
pub mod cc_rng_s;
#[doc = "CRYPTOCELL RNG SRAM interface"]
pub type CcRngSramS = crate::Periph<cc_rng_sram_s::RegisterBlock, 0x5084_1000>;
impl core::fmt::Debug for CcRngSramS {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("CcRngSramS").finish()
    }
}
#[doc = "CRYPTOCELL RNG SRAM interface"]
pub mod cc_rng_sram_s;
#[doc = "GPIO Port 0"]
pub type P0Ns = crate::Periph<p0_ns::RegisterBlock, 0x4084_2500>;
impl core::fmt::Debug for P0Ns {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("P0Ns").finish()
    }
}
#[doc = "GPIO Port 0"]
pub mod p0_ns;
#[doc = "GPIO Port 1"]
pub type P0S = crate::Periph<p0_ns::RegisterBlock, 0x5084_2500>;
impl core::fmt::Debug for P0S {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("P0S").finish()
    }
}
#[doc = "GPIO Port 1"]
pub use self::p0_ns as p0_s;
#[no_mangle]
static mut DEVICE_PERIPHERALS: bool = false;
#[doc = r" All the peripherals."]
#[allow(non_snake_case)]
pub struct Peripherals {
    #[doc = "FICR_S"]
    pub ficr_s: FicrS,
    #[doc = "UICR_S"]
    pub uicr_s: UicrS,
    #[doc = "ETM_NS"]
    pub etm_ns: EtmNs,
    #[doc = "ETB_NS"]
    pub etb_ns: EtbNs,
    #[doc = "TPIU_NS"]
    pub tpiu_ns: TpiuNs,
    #[doc = "ATBREPLICATOR_NS"]
    pub atbreplicator_ns: AtbreplicatorNs,
    #[doc = "ATBFUNNEL1_NS"]
    pub atbfunnel1_ns: Atbfunnel1Ns,
    #[doc = "ATBFUNNEL2_NS"]
    pub atbfunnel2_ns: Atbfunnel2Ns,
    #[doc = "TAD_S"]
    pub tad_s: TadS,
    #[doc = "SPU_S"]
    pub spu_s: SpuS,
    #[doc = "REGULATORS_NS"]
    pub regulators_ns: RegulatorsNs,
    #[doc = "REGULATORS_S"]
    pub regulators_s: RegulatorsS,
    #[doc = "CLOCK_NS"]
    pub clock_ns: ClockNs,
    #[doc = "POWER_NS"]
    pub power_ns: PowerNs,
    #[doc = "CLOCK_S"]
    pub clock_s: ClockS,
    #[doc = "POWER_S"]
    pub power_s: PowerS,
    #[doc = "CTRL_AP_PERI_S"]
    pub ctrl_ap_peri_s: CtrlApPeriS,
    #[doc = "SPIM0_NS"]
    pub spim0_ns: Spim0Ns,
    #[doc = "SPIS0_NS"]
    pub spis0_ns: Spis0Ns,
    #[doc = "TWIM0_NS"]
    pub twim0_ns: Twim0Ns,
    #[doc = "TWIS0_NS"]
    pub twis0_ns: Twis0Ns,
    #[doc = "UARTE0_NS"]
    pub uarte0_ns: Uarte0Ns,
    #[doc = "SPIM0_S"]
    pub spim0_s: Spim0S,
    #[doc = "SPIS0_S"]
    pub spis0_s: Spis0S,
    #[doc = "TWIM0_S"]
    pub twim0_s: Twim0S,
    #[doc = "TWIS0_S"]
    pub twis0_s: Twis0S,
    #[doc = "UARTE0_S"]
    pub uarte0_s: Uarte0S,
    #[doc = "SPIM1_NS"]
    pub spim1_ns: Spim1Ns,
    #[doc = "SPIS1_NS"]
    pub spis1_ns: Spis1Ns,
    #[doc = "TWIM1_NS"]
    pub twim1_ns: Twim1Ns,
    #[doc = "TWIS1_NS"]
    pub twis1_ns: Twis1Ns,
    #[doc = "UARTE1_NS"]
    pub uarte1_ns: Uarte1Ns,
    #[doc = "SPIM1_S"]
    pub spim1_s: Spim1S,
    #[doc = "SPIS1_S"]
    pub spis1_s: Spis1S,
    #[doc = "TWIM1_S"]
    pub twim1_s: Twim1S,
    #[doc = "TWIS1_S"]
    pub twis1_s: Twis1S,
    #[doc = "UARTE1_S"]
    pub uarte1_s: Uarte1S,
    #[doc = "SPIM2_NS"]
    pub spim2_ns: Spim2Ns,
    #[doc = "SPIS2_NS"]
    pub spis2_ns: Spis2Ns,
    #[doc = "TWIM2_NS"]
    pub twim2_ns: Twim2Ns,
    #[doc = "TWIS2_NS"]
    pub twis2_ns: Twis2Ns,
    #[doc = "UARTE2_NS"]
    pub uarte2_ns: Uarte2Ns,
    #[doc = "SPIM2_S"]
    pub spim2_s: Spim2S,
    #[doc = "SPIS2_S"]
    pub spis2_s: Spis2S,
    #[doc = "TWIM2_S"]
    pub twim2_s: Twim2S,
    #[doc = "TWIS2_S"]
    pub twis2_s: Twis2S,
    #[doc = "UARTE2_S"]
    pub uarte2_s: Uarte2S,
    #[doc = "SPIM3_NS"]
    pub spim3_ns: Spim3Ns,
    #[doc = "SPIS3_NS"]
    pub spis3_ns: Spis3Ns,
    #[doc = "TWIM3_NS"]
    pub twim3_ns: Twim3Ns,
    #[doc = "TWIS3_NS"]
    pub twis3_ns: Twis3Ns,
    #[doc = "UARTE3_NS"]
    pub uarte3_ns: Uarte3Ns,
    #[doc = "SPIM3_S"]
    pub spim3_s: Spim3S,
    #[doc = "SPIS3_S"]
    pub spis3_s: Spis3S,
    #[doc = "TWIM3_S"]
    pub twim3_s: Twim3S,
    #[doc = "TWIS3_S"]
    pub twis3_s: Twis3S,
    #[doc = "UARTE3_S"]
    pub uarte3_s: Uarte3S,
    #[doc = "GPIOTE0_S"]
    pub gpiote0_s: Gpiote0S,
    #[doc = "SAADC_NS"]
    pub saadc_ns: SaadcNs,
    #[doc = "SAADC_S"]
    pub saadc_s: SaadcS,
    #[doc = "TIMER0_NS"]
    pub timer0_ns: Timer0Ns,
    #[doc = "TIMER0_S"]
    pub timer0_s: Timer0S,
    #[doc = "TIMER1_NS"]
    pub timer1_ns: Timer1Ns,
    #[doc = "TIMER1_S"]
    pub timer1_s: Timer1S,
    #[doc = "TIMER2_NS"]
    pub timer2_ns: Timer2Ns,
    #[doc = "TIMER2_S"]
    pub timer2_s: Timer2S,
    #[doc = "RTC0_NS"]
    pub rtc0_ns: Rtc0Ns,
    #[doc = "RTC0_S"]
    pub rtc0_s: Rtc0S,
    #[doc = "RTC1_NS"]
    pub rtc1_ns: Rtc1Ns,
    #[doc = "RTC1_S"]
    pub rtc1_s: Rtc1S,
    #[doc = "DPPIC_NS"]
    pub dppic_ns: DppicNs,
    #[doc = "DPPIC_S"]
    pub dppic_s: DppicS,
    #[doc = "WDT_NS"]
    pub wdt_ns: WdtNs,
    #[doc = "WDT_S"]
    pub wdt_s: WdtS,
    #[doc = "EGU0_NS"]
    pub egu0_ns: Egu0Ns,
    #[doc = "EGU0_S"]
    pub egu0_s: Egu0S,
    #[doc = "EGU1_NS"]
    pub egu1_ns: Egu1Ns,
    #[doc = "EGU1_S"]
    pub egu1_s: Egu1S,
    #[doc = "EGU2_NS"]
    pub egu2_ns: Egu2Ns,
    #[doc = "EGU2_S"]
    pub egu2_s: Egu2S,
    #[doc = "EGU3_NS"]
    pub egu3_ns: Egu3Ns,
    #[doc = "EGU3_S"]
    pub egu3_s: Egu3S,
    #[doc = "EGU4_NS"]
    pub egu4_ns: Egu4Ns,
    #[doc = "EGU4_S"]
    pub egu4_s: Egu4S,
    #[doc = "EGU5_NS"]
    pub egu5_ns: Egu5Ns,
    #[doc = "EGU5_S"]
    pub egu5_s: Egu5S,
    #[doc = "PWM0_NS"]
    pub pwm0_ns: Pwm0Ns,
    #[doc = "PWM0_S"]
    pub pwm0_s: Pwm0S,
    #[doc = "PWM1_NS"]
    pub pwm1_ns: Pwm1Ns,
    #[doc = "PWM1_S"]
    pub pwm1_s: Pwm1S,
    #[doc = "PWM2_NS"]
    pub pwm2_ns: Pwm2Ns,
    #[doc = "PWM2_S"]
    pub pwm2_s: Pwm2S,
    #[doc = "PWM3_NS"]
    pub pwm3_ns: Pwm3Ns,
    #[doc = "PWM3_S"]
    pub pwm3_s: Pwm3S,
    #[doc = "PDM_NS"]
    pub pdm_ns: PdmNs,
    #[doc = "PDM_S"]
    pub pdm_s: PdmS,
    #[doc = "I2S_NS"]
    pub i2s_ns: I2sNs,
    #[doc = "I2S_S"]
    pub i2s_s: I2sS,
    #[doc = "IPC_NS"]
    pub ipc_ns: IpcNs,
    #[doc = "IPC_S"]
    pub ipc_s: IpcS,
    #[doc = "FPU_NS"]
    pub fpu_ns: FpuNs,
    #[doc = "GPIOTE1_NS"]
    pub gpiote1_ns: Gpiote1Ns,
    #[doc = "KMU_NS"]
    pub kmu_ns: KmuNs,
    #[doc = "NVMC_NS"]
    pub nvmc_ns: NvmcNs,
    #[doc = "KMU_S"]
    pub kmu_s: KmuS,
    #[doc = "NVMC_S"]
    pub nvmc_s: NvmcS,
    #[doc = "VMC_NS"]
    pub vmc_ns: VmcNs,
    #[doc = "VMC_S"]
    pub vmc_s: VmcS,
    #[doc = "CRYPTOCELL_S"]
    pub cryptocell_s: CryptocellS,
    #[doc = "CC_AES_S"]
    pub cc_aes_s: CcAesS,
    #[doc = "CC_AHB_S"]
    pub cc_ahb_s: CcAhbS,
    #[doc = "CC_CHACHA_S"]
    pub cc_chacha_s: CcChachaS,
    #[doc = "CC_CTL_S"]
    pub cc_ctl_s: CcCtlS,
    #[doc = "CC_DIN_S"]
    pub cc_din_s: CcDinS,
    #[doc = "CC_DOUT_S"]
    pub cc_dout_s: CcDoutS,
    #[doc = "CC_HASH_S"]
    pub cc_hash_s: CcHashS,
    #[doc = "CC_HOST_RGF_S"]
    pub cc_host_rgf_s: CcHostRgfS,
    #[doc = "CC_MISC_S"]
    pub cc_misc_s: CcMiscS,
    #[doc = "CC_PKA_S"]
    pub cc_pka_s: CcPkaS,
    #[doc = "CC_RNG_S"]
    pub cc_rng_s: CcRngS,
    #[doc = "CC_RNG_SRAM_S"]
    pub cc_rng_sram_s: CcRngSramS,
    #[doc = "P0_NS"]
    pub p0_ns: P0Ns,
    #[doc = "P0_S"]
    pub p0_s: P0S,
}
impl Peripherals {
    #[doc = r" Returns all the peripherals *once*."]
    #[cfg(feature = "critical-section")]
    #[inline]
    pub fn take() -> Option<Self> {
        critical_section::with(|_| {
            if unsafe { DEVICE_PERIPHERALS } {
                return None;
            }
            Some(unsafe { Peripherals::steal() })
        })
    }
    #[doc = r" Unchecked version of `Peripherals::take`."]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Each of the returned peripherals must be used at most once."]
    #[inline]
    pub unsafe fn steal() -> Self {
        DEVICE_PERIPHERALS = true;
        Peripherals {
            ficr_s: FicrS::steal(),
            uicr_s: UicrS::steal(),
            etm_ns: EtmNs::steal(),
            etb_ns: EtbNs::steal(),
            tpiu_ns: TpiuNs::steal(),
            atbreplicator_ns: AtbreplicatorNs::steal(),
            atbfunnel1_ns: Atbfunnel1Ns::steal(),
            atbfunnel2_ns: Atbfunnel2Ns::steal(),
            tad_s: TadS::steal(),
            spu_s: SpuS::steal(),
            regulators_ns: RegulatorsNs::steal(),
            regulators_s: RegulatorsS::steal(),
            clock_ns: ClockNs::steal(),
            power_ns: PowerNs::steal(),
            clock_s: ClockS::steal(),
            power_s: PowerS::steal(),
            ctrl_ap_peri_s: CtrlApPeriS::steal(),
            spim0_ns: Spim0Ns::steal(),
            spis0_ns: Spis0Ns::steal(),
            twim0_ns: Twim0Ns::steal(),
            twis0_ns: Twis0Ns::steal(),
            uarte0_ns: Uarte0Ns::steal(),
            spim0_s: Spim0S::steal(),
            spis0_s: Spis0S::steal(),
            twim0_s: Twim0S::steal(),
            twis0_s: Twis0S::steal(),
            uarte0_s: Uarte0S::steal(),
            spim1_ns: Spim1Ns::steal(),
            spis1_ns: Spis1Ns::steal(),
            twim1_ns: Twim1Ns::steal(),
            twis1_ns: Twis1Ns::steal(),
            uarte1_ns: Uarte1Ns::steal(),
            spim1_s: Spim1S::steal(),
            spis1_s: Spis1S::steal(),
            twim1_s: Twim1S::steal(),
            twis1_s: Twis1S::steal(),
            uarte1_s: Uarte1S::steal(),
            spim2_ns: Spim2Ns::steal(),
            spis2_ns: Spis2Ns::steal(),
            twim2_ns: Twim2Ns::steal(),
            twis2_ns: Twis2Ns::steal(),
            uarte2_ns: Uarte2Ns::steal(),
            spim2_s: Spim2S::steal(),
            spis2_s: Spis2S::steal(),
            twim2_s: Twim2S::steal(),
            twis2_s: Twis2S::steal(),
            uarte2_s: Uarte2S::steal(),
            spim3_ns: Spim3Ns::steal(),
            spis3_ns: Spis3Ns::steal(),
            twim3_ns: Twim3Ns::steal(),
            twis3_ns: Twis3Ns::steal(),
            uarte3_ns: Uarte3Ns::steal(),
            spim3_s: Spim3S::steal(),
            spis3_s: Spis3S::steal(),
            twim3_s: Twim3S::steal(),
            twis3_s: Twis3S::steal(),
            uarte3_s: Uarte3S::steal(),
            gpiote0_s: Gpiote0S::steal(),
            saadc_ns: SaadcNs::steal(),
            saadc_s: SaadcS::steal(),
            timer0_ns: Timer0Ns::steal(),
            timer0_s: Timer0S::steal(),
            timer1_ns: Timer1Ns::steal(),
            timer1_s: Timer1S::steal(),
            timer2_ns: Timer2Ns::steal(),
            timer2_s: Timer2S::steal(),
            rtc0_ns: Rtc0Ns::steal(),
            rtc0_s: Rtc0S::steal(),
            rtc1_ns: Rtc1Ns::steal(),
            rtc1_s: Rtc1S::steal(),
            dppic_ns: DppicNs::steal(),
            dppic_s: DppicS::steal(),
            wdt_ns: WdtNs::steal(),
            wdt_s: WdtS::steal(),
            egu0_ns: Egu0Ns::steal(),
            egu0_s: Egu0S::steal(),
            egu1_ns: Egu1Ns::steal(),
            egu1_s: Egu1S::steal(),
            egu2_ns: Egu2Ns::steal(),
            egu2_s: Egu2S::steal(),
            egu3_ns: Egu3Ns::steal(),
            egu3_s: Egu3S::steal(),
            egu4_ns: Egu4Ns::steal(),
            egu4_s: Egu4S::steal(),
            egu5_ns: Egu5Ns::steal(),
            egu5_s: Egu5S::steal(),
            pwm0_ns: Pwm0Ns::steal(),
            pwm0_s: Pwm0S::steal(),
            pwm1_ns: Pwm1Ns::steal(),
            pwm1_s: Pwm1S::steal(),
            pwm2_ns: Pwm2Ns::steal(),
            pwm2_s: Pwm2S::steal(),
            pwm3_ns: Pwm3Ns::steal(),
            pwm3_s: Pwm3S::steal(),
            pdm_ns: PdmNs::steal(),
            pdm_s: PdmS::steal(),
            i2s_ns: I2sNs::steal(),
            i2s_s: I2sS::steal(),
            ipc_ns: IpcNs::steal(),
            ipc_s: IpcS::steal(),
            fpu_ns: FpuNs::steal(),
            gpiote1_ns: Gpiote1Ns::steal(),
            kmu_ns: KmuNs::steal(),
            nvmc_ns: NvmcNs::steal(),
            kmu_s: KmuS::steal(),
            nvmc_s: NvmcS::steal(),
            vmc_ns: VmcNs::steal(),
            vmc_s: VmcS::steal(),
            cryptocell_s: CryptocellS::steal(),
            cc_aes_s: CcAesS::steal(),
            cc_ahb_s: CcAhbS::steal(),
            cc_chacha_s: CcChachaS::steal(),
            cc_ctl_s: CcCtlS::steal(),
            cc_din_s: CcDinS::steal(),
            cc_dout_s: CcDoutS::steal(),
            cc_hash_s: CcHashS::steal(),
            cc_host_rgf_s: CcHostRgfS::steal(),
            cc_misc_s: CcMiscS::steal(),
            cc_pka_s: CcPkaS::steal(),
            cc_rng_s: CcRngS::steal(),
            cc_rng_sram_s: CcRngSramS::steal(),
            p0_ns: P0Ns::steal(),
            p0_s: P0S::steal(),
        }
    }
}
