#[doc = "Register `ACCDBLREAD` reader"]
pub type R = crate::R<AccdblreadSpec>;
#[doc = "Field `ACCDBLREAD` reader - Snapshot of accumulated double (error) transitions."]
pub type AccdblreadR = crate::FieldReader;
impl R {
    #[doc = "Bits 0:3 - Snapshot of accumulated double (error) transitions."]
    #[inline(always)]
    pub fn accdblread(&self) -> AccdblreadR {
        AccdblreadR::new((self.bits & 0x0f) as u8)
    }
}
#[doc = "Snapshot of ACCDBL register. Value generated by the TASKS_READCLEACC task.\n\nYou can [`read`](crate::Reg::read) this register and get [`accdblread::R`](R). See [API](https://docs.rs/svd2rust/#read--modify--write-api)."]
pub struct AccdblreadSpec;
impl crate::RegisterSpec for AccdblreadSpec {
    type Ux = u32;
}
#[doc = "`read()` method returns [`accdblread::R`](R) reader structure"]
impl crate::Readable for AccdblreadSpec {}
#[doc = "`reset()` method sets ACCDBLREAD to value 0"]
impl crate::Resettable for AccdblreadSpec {}
