#[doc = "Register `ACCREAD` reader"]
pub struct R(crate::R<ACCREAD_SPEC>);
impl core::ops::Deref for R {
    type Target = crate::R<ACCREAD_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl From<crate::R<ACCREAD_SPEC>> for R {
    #[inline(always)]
    fn from(reader: crate::R<ACCREAD_SPEC>) -> Self {
        R(reader)
    }
}
#[doc = "Snapshot of ACC register. Value generated by the TASKS_READCLEACC task.\n\nThis register you can [`read`](crate::generic::Reg::read). See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [accread](index.html) module"]
pub struct ACCREAD_SPEC;
impl crate::RegisterSpec for ACCREAD_SPEC {
    type Ux = u32;
}
#[doc = "`read()` method returns [accread::R](R) reader structure"]
impl crate::Readable for ACCREAD_SPEC {
    type Reader = R;
}
#[doc = "`reset()` method sets ACCREAD to value 0"]
impl crate::Resettable for ACCREAD_SPEC {
    #[inline(always)]
    fn reset_value() -> Self::Ux {
        0
    }
}
