#[doc = "Register `ACCREAD` reader"]
pub type R = crate::R<AccreadSpec>;
impl core::fmt::Debug for R {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        write!(f, "{}", self.bits())
    }
}
#[doc = "Snapshot of ACC register. Value generated by the TASKS_READCLEACC task.\n\nYou can [`read`](crate::Reg::read) this register and get [`accread::R`](R). See [API](https://docs.rs/svd2rust/#read--modify--write-api)."]
pub struct AccreadSpec;
impl crate::RegisterSpec for AccreadSpec {
    type Ux = u32;
}
#[doc = "`read()` method returns [`accread::R`](R) reader structure"]
impl crate::Readable for AccreadSpec {}
#[doc = "`reset()` method sets ACCREAD to value 0"]
impl crate::Resettable for AccreadSpec {}
