#[doc = "Register `EVENTS_TRIGGERED[%s]` reader"]
pub type R = crate::R<EventsTriggeredSpec>;
#[doc = "Register `EVENTS_TRIGGERED[%s]` writer"]
pub type W = crate::W<EventsTriggeredSpec>;
impl core::fmt::Debug for R {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        write!(f, "{}", self.bits())
    }
}
impl W {}
#[doc = "Description collection\\[0\\]: Event number 0 generated by triggering the corresponding TRIGGER\\[0\\] task\n\nYou can [`read`](crate::Reg::read) this register and get [`events_triggered::R`](R). You can [`reset`](crate::Reg::reset), [`write`](crate::Reg::write), [`write_with_zero`](crate::Reg::write_with_zero) this register using [`events_triggered::W`](W). You can also [`modify`](crate::Reg::modify) this register. See [API](https://docs.rs/svd2rust/#read--modify--write-api)."]
pub struct EventsTriggeredSpec;
impl crate::RegisterSpec for EventsTriggeredSpec {
    type Ux = u32;
}
#[doc = "`read()` method returns [`events_triggered::R`](R) reader structure"]
impl crate::Readable for EventsTriggeredSpec {}
#[doc = "`write(|w| ..)` method takes [`events_triggered::W`](W) writer structure"]
impl crate::Writable for EventsTriggeredSpec {
    type Safety = crate::Unsafe;
}
#[doc = "`reset()` method sets EVENTS_TRIGGERED[%s] to value 0"]
impl crate::Resettable for EventsTriggeredSpec {}
