#![doc = "Peripheral access API for NRF51 microcontrollers (generated using svd2rust v0.37.0 ( ))\n\nYou can find an overview of the generated API [here].\n\nAPI features to be included in the [next] svd2rust release can be generated by cloning the svd2rust [repository], checking out the above commit, and running `cargo doc --open`.\n\n[here]: https://docs.rs/svd2rust/0.37.0/svd2rust/#peripheral-api\n[next]: https://github.com/rust-embedded/svd2rust/blob/master/CHANGELOG.md#unreleased\n[repository]: https://github.com/rust-embedded/svd2rust"]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![no_std]
#![cfg_attr(docsrs, feature(doc_auto_cfg))]
#[doc = r"Number available in the NVIC for configuring priority"]
pub const NVIC_PRIO_BITS: u8 = 2;
#[allow(unused_imports)]
use generic::*;
#[doc = r"Common register and bit access and modify traits"]
pub mod generic;
#[cfg(feature = "rt")]
extern "C" {
    fn POWER_CLOCK();
    fn RADIO();
    fn UART0();
    fn SPI0_TWI0();
    fn SPI1_TWI1();
    fn GPIOTE();
    fn ADC();
    fn TIMER0();
    fn TIMER1();
    fn TIMER2();
    fn RTC0();
    fn TEMP();
    fn RNG();
    fn ECB();
    fn CCM_AAR();
    fn WDT();
    fn RTC1();
    fn QDEC();
    fn LPCOMP();
    fn SWI0();
    fn SWI1();
    fn SWI2();
    fn SWI3();
    fn SWI4();
    fn SWI5();
}
#[doc(hidden)]
#[repr(C)]
pub union Vector {
    _handler: unsafe extern "C" fn(),
    _reserved: u32,
}
#[cfg(feature = "rt")]
#[doc(hidden)]
#[link_section = ".vector_table.interrupts"]
#[no_mangle]
pub static __INTERRUPTS: [Vector; 26] = [
    Vector {
        _handler: POWER_CLOCK,
    },
    Vector { _handler: RADIO },
    Vector { _handler: UART0 },
    Vector {
        _handler: SPI0_TWI0,
    },
    Vector {
        _handler: SPI1_TWI1,
    },
    Vector { _reserved: 0 },
    Vector { _handler: GPIOTE },
    Vector { _handler: ADC },
    Vector { _handler: TIMER0 },
    Vector { _handler: TIMER1 },
    Vector { _handler: TIMER2 },
    Vector { _handler: RTC0 },
    Vector { _handler: TEMP },
    Vector { _handler: RNG },
    Vector { _handler: ECB },
    Vector { _handler: CCM_AAR },
    Vector { _handler: WDT },
    Vector { _handler: RTC1 },
    Vector { _handler: QDEC },
    Vector { _handler: LPCOMP },
    Vector { _handler: SWI0 },
    Vector { _handler: SWI1 },
    Vector { _handler: SWI2 },
    Vector { _handler: SWI3 },
    Vector { _handler: SWI4 },
    Vector { _handler: SWI5 },
];
#[doc = r"Enumeration of all the interrupts."]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
#[repr(u16)]
pub enum Interrupt {
    #[doc = "0 - POWER_CLOCK"]
    POWER_CLOCK = 0,
    #[doc = "1 - RADIO"]
    RADIO = 1,
    #[doc = "2 - UART0"]
    UART0 = 2,
    #[doc = "3 - SPI0_TWI0"]
    SPI0_TWI0 = 3,
    #[doc = "4 - SPI1_TWI1"]
    SPI1_TWI1 = 4,
    #[doc = "6 - GPIOTE"]
    GPIOTE = 6,
    #[doc = "7 - ADC"]
    ADC = 7,
    #[doc = "8 - TIMER0"]
    TIMER0 = 8,
    #[doc = "9 - TIMER1"]
    TIMER1 = 9,
    #[doc = "10 - TIMER2"]
    TIMER2 = 10,
    #[doc = "11 - RTC0"]
    RTC0 = 11,
    #[doc = "12 - TEMP"]
    TEMP = 12,
    #[doc = "13 - RNG"]
    RNG = 13,
    #[doc = "14 - ECB"]
    ECB = 14,
    #[doc = "15 - CCM_AAR"]
    CCM_AAR = 15,
    #[doc = "16 - WDT"]
    WDT = 16,
    #[doc = "17 - RTC1"]
    RTC1 = 17,
    #[doc = "18 - QDEC"]
    QDEC = 18,
    #[doc = "19 - LPCOMP"]
    LPCOMP = 19,
    #[doc = "20 - SWI0"]
    SWI0 = 20,
    #[doc = "21 - SWI1"]
    SWI1 = 21,
    #[doc = "22 - SWI2"]
    SWI2 = 22,
    #[doc = "23 - SWI3"]
    SWI3 = 23,
    #[doc = "24 - SWI4"]
    SWI4 = 24,
    #[doc = "25 - SWI5"]
    SWI5 = 25,
}
unsafe impl cortex_m::interrupt::InterruptNumber for Interrupt {
    #[inline(always)]
    fn number(self) -> u16 {
        self as u16
    }
}
#[doc = "Power Control."]
pub type Power = crate::Periph<power::RegisterBlock, 0x4000_0000>;
impl core::fmt::Debug for Power {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Power").finish()
    }
}
#[doc = "Power Control."]
pub mod power;
#[doc = "Clock control."]
pub type Clock = crate::Periph<clock::RegisterBlock, 0x4000_0000>;
impl core::fmt::Debug for Clock {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Clock").finish()
    }
}
#[doc = "Clock control."]
pub mod clock;
#[doc = "The radio."]
pub type Radio = crate::Periph<radio::RegisterBlock, 0x4000_1000>;
impl core::fmt::Debug for Radio {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Radio").finish()
    }
}
#[doc = "The radio."]
pub mod radio;
#[doc = "Universal Asynchronous Receiver/Transmitter."]
pub type Uart0 = crate::Periph<uart0::RegisterBlock, 0x4000_2000>;
impl core::fmt::Debug for Uart0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uart0").finish()
    }
}
#[doc = "Universal Asynchronous Receiver/Transmitter."]
pub mod uart0;
#[doc = "SPI master 0."]
pub type Spi0 = crate::Periph<spi0::RegisterBlock, 0x4000_3000>;
impl core::fmt::Debug for Spi0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spi0").finish()
    }
}
#[doc = "SPI master 0."]
pub mod spi0;
#[doc = "Two-wire interface master 0."]
pub type Twi0 = crate::Periph<twi0::RegisterBlock, 0x4000_3000>;
impl core::fmt::Debug for Twi0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Twi0").finish()
    }
}
#[doc = "Two-wire interface master 0."]
pub mod twi0;
#[doc = "SPI master 1."]
pub type Spi1 = crate::Periph<spi0::RegisterBlock, 0x4000_4000>;
impl core::fmt::Debug for Spi1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spi1").finish()
    }
}
#[doc = "SPI master 1."]
pub use self::spi0 as spi1;
#[doc = "Two-wire interface master 1."]
pub type Twi1 = crate::Periph<twi0::RegisterBlock, 0x4000_4000>;
impl core::fmt::Debug for Twi1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Twi1").finish()
    }
}
#[doc = "Two-wire interface master 1."]
pub use self::twi0 as twi1;
#[doc = "SPI slave 1."]
pub type Spis1 = crate::Periph<spis1::RegisterBlock, 0x4000_4000>;
impl core::fmt::Debug for Spis1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spis1").finish()
    }
}
#[doc = "SPI slave 1."]
pub mod spis1;
#[doc = "GPIO tasks and events."]
pub type Gpiote = crate::Periph<gpiote::RegisterBlock, 0x4000_6000>;
impl core::fmt::Debug for Gpiote {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpiote").finish()
    }
}
#[doc = "GPIO tasks and events."]
pub mod gpiote;
#[doc = "Analog to digital converter."]
pub type Adc = crate::Periph<adc::RegisterBlock, 0x4000_7000>;
impl core::fmt::Debug for Adc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Adc").finish()
    }
}
#[doc = "Analog to digital converter."]
pub mod adc;
#[doc = "Timer 0."]
pub type Timer0 = crate::Periph<timer0::RegisterBlock, 0x4000_8000>;
impl core::fmt::Debug for Timer0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timer0").finish()
    }
}
#[doc = "Timer 0."]
pub mod timer0;
#[doc = "Timer 1."]
pub type Timer1 = crate::Periph<timer0::RegisterBlock, 0x4000_9000>;
impl core::fmt::Debug for Timer1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timer1").finish()
    }
}
#[doc = "Timer 1."]
pub use self::timer0 as timer1;
#[doc = "Timer 2."]
pub type Timer2 = crate::Periph<timer0::RegisterBlock, 0x4000_a000>;
impl core::fmt::Debug for Timer2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timer2").finish()
    }
}
#[doc = "Timer 2."]
pub use self::timer0 as timer2;
#[doc = "Real time counter 0."]
pub type Rtc0 = crate::Periph<rtc0::RegisterBlock, 0x4000_b000>;
impl core::fmt::Debug for Rtc0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Rtc0").finish()
    }
}
#[doc = "Real time counter 0."]
pub mod rtc0;
#[doc = "Temperature Sensor."]
pub type Temp = crate::Periph<temp::RegisterBlock, 0x4000_c000>;
impl core::fmt::Debug for Temp {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Temp").finish()
    }
}
#[doc = "Temperature Sensor."]
pub mod temp;
#[doc = "Random Number Generator."]
pub type Rng = crate::Periph<rng::RegisterBlock, 0x4000_d000>;
impl core::fmt::Debug for Rng {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Rng").finish()
    }
}
#[doc = "Random Number Generator."]
pub mod rng;
#[doc = "AES ECB Mode Encryption."]
pub type Ecb = crate::Periph<ecb::RegisterBlock, 0x4000_e000>;
impl core::fmt::Debug for Ecb {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Ecb").finish()
    }
}
#[doc = "AES ECB Mode Encryption."]
pub mod ecb;
#[doc = "Accelerated Address Resolver."]
pub type Aar = crate::Periph<aar::RegisterBlock, 0x4000_f000>;
impl core::fmt::Debug for Aar {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Aar").finish()
    }
}
#[doc = "Accelerated Address Resolver."]
pub mod aar;
#[doc = "AES CCM Mode Encryption."]
pub type Ccm = crate::Periph<ccm::RegisterBlock, 0x4000_f000>;
impl core::fmt::Debug for Ccm {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Ccm").finish()
    }
}
#[doc = "AES CCM Mode Encryption."]
pub mod ccm;
#[doc = "Watchdog Timer."]
pub type Wdt = crate::Periph<wdt::RegisterBlock, 0x4001_0000>;
impl core::fmt::Debug for Wdt {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Wdt").finish()
    }
}
#[doc = "Watchdog Timer."]
pub mod wdt;
#[doc = "Real time counter 1."]
pub type Rtc1 = crate::Periph<rtc0::RegisterBlock, 0x4001_1000>;
impl core::fmt::Debug for Rtc1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Rtc1").finish()
    }
}
#[doc = "Real time counter 1."]
pub use self::rtc0 as rtc1;
#[doc = "Rotary decoder."]
pub type Qdec = crate::Periph<qdec::RegisterBlock, 0x4001_2000>;
impl core::fmt::Debug for Qdec {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Qdec").finish()
    }
}
#[doc = "Rotary decoder."]
pub mod qdec;
#[doc = "Low power comparator."]
pub type Lpcomp = crate::Periph<lpcomp::RegisterBlock, 0x4001_3000>;
impl core::fmt::Debug for Lpcomp {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Lpcomp").finish()
    }
}
#[doc = "Low power comparator."]
pub mod lpcomp;
#[doc = "SW Interrupts."]
pub type Swi = crate::Periph<swi::RegisterBlock, 0x4001_4000>;
impl core::fmt::Debug for Swi {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Swi").finish()
    }
}
#[doc = "SW Interrupts."]
pub mod swi;
#[doc = "Non Volatile Memory Controller."]
pub type Nvmc = crate::Periph<nvmc::RegisterBlock, 0x4001_e000>;
impl core::fmt::Debug for Nvmc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Nvmc").finish()
    }
}
#[doc = "Non Volatile Memory Controller."]
pub mod nvmc;
#[doc = "PPI controller."]
pub type Ppi = crate::Periph<ppi::RegisterBlock, 0x4001_f000>;
impl core::fmt::Debug for Ppi {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Ppi").finish()
    }
}
#[doc = "PPI controller."]
pub mod ppi;
#[doc = "Factory Information Configuration."]
pub type Ficr = crate::Periph<ficr::RegisterBlock, 0x1000_0000>;
impl core::fmt::Debug for Ficr {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Ficr").finish()
    }
}
#[doc = "Factory Information Configuration."]
pub mod ficr;
#[doc = "User Information Configuration."]
pub type Uicr = crate::Periph<uicr::RegisterBlock, 0x1000_1000>;
impl core::fmt::Debug for Uicr {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uicr").finish()
    }
}
#[doc = "User Information Configuration."]
pub mod uicr;
#[doc = "General purpose input and output."]
pub type Gpio = crate::Periph<gpio::RegisterBlock, 0x5000_0000>;
impl core::fmt::Debug for Gpio {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpio").finish()
    }
}
#[doc = "General purpose input and output."]
pub mod gpio;
#[no_mangle]
static mut DEVICE_PERIPHERALS: bool = false;
#[doc = r" All the peripherals."]
#[allow(non_snake_case)]
pub struct Peripherals {
    #[doc = "POWER"]
    pub power: Power,
    #[doc = "CLOCK"]
    pub clock: Clock,
    #[doc = "RADIO"]
    pub radio: Radio,
    #[doc = "UART0"]
    pub uart0: Uart0,
    #[doc = "SPI0"]
    pub spi0: Spi0,
    #[doc = "TWI0"]
    pub twi0: Twi0,
    #[doc = "SPI1"]
    pub spi1: Spi1,
    #[doc = "TWI1"]
    pub twi1: Twi1,
    #[doc = "SPIS1"]
    pub spis1: Spis1,
    #[doc = "GPIOTE"]
    pub gpiote: Gpiote,
    #[doc = "ADC"]
    pub adc: Adc,
    #[doc = "TIMER0"]
    pub timer0: Timer0,
    #[doc = "TIMER1"]
    pub timer1: Timer1,
    #[doc = "TIMER2"]
    pub timer2: Timer2,
    #[doc = "RTC0"]
    pub rtc0: Rtc0,
    #[doc = "TEMP"]
    pub temp: Temp,
    #[doc = "RNG"]
    pub rng: Rng,
    #[doc = "ECB"]
    pub ecb: Ecb,
    #[doc = "AAR"]
    pub aar: Aar,
    #[doc = "CCM"]
    pub ccm: Ccm,
    #[doc = "WDT"]
    pub wdt: Wdt,
    #[doc = "RTC1"]
    pub rtc1: Rtc1,
    #[doc = "QDEC"]
    pub qdec: Qdec,
    #[doc = "LPCOMP"]
    pub lpcomp: Lpcomp,
    #[doc = "SWI"]
    pub swi: Swi,
    #[doc = "NVMC"]
    pub nvmc: Nvmc,
    #[doc = "PPI"]
    pub ppi: Ppi,
    #[doc = "FICR"]
    pub ficr: Ficr,
    #[doc = "UICR"]
    pub uicr: Uicr,
    #[doc = "GPIO"]
    pub gpio: Gpio,
}
impl Peripherals {
    #[doc = r" Returns all the peripherals *once*."]
    #[cfg(feature = "critical-section")]
    #[inline]
    pub fn take() -> Option<Self> {
        critical_section::with(|_| {
            if unsafe { DEVICE_PERIPHERALS } {
                return None;
            }
            Some(unsafe { Peripherals::steal() })
        })
    }
    #[doc = r" Unchecked version of `Peripherals::take`."]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Each of the returned peripherals must be used at most once."]
    #[inline]
    pub unsafe fn steal() -> Self {
        DEVICE_PERIPHERALS = true;
        Peripherals {
            power: Power::steal(),
            clock: Clock::steal(),
            radio: Radio::steal(),
            uart0: Uart0::steal(),
            spi0: Spi0::steal(),
            twi0: Twi0::steal(),
            spi1: Spi1::steal(),
            twi1: Twi1::steal(),
            spis1: Spis1::steal(),
            gpiote: Gpiote::steal(),
            adc: Adc::steal(),
            timer0: Timer0::steal(),
            timer1: Timer1::steal(),
            timer2: Timer2::steal(),
            rtc0: Rtc0::steal(),
            temp: Temp::steal(),
            rng: Rng::steal(),
            ecb: Ecb::steal(),
            aar: Aar::steal(),
            ccm: Ccm::steal(),
            wdt: Wdt::steal(),
            rtc1: Rtc1::steal(),
            qdec: Qdec::steal(),
            lpcomp: Lpcomp::steal(),
            swi: Swi::steal(),
            nvmc: Nvmc::steal(),
            ppi: Ppi::steal(),
            ficr: Ficr::steal(),
            uicr: Uicr::steal(),
            gpio: Gpio::steal(),
        }
    }
}
