#[repr(C)]
#[doc = "Register block"]
pub struct RegisterBlock {
    tasks_start: TasksStart,
    tasks_stop: TasksStop,
    tasks_readclracc: TasksReadclracc,
    _reserved3: [u8; 0xf4],
    events_samplerdy: EventsSamplerdy,
    events_reportrdy: EventsReportrdy,
    events_accof: EventsAccof,
    _reserved6: [u8; 0xf4],
    shorts: Shorts,
    _reserved7: [u8; 0x0100],
    intenset: Intenset,
    intenclr: Intenclr,
    _reserved9: [u8; 0x01f4],
    enable: Enable,
    ledpol: Ledpol,
    sampleper: Sampleper,
    sample: Sample,
    reportper: Reportper,
    acc: Acc,
    accread: Accread,
    pselled: Pselled,
    psela: Psela,
    pselb: Pselb,
    dbfen: Dbfen,
    _reserved20: [u8; 0x14],
    ledpre: Ledpre,
    accdbl: Accdbl,
    accdblread: Accdblread,
    _reserved23: [u8; 0x0ab0],
    power: Power,
}
impl RegisterBlock {
    #[doc = "0x00 - Start the quadrature decoder."]
    #[inline(always)]
    pub const fn tasks_start(&self) -> &TasksStart {
        &self.tasks_start
    }
    #[doc = "0x04 - Stop the quadrature decoder."]
    #[inline(always)]
    pub const fn tasks_stop(&self) -> &TasksStop {
        &self.tasks_stop
    }
    #[doc = "0x08 - Transfers the content from ACC registers to ACCREAD registers, and clears the ACC registers."]
    #[inline(always)]
    pub const fn tasks_readclracc(&self) -> &TasksReadclracc {
        &self.tasks_readclracc
    }
    #[doc = "0x100 - A new sample is written to the sample register."]
    #[inline(always)]
    pub const fn events_samplerdy(&self) -> &EventsSamplerdy {
        &self.events_samplerdy
    }
    #[doc = "0x104 - REPORTPER number of samples accumulated in ACC register, and ACC register different than zero."]
    #[inline(always)]
    pub const fn events_reportrdy(&self) -> &EventsReportrdy {
        &self.events_reportrdy
    }
    #[doc = "0x108 - ACC or ACCDBL register overflow."]
    #[inline(always)]
    pub const fn events_accof(&self) -> &EventsAccof {
        &self.events_accof
    }
    #[doc = "0x200 - Shortcuts for the QDEC."]
    #[inline(always)]
    pub const fn shorts(&self) -> &Shorts {
        &self.shorts
    }
    #[doc = "0x304 - Interrupt enable set register."]
    #[inline(always)]
    pub const fn intenset(&self) -> &Intenset {
        &self.intenset
    }
    #[doc = "0x308 - Interrupt enable clear register."]
    #[inline(always)]
    pub const fn intenclr(&self) -> &Intenclr {
        &self.intenclr
    }
    #[doc = "0x500 - Enable the QDEC."]
    #[inline(always)]
    pub const fn enable(&self) -> &Enable {
        &self.enable
    }
    #[doc = "0x504 - LED output pin polarity."]
    #[inline(always)]
    pub const fn ledpol(&self) -> &Ledpol {
        &self.ledpol
    }
    #[doc = "0x508 - Sample period."]
    #[inline(always)]
    pub const fn sampleper(&self) -> &Sampleper {
        &self.sampleper
    }
    #[doc = "0x50c - Motion sample value."]
    #[inline(always)]
    pub const fn sample(&self) -> &Sample {
        &self.sample
    }
    #[doc = "0x510 - Number of samples to generate an EVENT_REPORTRDY."]
    #[inline(always)]
    pub const fn reportper(&self) -> &Reportper {
        &self.reportper
    }
    #[doc = "0x514 - Accumulated valid transitions register."]
    #[inline(always)]
    pub const fn acc(&self) -> &Acc {
        &self.acc
    }
    #[doc = "0x518 - Snapshot of ACC register. Value generated by the TASKS_READCLEACC task."]
    #[inline(always)]
    pub const fn accread(&self) -> &Accread {
        &self.accread
    }
    #[doc = "0x51c - Pin select for LED output."]
    #[inline(always)]
    pub const fn pselled(&self) -> &Pselled {
        &self.pselled
    }
    #[doc = "0x520 - Pin select for phase A input."]
    #[inline(always)]
    pub const fn psela(&self) -> &Psela {
        &self.psela
    }
    #[doc = "0x524 - Pin select for phase B input."]
    #[inline(always)]
    pub const fn pselb(&self) -> &Pselb {
        &self.pselb
    }
    #[doc = "0x528 - Enable debouncer input filters."]
    #[inline(always)]
    pub const fn dbfen(&self) -> &Dbfen {
        &self.dbfen
    }
    #[doc = "0x540 - Time LED is switched ON before the sample."]
    #[inline(always)]
    pub const fn ledpre(&self) -> &Ledpre {
        &self.ledpre
    }
    #[doc = "0x544 - Accumulated double (error) transitions register."]
    #[inline(always)]
    pub const fn accdbl(&self) -> &Accdbl {
        &self.accdbl
    }
    #[doc = "0x548 - Snapshot of ACCDBL register. Value generated by the TASKS_READCLEACC task."]
    #[inline(always)]
    pub const fn accdblread(&self) -> &Accdblread {
        &self.accdblread
    }
    #[doc = "0xffc - Peripheral power control."]
    #[inline(always)]
    pub const fn power(&self) -> &Power {
        &self.power
    }
}
#[doc = "TASKS_START (w) register accessor: Start the quadrature decoder.\n\nYou can [`reset`](crate::Reg::reset), [`write`](crate::Reg::write), [`write_with_zero`](crate::Reg::write_with_zero) this register using [`tasks_start::W`]. See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [`mod@tasks_start`] module"]
#[doc(alias = "TASKS_START")]
pub type TasksStart = crate::Reg<tasks_start::TasksStartSpec>;
#[doc = "Start the quadrature decoder."]
pub mod tasks_start;
#[doc = "TASKS_STOP (w) register accessor: Stop the quadrature decoder.\n\nYou can [`reset`](crate::Reg::reset), [`write`](crate::Reg::write), [`write_with_zero`](crate::Reg::write_with_zero) this register using [`tasks_stop::W`]. See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [`mod@tasks_stop`] module"]
#[doc(alias = "TASKS_STOP")]
pub type TasksStop = crate::Reg<tasks_stop::TasksStopSpec>;
#[doc = "Stop the quadrature decoder."]
pub mod tasks_stop;
#[doc = "TASKS_READCLRACC (w) register accessor: Transfers the content from ACC registers to ACCREAD registers, and clears the ACC registers.\n\nYou can [`reset`](crate::Reg::reset), [`write`](crate::Reg::write), [`write_with_zero`](crate::Reg::write_with_zero) this register using [`tasks_readclracc::W`]. See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [`mod@tasks_readclracc`] module"]
#[doc(alias = "TASKS_READCLRACC")]
pub type TasksReadclracc = crate::Reg<tasks_readclracc::TasksReadclraccSpec>;
#[doc = "Transfers the content from ACC registers to ACCREAD registers, and clears the ACC registers."]
pub mod tasks_readclracc;
#[doc = "EVENTS_SAMPLERDY (rw) register accessor: A new sample is written to the sample register.\n\nYou can [`read`](crate::Reg::read) this register and get [`events_samplerdy::R`]. You can [`reset`](crate::Reg::reset), [`write`](crate::Reg::write), [`write_with_zero`](crate::Reg::write_with_zero) this register using [`events_samplerdy::W`]. You can also [`modify`](crate::Reg::modify) this register. See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [`mod@events_samplerdy`] module"]
#[doc(alias = "EVENTS_SAMPLERDY")]
pub type EventsSamplerdy = crate::Reg<events_samplerdy::EventsSamplerdySpec>;
#[doc = "A new sample is written to the sample register."]
pub mod events_samplerdy;
#[doc = "EVENTS_REPORTRDY (rw) register accessor: REPORTPER number of samples accumulated in ACC register, and ACC register different than zero.\n\nYou can [`read`](crate::Reg::read) this register and get [`events_reportrdy::R`]. You can [`reset`](crate::Reg::reset), [`write`](crate::Reg::write), [`write_with_zero`](crate::Reg::write_with_zero) this register using [`events_reportrdy::W`]. You can also [`modify`](crate::Reg::modify) this register. See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [`mod@events_reportrdy`] module"]
#[doc(alias = "EVENTS_REPORTRDY")]
pub type EventsReportrdy = crate::Reg<events_reportrdy::EventsReportrdySpec>;
#[doc = "REPORTPER number of samples accumulated in ACC register, and ACC register different than zero."]
pub mod events_reportrdy;
#[doc = "EVENTS_ACCOF (rw) register accessor: ACC or ACCDBL register overflow.\n\nYou can [`read`](crate::Reg::read) this register and get [`events_accof::R`]. You can [`reset`](crate::Reg::reset), [`write`](crate::Reg::write), [`write_with_zero`](crate::Reg::write_with_zero) this register using [`events_accof::W`]. You can also [`modify`](crate::Reg::modify) this register. See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [`mod@events_accof`] module"]
#[doc(alias = "EVENTS_ACCOF")]
pub type EventsAccof = crate::Reg<events_accof::EventsAccofSpec>;
#[doc = "ACC or ACCDBL register overflow."]
pub mod events_accof;
#[doc = "SHORTS (rw) register accessor: Shortcuts for the QDEC.\n\nYou can [`read`](crate::Reg::read) this register and get [`shorts::R`]. You can [`reset`](crate::Reg::reset), [`write`](crate::Reg::write), [`write_with_zero`](crate::Reg::write_with_zero) this register using [`shorts::W`]. You can also [`modify`](crate::Reg::modify) this register. See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [`mod@shorts`] module"]
#[doc(alias = "SHORTS")]
pub type Shorts = crate::Reg<shorts::ShortsSpec>;
#[doc = "Shortcuts for the QDEC."]
pub mod shorts;
#[doc = "INTENSET (rw) register accessor: Interrupt enable set register.\n\nYou can [`read`](crate::Reg::read) this register and get [`intenset::R`]. You can [`reset`](crate::Reg::reset), [`write`](crate::Reg::write), [`write_with_zero`](crate::Reg::write_with_zero) this register using [`intenset::W`]. You can also [`modify`](crate::Reg::modify) this register. See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [`mod@intenset`] module"]
#[doc(alias = "INTENSET")]
pub type Intenset = crate::Reg<intenset::IntensetSpec>;
#[doc = "Interrupt enable set register."]
pub mod intenset;
#[doc = "INTENCLR (rw) register accessor: Interrupt enable clear register.\n\nYou can [`read`](crate::Reg::read) this register and get [`intenclr::R`]. You can [`reset`](crate::Reg::reset), [`write`](crate::Reg::write), [`write_with_zero`](crate::Reg::write_with_zero) this register using [`intenclr::W`]. You can also [`modify`](crate::Reg::modify) this register. See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [`mod@intenclr`] module"]
#[doc(alias = "INTENCLR")]
pub type Intenclr = crate::Reg<intenclr::IntenclrSpec>;
#[doc = "Interrupt enable clear register."]
pub mod intenclr;
#[doc = "ENABLE (rw) register accessor: Enable the QDEC.\n\nYou can [`read`](crate::Reg::read) this register and get [`enable::R`]. You can [`reset`](crate::Reg::reset), [`write`](crate::Reg::write), [`write_with_zero`](crate::Reg::write_with_zero) this register using [`enable::W`]. You can also [`modify`](crate::Reg::modify) this register. See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [`mod@enable`] module"]
#[doc(alias = "ENABLE")]
pub type Enable = crate::Reg<enable::EnableSpec>;
#[doc = "Enable the QDEC."]
pub mod enable;
#[doc = "LEDPOL (rw) register accessor: LED output pin polarity.\n\nYou can [`read`](crate::Reg::read) this register and get [`ledpol::R`]. You can [`reset`](crate::Reg::reset), [`write`](crate::Reg::write), [`write_with_zero`](crate::Reg::write_with_zero) this register using [`ledpol::W`]. You can also [`modify`](crate::Reg::modify) this register. See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [`mod@ledpol`] module"]
#[doc(alias = "LEDPOL")]
pub type Ledpol = crate::Reg<ledpol::LedpolSpec>;
#[doc = "LED output pin polarity."]
pub mod ledpol;
#[doc = "SAMPLEPER (rw) register accessor: Sample period.\n\nYou can [`read`](crate::Reg::read) this register and get [`sampleper::R`]. You can [`reset`](crate::Reg::reset), [`write`](crate::Reg::write), [`write_with_zero`](crate::Reg::write_with_zero) this register using [`sampleper::W`]. You can also [`modify`](crate::Reg::modify) this register. See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [`mod@sampleper`] module"]
#[doc(alias = "SAMPLEPER")]
pub type Sampleper = crate::Reg<sampleper::SampleperSpec>;
#[doc = "Sample period."]
pub mod sampleper;
#[doc = "SAMPLE (r) register accessor: Motion sample value.\n\nYou can [`read`](crate::Reg::read) this register and get [`sample::R`]. See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [`mod@sample`] module"]
#[doc(alias = "SAMPLE")]
pub type Sample = crate::Reg<sample::SampleSpec>;
#[doc = "Motion sample value."]
pub mod sample;
#[doc = "REPORTPER (rw) register accessor: Number of samples to generate an EVENT_REPORTRDY.\n\nYou can [`read`](crate::Reg::read) this register and get [`reportper::R`]. You can [`reset`](crate::Reg::reset), [`write`](crate::Reg::write), [`write_with_zero`](crate::Reg::write_with_zero) this register using [`reportper::W`]. You can also [`modify`](crate::Reg::modify) this register. See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [`mod@reportper`] module"]
#[doc(alias = "REPORTPER")]
pub type Reportper = crate::Reg<reportper::ReportperSpec>;
#[doc = "Number of samples to generate an EVENT_REPORTRDY."]
pub mod reportper;
#[doc = "ACC (r) register accessor: Accumulated valid transitions register.\n\nYou can [`read`](crate::Reg::read) this register and get [`acc::R`]. See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [`mod@acc`] module"]
#[doc(alias = "ACC")]
pub type Acc = crate::Reg<acc::AccSpec>;
#[doc = "Accumulated valid transitions register."]
pub mod acc;
#[doc = "ACCREAD (r) register accessor: Snapshot of ACC register. Value generated by the TASKS_READCLEACC task.\n\nYou can [`read`](crate::Reg::read) this register and get [`accread::R`]. See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [`mod@accread`] module"]
#[doc(alias = "ACCREAD")]
pub type Accread = crate::Reg<accread::AccreadSpec>;
#[doc = "Snapshot of ACC register. Value generated by the TASKS_READCLEACC task."]
pub mod accread;
#[doc = "PSELLED (rw) register accessor: Pin select for LED output.\n\nYou can [`read`](crate::Reg::read) this register and get [`pselled::R`]. You can [`reset`](crate::Reg::reset), [`write`](crate::Reg::write), [`write_with_zero`](crate::Reg::write_with_zero) this register using [`pselled::W`]. You can also [`modify`](crate::Reg::modify) this register. See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [`mod@pselled`] module"]
#[doc(alias = "PSELLED")]
pub type Pselled = crate::Reg<pselled::PselledSpec>;
#[doc = "Pin select for LED output."]
pub mod pselled;
#[doc = "PSELA (rw) register accessor: Pin select for phase A input.\n\nYou can [`read`](crate::Reg::read) this register and get [`psela::R`]. You can [`reset`](crate::Reg::reset), [`write`](crate::Reg::write), [`write_with_zero`](crate::Reg::write_with_zero) this register using [`psela::W`]. You can also [`modify`](crate::Reg::modify) this register. See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [`mod@psela`] module"]
#[doc(alias = "PSELA")]
pub type Psela = crate::Reg<psela::PselaSpec>;
#[doc = "Pin select for phase A input."]
pub mod psela;
#[doc = "PSELB (rw) register accessor: Pin select for phase B input.\n\nYou can [`read`](crate::Reg::read) this register and get [`pselb::R`]. You can [`reset`](crate::Reg::reset), [`write`](crate::Reg::write), [`write_with_zero`](crate::Reg::write_with_zero) this register using [`pselb::W`]. You can also [`modify`](crate::Reg::modify) this register. See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [`mod@pselb`] module"]
#[doc(alias = "PSELB")]
pub type Pselb = crate::Reg<pselb::PselbSpec>;
#[doc = "Pin select for phase B input."]
pub mod pselb;
#[doc = "DBFEN (rw) register accessor: Enable debouncer input filters.\n\nYou can [`read`](crate::Reg::read) this register and get [`dbfen::R`]. You can [`reset`](crate::Reg::reset), [`write`](crate::Reg::write), [`write_with_zero`](crate::Reg::write_with_zero) this register using [`dbfen::W`]. You can also [`modify`](crate::Reg::modify) this register. See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [`mod@dbfen`] module"]
#[doc(alias = "DBFEN")]
pub type Dbfen = crate::Reg<dbfen::DbfenSpec>;
#[doc = "Enable debouncer input filters."]
pub mod dbfen;
#[doc = "LEDPRE (rw) register accessor: Time LED is switched ON before the sample.\n\nYou can [`read`](crate::Reg::read) this register and get [`ledpre::R`]. You can [`reset`](crate::Reg::reset), [`write`](crate::Reg::write), [`write_with_zero`](crate::Reg::write_with_zero) this register using [`ledpre::W`]. You can also [`modify`](crate::Reg::modify) this register. See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [`mod@ledpre`] module"]
#[doc(alias = "LEDPRE")]
pub type Ledpre = crate::Reg<ledpre::LedpreSpec>;
#[doc = "Time LED is switched ON before the sample."]
pub mod ledpre;
#[doc = "ACCDBL (r) register accessor: Accumulated double (error) transitions register.\n\nYou can [`read`](crate::Reg::read) this register and get [`accdbl::R`]. See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [`mod@accdbl`] module"]
#[doc(alias = "ACCDBL")]
pub type Accdbl = crate::Reg<accdbl::AccdblSpec>;
#[doc = "Accumulated double (error) transitions register."]
pub mod accdbl;
#[doc = "ACCDBLREAD (r) register accessor: Snapshot of ACCDBL register. Value generated by the TASKS_READCLEACC task.\n\nYou can [`read`](crate::Reg::read) this register and get [`accdblread::R`]. See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [`mod@accdblread`] module"]
#[doc(alias = "ACCDBLREAD")]
pub type Accdblread = crate::Reg<accdblread::AccdblreadSpec>;
#[doc = "Snapshot of ACCDBL register. Value generated by the TASKS_READCLEACC task."]
pub mod accdblread;
#[doc = "POWER (rw) register accessor: Peripheral power control.\n\nYou can [`read`](crate::Reg::read) this register and get [`power::R`]. You can [`reset`](crate::Reg::reset), [`write`](crate::Reg::write), [`write_with_zero`](crate::Reg::write_with_zero) this register using [`power::W`]. You can also [`modify`](crate::Reg::modify) this register. See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [`mod@power`] module"]
#[doc(alias = "POWER")]
pub type Power = crate::Reg<power::PowerSpec>;
#[doc = "Peripheral power control."]
pub mod power;
